import type { FleetLoadoutPermanence } from './fleetBuildLoadout';

export type FleetLoadoutQuickAddCategoryId =
  | 'recovery'
  | 'tire_air'
  | 'tools_repair'
  | 'spares'
  | 'fluids'
  | 'kitchen'
  | 'food_water'
  | 'camp_sleep'
  | 'shelter_furniture'
  | 'power'
  | 'navigation_comms'
  | 'safety_medical'
  | 'clothing_personal'
  | 'hygiene'
  | 'pets_family'
  | 'trail_work';

export type FleetLoadoutQuickAddCategory = {
  id: FleetLoadoutQuickAddCategoryId;
  label: string;
};

export type FleetLoadoutQuickAddCatalogItem = {
  id: string;
  name: string;
  categoryId: FleetLoadoutQuickAddCategoryId;
  category: string;
  typicalWeightLb: number;
  quantity?: number;
  permanence: FleetLoadoutPermanence;
};

export const FLEET_LOADOUT_QUICK_ADD_CATEGORIES: readonly FleetLoadoutQuickAddCategory[] = [
  { id: 'recovery', label: 'Recovery' },
  { id: 'tire_air', label: 'Tire / Air' },
  { id: 'tools_repair', label: 'Tools / Repair' },
  { id: 'spares', label: 'Spares' },
  { id: 'fluids', label: 'Fluids' },
  { id: 'kitchen', label: 'Kitchen' },
  { id: 'food_water', label: 'Food / Water' },
  { id: 'camp_sleep', label: 'Camp / Sleep' },
  { id: 'shelter_furniture', label: 'Shelter / Furniture' },
  { id: 'power', label: 'Power' },
  { id: 'navigation_comms', label: 'Nav / Comms' },
  { id: 'safety_medical', label: 'Safety / Medical' },
  { id: 'clothing_personal', label: 'Clothing / Personal' },
  { id: 'hygiene', label: 'Hygiene' },
  { id: 'pets_family', label: 'Pets / Family' },
  { id: 'trail_work', label: 'Trail Work' },
];

export const FLEET_LOADOUT_QUICK_ADD_CATALOG: readonly FleetLoadoutQuickAddCatalogItem[] = [
  { id: 'recovery_kinetic_rope', name: 'Kinetic recovery rope', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 14, permanence: 'always' },
  { id: 'recovery_static_strap', name: 'Static recovery strap', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 8, permanence: 'always' },
  { id: 'recovery_tree_saver', name: 'Tree saver strap', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 5, permanence: 'always' },
  { id: 'recovery_soft_shackles_pair', name: 'Soft shackles pair', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 2, permanence: 'always' },
  { id: 'recovery_steel_shackles_pair', name: 'Steel shackles pair', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 6, permanence: 'always' },
  { id: 'recovery_snatch_block', name: 'Snatch block pulley', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 8, permanence: 'always' },
  { id: 'recovery_winch_line_damper', name: 'Winch line damper', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 3, permanence: 'always' },
  { id: 'recovery_winch_remote', name: 'Winch remote', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 1, permanence: 'always' },
  { id: 'recovery_gloves', name: 'Recovery gloves', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 1, permanence: 'always' },
  { id: 'recovery_maxtrax_pair', name: 'Traction boards pair', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 16, permanence: 'always' },
  { id: 'recovery_fold_shovel', name: 'Folding recovery shovel', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 3, permanence: 'always' },
  { id: 'recovery_bottle_jack', name: 'Bottle jack', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 12, permanence: 'always' },
  { id: 'recovery_jack_base', name: 'Jack base plate', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 5, permanence: 'always' },
  { id: 'recovery_high_lift', name: 'Farm jack / high lift', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 30, permanence: 'trip' },
  { id: 'recovery_tow_hitch_receiver', name: 'Recovery hitch receiver', categoryId: 'recovery', category: 'recovery', typicalWeightLb: 6, permanence: 'always' },
  { id: 'tire_air_compressor', name: 'Portable air compressor', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 12, permanence: 'always' },
  { id: 'tire_air_hose_kit', name: 'Air hose kit', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 4, permanence: 'always' },
  { id: 'tire_air_deflators', name: 'Tire deflators', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tire_air_pressure_gauge', name: 'Tire pressure gauge', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tire_air_plug_kit', name: 'Tire plug kit', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 2, permanence: 'always' },
  { id: 'tire_air_valve_core_tool', name: 'Valve core tool', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tire_air_valve_stems', name: 'Spare valve stems', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tire_air_bead_sealer', name: 'Bead sealer', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'tire_air_patches', name: 'Patch kit', categoryId: 'tire_air', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tire_air_spare_tire', name: 'Full-size spare tire', categoryId: 'tire_air', category: 'spare', typicalWeightLb: 75, permanence: 'always' },
  { id: 'tire_air_lug_wrench', name: 'Lug wrench', categoryId: 'tire_air', category: 'tools', typicalWeightLb: 4, permanence: 'always' },
  { id: 'tire_air_torque_wrench', name: 'Torque wrench', categoryId: 'tire_air', category: 'tools', typicalWeightLb: 5, permanence: 'trip' },
  { id: 'tools_socket_set', name: 'Socket set', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 15, permanence: 'always' },
  { id: 'tools_wrench_roll', name: 'Wrench roll', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 12, permanence: 'always' },
  { id: 'tools_screwdriver_set', name: 'Screwdriver set', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 4, permanence: 'always' },
  { id: 'tools_pliers_set', name: 'Pliers set', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 5, permanence: 'always' },
  { id: 'tools_adjustable_wrench', name: 'Adjustable wrench', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 2, permanence: 'always' },
  { id: 'tools_hex_torx_keys', name: 'Hex / Torx keys', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 2, permanence: 'always' },
  { id: 'tools_hammer', name: 'Hammer', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 3, permanence: 'always' },
  { id: 'tools_pry_bar', name: 'Pry bar', categoryId: 'tools_repair', category: 'tools', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'tools_multimeter', name: 'Multimeter', categoryId: 'tools_repair', category: 'electrical', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tools_electrical_repair_kit', name: 'Electrical repair kit', categoryId: 'tools_repair', category: 'electrical', typicalWeightLb: 4, permanence: 'always' },
  { id: 'tools_diagnostic_scanner', name: 'OBD2 scanner', categoryId: 'tools_repair', category: 'telemetry', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tools_jb_weld_epoxy', name: 'Epoxy / JB Weld', categoryId: 'tools_repair', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tools_duct_tape', name: 'Duct tape', categoryId: 'tools_repair', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tools_zip_ties', name: 'Zip ties pack', categoryId: 'tools_repair', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tools_bailing_wire', name: 'Bailing wire', categoryId: 'tools_repair', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'tools_ratcheting_straps', name: 'Ratchet straps pair', categoryId: 'tools_repair', category: 'tie_down', typicalWeightLb: 5, permanence: 'always' },
  { id: 'tools_bungee_cords', name: 'Bungee cord set', categoryId: 'tools_repair', category: 'tie_down', typicalWeightLb: 2, permanence: 'always' },
  { id: 'tools_threadlocker', name: 'Threadlocker', categoryId: 'tools_repair', category: 'repair', typicalWeightLb: 1, permanence: 'always' },
  { id: 'spares_serpentine_belt', name: 'Serpentine belt', categoryId: 'spares', category: 'spare', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'spares_radiator_hose', name: 'Radiator hose', categoryId: 'spares', category: 'spare', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'spares_heater_hose', name: 'Heater hose', categoryId: 'spares', category: 'spare', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'spares_hose_clamps', name: 'Hose clamp kit', categoryId: 'spares', category: 'spare', typicalWeightLb: 1, permanence: 'always' },
  { id: 'spares_fuses', name: 'Fuse kit', categoryId: 'spares', category: 'electrical', typicalWeightLb: 1, permanence: 'always' },
  { id: 'spares_relays', name: 'Relay kit', categoryId: 'spares', category: 'electrical', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'spares_bulbs', name: 'Spare bulbs', categoryId: 'spares', category: 'electrical', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'spares_wiper_blades', name: 'Wiper blades', categoryId: 'spares', category: 'spare', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'spares_air_filter', name: 'Engine air filter', categoryId: 'spares', category: 'spare', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'spares_oil_filter', name: 'Oil filter', categoryId: 'spares', category: 'spare', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'spares_nuts_bolts', name: 'Nuts and bolts kit', categoryId: 'spares', category: 'spare', typicalWeightLb: 4, permanence: 'always' },
  { id: 'spares_battery_jump_pack', name: 'Jump starter pack', categoryId: 'spares', category: 'power', typicalWeightLb: 3, permanence: 'always' },
  { id: 'fluids_engine_oil_quart', name: 'Engine oil quart', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'fluids_coolant_gallon', name: 'Coolant gallon', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 9, permanence: 'trip' },
  { id: 'fluids_brake_fluid', name: 'Brake fluid', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'fluids_power_steering', name: 'Power steering fluid', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'fluids_transmission', name: 'Transmission fluid quart', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'fluids_gear_oil', name: 'Gear oil quart', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'fluids_washer_fluid', name: 'Washer fluid gallon', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 9, permanence: 'trip' },
  { id: 'fluids_fuel_can_empty', name: 'Empty fuel can', categoryId: 'fluids', category: 'fuel', typicalWeightLb: 10, permanence: 'trip' },
  { id: 'fluids_fuel_can_full_5gal', name: 'Fuel can full 5 gal', categoryId: 'fluids', category: 'fuel', typicalWeightLb: 42, permanence: 'trip' },
  { id: 'fluids_def_jug', name: 'DEF jug 2.5 gal', categoryId: 'fluids', category: 'fluid', typicalWeightLb: 24, permanence: 'trip' },
  { id: 'kitchen_stove', name: 'Camp stove', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 12, permanence: 'trip' },
  { id: 'kitchen_propane_1lb_pair', name: 'Propane bottles pair', categoryId: 'kitchen', category: 'fuel', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'kitchen_propane_5lb', name: 'Propane cylinder 5 lb', categoryId: 'kitchen', category: 'fuel', typicalWeightLb: 15, permanence: 'trip' },
  { id: 'kitchen_cookset', name: 'Cook pot set', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 5, permanence: 'trip' },
  { id: 'kitchen_cast_iron_pan', name: 'Cast iron pan', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 8, permanence: 'trip' },
  { id: 'kitchen_utensil_roll', name: 'Cooking utensil roll', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_dishes_set', name: 'Dishes set', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'kitchen_silverware_set', name: 'Silverware set', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_cups_mugs', name: 'Cups / mugs set', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_cutting_board', name: 'Cutting board', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_knife_set', name: 'Kitchen knife set', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_coffee_kit', name: 'Coffee kit', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 3, permanence: 'trip' },
  { id: 'kitchen_kettle', name: 'Kettle', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_spice_kit', name: 'Spice kit', categoryId: 'kitchen', category: 'food', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_wash_bin', name: 'Dish wash bin', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_biodegradable_soap', name: 'Camp dish soap', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'kitchen_paper_towels', name: 'Paper towels roll', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'kitchen_trash_bags', name: 'Trash bags roll', categoryId: 'kitchen', category: 'camp', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_french_press', name: 'French press', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_coffee_grinder', name: 'Coffee grinder', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_collapsible_sink', name: 'Collapsible sink', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_drying_rack', name: 'Dish drying rack', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_foil_wrap', name: 'Foil / plastic wrap kit', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'kitchen_food_storage_bags', name: 'Food storage bags', categoryId: 'kitchen', category: 'kitchen', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'kitchen_ice_packs', name: 'Reusable ice packs', categoryId: 'kitchen', category: 'food', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'food_water_water_jug_5gal_full', name: 'Water jug full 5 gal', categoryId: 'food_water', category: 'water', typicalWeightLb: 42, permanence: 'trip' },
  { id: 'food_water_water_jug_7gal_full', name: 'Water jug full 7 gal', categoryId: 'food_water', category: 'water', typicalWeightLb: 58, permanence: 'trip' },
  { id: 'food_water_water_filter', name: 'Water filter', categoryId: 'food_water', category: 'water', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'food_water_hydration_bladders', name: 'Hydration bladders pair', categoryId: 'food_water', category: 'water', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'food_water_cooler_empty', name: 'Cooler empty', categoryId: 'food_water', category: 'food', typicalWeightLb: 25, permanence: 'trip' },
  { id: 'food_water_cooler_loaded', name: 'Cooler loaded', categoryId: 'food_water', category: 'food', typicalWeightLb: 55, permanence: 'trip' },
  { id: 'food_water_dry_food_bin', name: 'Dry food bin', categoryId: 'food_water', category: 'food', typicalWeightLb: 25, permanence: 'trip' },
  { id: 'food_water_snack_bin', name: 'Snack bin', categoryId: 'food_water', category: 'food', typicalWeightLb: 8, permanence: 'trip' },
  { id: 'food_water_freeze_dried_meals', name: 'Freeze dried meals pack', categoryId: 'food_water', category: 'food', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'food_water_ice_bag', name: 'Ice bag', categoryId: 'food_water', category: 'food', typicalWeightLb: 10, permanence: 'trip' },
  { id: 'food_water_bear_canister', name: 'Bear canister', categoryId: 'food_water', category: 'food', typicalWeightLb: 3, permanence: 'trip' },
  { id: 'camp_sleep_tent', name: 'Ground tent', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 18, permanence: 'trip' },
  { id: 'camp_sleep_rooftop_ladder', name: 'Rooftop tent ladder', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 10, permanence: 'always' },
  { id: 'camp_sleep_sleeping_bag', name: 'Sleeping bag', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 5, permanence: 'trip' },
  { id: 'camp_sleep_sleeping_pad', name: 'Sleeping pad', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'camp_sleep_pillow', name: 'Camp pillow', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'camp_sleep_blanket', name: 'Camp blanket', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'camp_sleep_hammock', name: 'Hammock', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'camp_sleep_sleep_system_bin', name: 'Sleep system bin', categoryId: 'camp_sleep', category: 'sleep', typicalWeightLb: 20, permanence: 'trip' },
  { id: 'camp_sleep_heated_blanket', name: 'Heated blanket', categoryId: 'camp_sleep', category: 'power', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'camp_sleep_extra_tarp_floor', name: 'Tent footprint / tarp', categoryId: 'camp_sleep', category: 'shelter', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'shelter_awning', name: 'Vehicle awning', categoryId: 'shelter_furniture', category: 'shelter', typicalWeightLb: 35, permanence: 'always' },
  { id: 'shelter_awning_room', name: 'Awning room', categoryId: 'shelter_furniture', category: 'shelter', typicalWeightLb: 18, permanence: 'trip' },
  { id: 'shelter_tarp', name: 'Large tarp', categoryId: 'shelter_furniture', category: 'shelter', typicalWeightLb: 6, permanence: 'trip' },
  { id: 'shelter_poles', name: 'Tarp poles set', categoryId: 'shelter_furniture', category: 'shelter', typicalWeightLb: 8, permanence: 'trip' },
  { id: 'shelter_stakes_guy_lines', name: 'Stakes and guy lines', categoryId: 'shelter_furniture', category: 'shelter', typicalWeightLb: 3, permanence: 'trip' },
  { id: 'shelter_camp_chair', name: 'Camp chair', categoryId: 'shelter_furniture', category: 'furniture', typicalWeightLb: 10, permanence: 'trip' },
  { id: 'shelter_camp_table', name: 'Camp table', categoryId: 'shelter_furniture', category: 'furniture', typicalWeightLb: 15, permanence: 'trip' },
  { id: 'shelter_stool', name: 'Camp stool', categoryId: 'shelter_furniture', category: 'furniture', typicalWeightLb: 3, permanence: 'trip' },
  { id: 'shelter_lantern_stand', name: 'Lantern stand', categoryId: 'shelter_furniture', category: 'furniture', typicalWeightLb: 5, permanence: 'trip' },
  { id: 'shelter_ground_mat', name: 'Ground mat', categoryId: 'shelter_furniture', category: 'camp', typicalWeightLb: 8, permanence: 'trip' },
  { id: 'shelter_fire_pan', name: 'Fire pan', categoryId: 'shelter_furniture', category: 'camp', typicalWeightLb: 12, permanence: 'trip' },
  { id: 'shelter_firewood_bundle', name: 'Firewood bundle', categoryId: 'shelter_furniture', category: 'camp', typicalWeightLb: 20, permanence: 'trip' },
  { id: 'power_station_small', name: 'Portable power station small', categoryId: 'power', category: 'power', typicalWeightLb: 18, permanence: 'trip' },
  { id: 'power_station_medium', name: 'Portable power station medium', categoryId: 'power', category: 'power', typicalWeightLb: 35, permanence: 'trip' },
  { id: 'power_station_large', name: 'Portable power station large', categoryId: 'power', category: 'power', typicalWeightLb: 55, permanence: 'trip' },
  { id: 'power_solar_panel_100w', name: 'Solar panel 100 W', categoryId: 'power', category: 'power', typicalWeightLb: 12, permanence: 'trip' },
  { id: 'power_solar_panel_200w', name: 'Solar panel 200 W', categoryId: 'power', category: 'power', typicalWeightLb: 22, permanence: 'trip' },
  { id: 'power_extension_cord', name: 'Extension cord', categoryId: 'power', category: 'power', typicalWeightLb: 5, permanence: 'trip' },
  { id: 'power_usb_cables', name: 'USB cable kit', categoryId: 'power', category: 'power', typicalWeightLb: 1, permanence: 'always' },
  { id: 'power_inverter', name: 'Power inverter', categoryId: 'power', category: 'power', typicalWeightLb: 6, permanence: 'always' },
  { id: 'power_battery_charger', name: 'Battery charger', categoryId: 'power', category: 'power', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'power_headlamps_pair', name: 'Headlamps pair', categoryId: 'power', category: 'lighting', typicalWeightLb: 1, permanence: 'always' },
  { id: 'power_lantern', name: 'Camp lantern', categoryId: 'power', category: 'lighting', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'power_flashlight', name: 'Flashlight', categoryId: 'power', category: 'lighting', typicalWeightLb: 1, permanence: 'always' },
  { id: 'power_spare_batteries', name: 'Spare batteries pack', categoryId: 'power', category: 'power', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'nav_paper_maps', name: 'Paper maps', categoryId: 'navigation_comms', category: 'navigation', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'nav_compass', name: 'Compass', categoryId: 'navigation_comms', category: 'navigation', typicalWeightLb: 1, permanence: 'always' },
  { id: 'nav_gps_unit', name: 'Handheld GPS', categoryId: 'navigation_comms', category: 'navigation', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'nav_sat_messenger', name: 'Satellite messenger', categoryId: 'navigation_comms', category: 'comms', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'nav_handheld_radio', name: 'Handheld radio', categoryId: 'navigation_comms', category: 'comms', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'nav_radio_charger', name: 'Radio charger', categoryId: 'navigation_comms', category: 'comms', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'nav_tablet_mount', name: 'Tablet mount', categoryId: 'navigation_comms', category: 'navigation', typicalWeightLb: 2, permanence: 'always' },
  { id: 'nav_tablet', name: 'Trail tablet', categoryId: 'navigation_comms', category: 'navigation', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'nav_binoculars', name: 'Binoculars', categoryId: 'navigation_comms', category: 'navigation', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'nav_notebook_pencils', name: 'Notebook and pencils', categoryId: 'navigation_comms', category: 'navigation', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'safety_first_aid_kit', name: 'First aid kit', categoryId: 'safety_medical', category: 'medical', typicalWeightLb: 5, permanence: 'always' },
  { id: 'safety_trauma_kit', name: 'Trauma kit', categoryId: 'safety_medical', category: 'medical', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'safety_fire_extinguisher', name: 'Fire extinguisher', categoryId: 'safety_medical', category: 'safety', typicalWeightLb: 5, permanence: 'always' },
  { id: 'safety_emergency_blanket', name: 'Emergency blankets pack', categoryId: 'safety_medical', category: 'safety', typicalWeightLb: 1, permanence: 'always' },
  { id: 'safety_signal_mirror', name: 'Signal mirror', categoryId: 'safety_medical', category: 'safety', typicalWeightLb: 1, permanence: 'always' },
  { id: 'safety_whistle', name: 'Whistle', categoryId: 'safety_medical', category: 'safety', typicalWeightLb: 1, permanence: 'always' },
  { id: 'safety_road_flares', name: 'Road flares', categoryId: 'safety_medical', category: 'safety', typicalWeightLb: 2, permanence: 'always' },
  { id: 'safety_reflective_triangles', name: 'Reflective triangles', categoryId: 'safety_medical', category: 'safety', typicalWeightLb: 4, permanence: 'always' },
  { id: 'safety_sunscreen', name: 'Sunscreen', categoryId: 'safety_medical', category: 'medical', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'safety_insect_repellent', name: 'Insect repellent', categoryId: 'safety_medical', category: 'medical', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'safety_medications', name: 'Personal medications', categoryId: 'safety_medical', category: 'medical', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'safety_eye_wash', name: 'Eye wash', categoryId: 'safety_medical', category: 'medical', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'clothing_rain_jacket', name: 'Rain jacket', categoryId: 'clothing_personal', category: 'clothing', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'clothing_insulated_jacket', name: 'Insulated jacket', categoryId: 'clothing_personal', category: 'clothing', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'clothing_base_layers', name: 'Base layers set', categoryId: 'clothing_personal', category: 'clothing', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'clothing_extra_socks', name: 'Extra socks pack', categoryId: 'clothing_personal', category: 'clothing', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'clothing_gloves_beanie', name: 'Gloves and beanie', categoryId: 'clothing_personal', category: 'clothing', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'clothing_boots', name: 'Camp boots', categoryId: 'clothing_personal', category: 'clothing', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'clothing_warm_hat', name: 'Sun hat / warm hat', categoryId: 'clothing_personal', category: 'clothing', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'clothing_day_pack', name: 'Day pack', categoryId: 'clothing_personal', category: 'personal', typicalWeightLb: 3, permanence: 'trip' },
  { id: 'clothing_sunglasses_case', name: 'Sunglasses and case', categoryId: 'clothing_personal', category: 'personal', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'clothing_towels', name: 'Camp towels', categoryId: 'clothing_personal', category: 'personal', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'hygiene_toiletry_kit', name: 'Toiletry kit', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 3, permanence: 'trip' },
  { id: 'hygiene_toilet_paper', name: 'Toilet paper', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'hygiene_wag_bags', name: 'WAG bags', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'hygiene_trowel', name: 'Camp trowel', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'hygiene_hand_sanitizer', name: 'Hand sanitizer', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'hygiene_wet_wipes', name: 'Wet wipes pack', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'hygiene_shower_bag', name: 'Solar shower bag', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'hygiene_privacy_shelter', name: 'Privacy shelter', categoryId: 'hygiene', category: 'shelter', typicalWeightLb: 10, permanence: 'trip' },
  { id: 'hygiene_laundry_bag', name: 'Laundry bag', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'hygiene_microfiber_cloths', name: 'Microfiber cloths', categoryId: 'hygiene', category: 'hygiene', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'pets_dog_food_bin', name: 'Dog food bin', categoryId: 'pets_family', category: 'pets', typicalWeightLb: 12, permanence: 'trip' },
  { id: 'pets_water_bowl', name: 'Pet water bowl', categoryId: 'pets_family', category: 'pets', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'pets_leash_harness', name: 'Leash and harness', categoryId: 'pets_family', category: 'pets', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'pets_pet_first_aid', name: 'Pet first aid kit', categoryId: 'pets_family', category: 'pets', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'family_child_seat', name: 'Child seat', categoryId: 'pets_family', category: 'family', typicalWeightLb: 15, permanence: 'trip' },
  { id: 'family_kid_activity_bin', name: 'Kid activity bin', categoryId: 'pets_family', category: 'family', typicalWeightLb: 6, permanence: 'trip' },
  { id: 'family_extra_blanket', name: 'Extra family blanket', categoryId: 'pets_family', category: 'family', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'family_baby_wipes_diapers', name: 'Diapers / wipes pack', categoryId: 'pets_family', category: 'family', typicalWeightLb: 6, permanence: 'trip' },
  { id: 'trail_work_chainsaw', name: 'Chainsaw', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 14, permanence: 'trip' },
  { id: 'trail_work_chainsaw_fuel', name: 'Chainsaw fuel / bar oil', categoryId: 'trail_work', category: 'fluid', typicalWeightLb: 8, permanence: 'trip' },
  { id: 'trail_work_handsaw', name: 'Folding saw', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'trail_work_axe', name: 'Axe', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 5, permanence: 'trip' },
  { id: 'trail_work_hatchet', name: 'Hatchet', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'trail_work_machete', name: 'Machete', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 2, permanence: 'trip' },
  { id: 'trail_work_work_gloves', name: 'Work gloves', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 1, permanence: 'always' },
  { id: 'trail_work_safety_glasses', name: 'Safety glasses', categoryId: 'trail_work', category: 'safety', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'trail_work_loppers', name: 'Loppers', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 4, permanence: 'trip' },
  { id: 'trail_work_garden_shovel', name: 'Full-size shovel', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 5, permanence: 'trip' },
  { id: 'trail_work_trash_grabber', name: 'Trash grabber', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 1, permanence: 'trip' },
  { id: 'trail_work_trash_bags_heavy', name: 'Heavy trash bags', categoryId: 'trail_work', category: 'trail_work', typicalWeightLb: 3, permanence: 'trip' },
];

export function getFleetLoadoutQuickAddItemsForCategory(categoryId: FleetLoadoutQuickAddCategoryId): readonly FleetLoadoutQuickAddCatalogItem[] {
  return FLEET_LOADOUT_QUICK_ADD_CATALOG.filter((item) => item.categoryId === categoryId);
}
