import type { FuelType } from '../vehicleSpecStore';

export type FleetOemSpecSource = 'ecs_oem_reference' | 'ecs_model_estimate';

export type FleetOemVehicleSpec = {
  base_weight_lb: number;
  gvwr_lb: number;
  payload_capacity_lb?: number | null;
  fuel_tank_capacity_gal: number;
  fuel_type: FuelType;
  ground_clearance_inches?: number | null;
  wheelbase_in?: number | null;
  overall_length_in?: number | null;
  overall_width_in?: number | null;
  overall_height_in?: number | null;
  track_width_front_in?: number | null;
  track_width_rear_in?: number | null;
  approach_angle_deg?: number | null;
  breakover_angle_deg?: number | null;
  departure_angle_deg?: number | null;
  turning_diameter_ft?: number | null;
};

export type FleetOemVehicleSpecReference = {
  id: string;
  label: string;
  make: string;
  model: string;
  trim?: string | null;
  vehicleType: string;
  yearStart: number;
  yearEnd?: number | null;
  source: FleetOemSpecSource;
  confidence: number;
  notes: string;
  specs: FleetOemVehicleSpec;
};

export type FleetOemSpecMatch =
  | {
      status: 'matched';
      reference: FleetOemVehicleSpecReference;
      message: string;
    }
  | {
      status: 'unsupported_year' | 'not_found' | 'incomplete';
      reference: null;
      message: string;
    };

function normalizeVehicleText(value: string | number | null | undefined): string {
  return String(value ?? '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function makeMatches(inputMake: string, referenceMake: string): boolean {
  if (inputMake === referenceMake || inputMake.includes(referenceMake) || referenceMake.includes(inputMake)) return true;
  const chevyInput = inputMake === 'chevy' || inputMake === 'chevrolet';
  const chevyRef = referenceMake === 'chevy' || referenceMake === 'chevrolet';
  const mercedesInput = inputMake === 'mercedes' || inputMake === 'mercedes benz';
  const mercedesRef = referenceMake === 'mercedes' || referenceMake === 'mercedes benz';
  return (chevyInput && chevyRef) || (mercedesInput && mercedesRef);
}

function modelMatches(inputModel: string, referenceModel: string, search: string): boolean {
  if (inputModel === referenceModel) return true;
  if (inputModel.includes(referenceModel) || referenceModel.includes(inputModel)) return true;
  return search.includes(referenceModel);
}

function yearInRange(year: number | null, reference: FleetOemVehicleSpecReference): boolean {
  if (year == null) return true;
  if (year < reference.yearStart) return false;
  if (reference.yearEnd != null && year > reference.yearEnd) return false;
  return true;
}

const currentModelYear = new Date().getFullYear() + 1;

export const FLEET_OEM_SPEC_REFERENCES: readonly FleetOemVehicleSpecReference[] = [
  {
    id: 'ford-bronco-2021-4door-reference',
    label: 'Ford Bronco 4-door OEM reference',
    make: 'ford',
    model: 'bronco',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2021,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 88,
    notes: 'Modern Bronco reference range. Verify trim, Sasquatch package, tire package, and door placard before final payload decisions.',
    specs: {
      base_weight_lb: 4700,
      gvwr_lb: 6100,
      fuel_tank_capacity_gal: 20.8,
      fuel_type: 'gas',
      ground_clearance_inches: 8.4,
      wheelbase_in: 116.1,
      overall_width_in: 75.9,
      overall_height_in: 73.0,
      approach_angle_deg: 35.5,
      breakover_angle_deg: 20.0,
      departure_angle_deg: 29.8,
      turning_diameter_ft: 40.0,
    },
  },
  {
    id: 'jeep-wrangler-jk-2010-reference',
    label: 'Jeep Wrangler JK 2010-2017 OEM reference',
    make: 'jeep',
    model: 'wrangler',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: 2017,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Wrangler JK values vary by two-door/four-door, Rubicon, tire package, and hardtop/soft-top equipment. Verify placard.',
    specs: {
      base_weight_lb: 4300,
      gvwr_lb: 5400,
      payload_capacity_lb: 1000,
      fuel_tank_capacity_gal: 22.5,
      fuel_type: 'gas',
      ground_clearance_inches: 10.0,
      wheelbase_in: 116.0,
      overall_width_in: 73.7,
      overall_height_in: 72.6,
      approach_angle_deg: 42.2,
      breakover_angle_deg: 21.2,
      departure_angle_deg: 32.3,
      turning_diameter_ft: 41.2,
    },
  },
  {
    id: 'toyota-tacoma-2024-reference',
    label: 'Toyota Tacoma OEM reference',
    make: 'toyota',
    model: 'tacoma',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2016,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 86,
    notes: 'Tacoma range varies heavily by cab, drivetrain, bed, hybrid, and off-road package.',
    specs: {
      base_weight_lb: 4480,
      gvwr_lb: 5600,
      fuel_tank_capacity_gal: 21.1,
      fuel_type: 'gas',
      ground_clearance_inches: 9.4,
      wheelbase_in: 127.4,
      overall_width_in: 75.2,
      overall_height_in: 73.8,
      turning_diameter_ft: 40.6,
    },
  },
  {
    id: 'toyota-4runner-2010-reference',
    label: 'Toyota 4Runner OEM reference',
    make: 'toyota',
    model: '4runner',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 86,
    notes: '4Runner reference range; verify trim and tire package.',
    specs: {
      base_weight_lb: 4675,
      gvwr_lb: 5750,
      fuel_tank_capacity_gal: 23.0,
      fuel_type: 'gas',
      ground_clearance_inches: 9.6,
      wheelbase_in: 109.8,
      overall_width_in: 75.8,
      overall_height_in: 71.5,
      turning_diameter_ft: 37.4,
    },
  },
  {
    id: 'ford-f150-2015-reference',
    label: 'Ford F-150 OEM reference',
    make: 'ford',
    model: 'f 150',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2015,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'F-150 specs vary by cab, bed, engine, axle package, and payload package. Door placard is required for final payload.',
    specs: {
      base_weight_lb: 5200,
      gvwr_lb: 7050,
      fuel_tank_capacity_gal: 36.0,
      fuel_type: 'gas',
      ground_clearance_inches: 9.4,
      wheelbase_in: 145.0,
      overall_width_in: 79.9,
      overall_height_in: 77.2,
      turning_diameter_ft: 47.8,
    },
  },
  {
    id: 'ram-2500-2019-reference',
    label: 'RAM 2500 OEM reference',
    make: 'ram',
    model: '2500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Heavy-duty payload and weight vary materially by engine, cab, bed, and axle rating.',
    specs: {
      base_weight_lb: 7400,
      gvwr_lb: 10000,
      fuel_tank_capacity_gal: 32.0,
      fuel_type: 'diesel',
      ground_clearance_inches: 8.5,
      wheelbase_in: 149.0,
      overall_width_in: 79.4,
      overall_height_in: 80.2,
      turning_diameter_ft: 49.2,
    },
  },
  {
    id: 'jeep-wrangler-2018-reference',
    label: 'Jeep Wrangler OEM reference',
    make: 'jeep',
    model: 'wrangler',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2018,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 86,
    notes: 'Wrangler reference range. Two-door, four-door, 4xe, Rubicon, and 392 specs differ.',
    specs: {
      base_weight_lb: 4800,
      gvwr_lb: 5700,
      fuel_tank_capacity_gal: 21.5,
      fuel_type: 'gas',
      ground_clearance_inches: 10.8,
      wheelbase_in: 118.4,
      overall_width_in: 73.8,
      overall_height_in: 73.6,
      approach_angle_deg: 43.9,
      breakover_angle_deg: 22.6,
      departure_angle_deg: 37.0,
      turning_diameter_ft: 40.8,
    },
  },
  {
    id: 'jeep-grand-cherokee-2011-reference',
    label: 'Jeep Grand Cherokee 2011-2021 OEM reference',
    make: 'jeep',
    model: 'grand cherokee',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2011,
    yearEnd: 2021,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Grand Cherokee WK2 values vary by engine, Trailhawk, air suspension, tire package, and drivetrain. Verify placard.',
    specs: {
      base_weight_lb: 5000,
      gvwr_lb: 6500,
      payload_capacity_lb: 1250,
      fuel_tank_capacity_gal: 24.6,
      fuel_type: 'gas',
      ground_clearance_inches: 8.6,
      wheelbase_in: 114.8,
      overall_width_in: 76.5,
      overall_height_in: 69.3,
      turning_diameter_ft: 37.1,
    },
  },
  {
    id: 'jeep-grand-cherokee-2022-reference',
    label: 'Jeep Grand Cherokee 2022+ OEM reference',
    make: 'jeep',
    model: 'grand cherokee',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2022,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Modern Grand Cherokee values vary by two-row/three-row, 4xe, Trailhawk, air suspension, and trim. Verify placard.',
    specs: {
      base_weight_lb: 5050,
      gvwr_lb: 6500,
      payload_capacity_lb: 1200,
      fuel_tank_capacity_gal: 23.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.4,
      wheelbase_in: 116.7,
      overall_width_in: 77.5,
      overall_height_in: 70.8,
      turning_diameter_ft: 38.0,
    },
  },
  {
    id: 'jeep-cherokee-2014-reference',
    label: 'Jeep Cherokee 2014-2023 OEM reference',
    make: 'jeep',
    model: 'cherokee',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2014,
    yearEnd: 2023,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Cherokee KL values vary by Trailhawk, engine, AWD system, tire package, and trim. Verify placard.',
    specs: {
      base_weight_lb: 4100,
      gvwr_lb: 5500,
      payload_capacity_lb: 1200,
      fuel_tank_capacity_gal: 15.8,
      fuel_type: 'gas',
      ground_clearance_inches: 8.7,
      wheelbase_in: 106.5,
      overall_width_in: 73.2,
      overall_height_in: 67.8,
      turning_diameter_ft: 37.6,
    },
  },
  {
    id: 'honda-passport-trailsport-2022-reference',
    label: 'Honda Passport TrailSport OEM reference',
    make: 'honda',
    model: 'passport',
    trim: 'trailsport',
    vehicleType: 'suv',
    yearStart: 2022,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 88,
    notes: 'Passport TrailSport SUV reference range. Verify exact trim, AWD package, accessories, and door placard before final payload decisions.',
    specs: {
      base_weight_lb: 4300,
      gvwr_lb: 5500,
      payload_capacity_lb: 1200,
      fuel_tank_capacity_gal: 19.5,
      fuel_type: 'gas',
      ground_clearance_inches: 8.1,
      wheelbase_in: 110.9,
      overall_width_in: 78.6,
      overall_height_in: 72.2,
      overall_length_in: 189.1,
      turning_diameter_ft: 39.5,
    },
  },
  {
    id: 'subaru-outback-2020-reference',
    label: 'Subaru Outback OEM reference',
    make: 'subaru',
    model: 'outback',
    trim: null,
    vehicleType: 'wagon',
    yearStart: 2020,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 86,
    notes: 'Outback reference range. Wilderness trim changes clearance and tire assumptions.',
    specs: {
      base_weight_lb: 3900,
      gvwr_lb: 5050,
      fuel_tank_capacity_gal: 18.5,
      fuel_type: 'gas',
      ground_clearance_inches: 8.7,
      wheelbase_in: 108.1,
      overall_width_in: 73.0,
      overall_height_in: 66.4,
      turning_diameter_ft: 36.1,
    },
  },
  {
    id: 'ford-transit-awd-2020-reference',
    label: 'Ford Transit AWD OEM reference',
    make: 'ford',
    model: 'transit',
    trim: null,
    vehicleType: 'van',
    yearStart: 2020,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Transit van height, wheelbase, GVWR, and fuel capacity vary by roof, body length, and package.',
    specs: {
      base_weight_lb: 6300,
      gvwr_lb: 9500,
      fuel_tank_capacity_gal: 25.0,
      fuel_type: 'gas',
      ground_clearance_inches: 6.0,
      wheelbase_in: 148.0,
      overall_width_in: 81.3,
      overall_height_in: 100.8,
      turning_diameter_ft: 48.0,
    },
  },
  {
    id: 'mercedes-sprinter-awd-reference',
    label: 'Mercedes Sprinter AWD OEM reference',
    make: 'mercedes',
    model: 'sprinter',
    trim: null,
    vehicleType: 'van',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Sprinter specs vary by wheelbase, roof height, and GVWR. Verify conversion weight and door placard.',
    specs: {
      base_weight_lb: 6100,
      gvwr_lb: 8550,
      fuel_tank_capacity_gal: 24.5,
      fuel_type: 'diesel',
      ground_clearance_inches: 6.9,
      wheelbase_in: 144.0,
      overall_width_in: 80.0,
      overall_height_in: 102.8,
      turning_diameter_ft: 47.0,
    },
  },
  {
    id: 'toyota-rav4-2019-reference',
    label: 'Toyota RAV4 OEM reference',
    make: 'toyota',
    model: 'rav4',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'RAV4 reference range. Hybrid and TRD Off-Road values differ.',
    specs: {
      base_weight_lb: 3900,
      gvwr_lb: 5060,
      fuel_tank_capacity_gal: 14.5,
      fuel_type: 'gas',
      ground_clearance_inches: 8.6,
      wheelbase_in: 105.9,
      overall_width_in: 73.0,
      overall_height_in: 68.6,
      turning_diameter_ft: 36.1,
    },
  },
  {
    id: 'toyota-tundra-2014-reference',
    label: 'Toyota Tundra 2014-2021 OEM reference',
    make: 'toyota',
    model: 'tundra',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2014,
    yearEnd: 2021,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Tundra payload, fuel tank, axle, and curb weight vary by cab, bed, drivetrain, and tow package. Verify door placard.',
    specs: {
      base_weight_lb: 5600,
      gvwr_lb: 7200,
      payload_capacity_lb: 1600,
      fuel_tank_capacity_gal: 38.0,
      fuel_type: 'gas',
      ground_clearance_inches: 10.4,
      wheelbase_in: 145.7,
      overall_width_in: 79.9,
      overall_height_in: 76.2,
      turning_diameter_ft: 44.0,
    },
  },
  {
    id: 'toyota-tundra-2022-reference',
    label: 'Toyota Tundra 2022+ OEM reference',
    make: 'toyota',
    model: 'tundra',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2022,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Modern Tundra reference range. Hybrid, cab, bed, TRD, and payload packages materially change exact specs.',
    specs: {
      base_weight_lb: 5700,
      gvwr_lb: 7580,
      payload_capacity_lb: 1750,
      fuel_tank_capacity_gal: 32.2,
      fuel_type: 'gas',
      ground_clearance_inches: 9.3,
      wheelbase_in: 145.7,
      overall_width_in: 80.2,
      overall_height_in: 78.0,
      turning_diameter_ft: 48.6,
    },
  },
  {
    id: 'toyota-sequoia-2010-reference',
    label: 'Toyota Sequoia 2010-2022 OEM reference',
    make: 'toyota',
    model: 'sequoia',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: 2022,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Sequoia full-size SUV values vary by trim, drivetrain, and seating package. Verify payload placard.',
    specs: {
      base_weight_lb: 5900,
      gvwr_lb: 7300,
      payload_capacity_lb: 1400,
      fuel_tank_capacity_gal: 26.4,
      fuel_type: 'gas',
      ground_clearance_inches: 9.9,
      wheelbase_in: 122.0,
      overall_width_in: 79.9,
      overall_height_in: 77.0,
      turning_diameter_ft: 38.1,
    },
  },
  {
    id: 'toyota-sequoia-2023-reference',
    label: 'Toyota Sequoia 2023+ OEM reference',
    make: 'toyota',
    model: 'sequoia',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2023,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Modern Sequoia hybrid SUV reference. Verify trim, seating, tire package, and door placard before payload decisions.',
    specs: {
      base_weight_lb: 6000,
      gvwr_lb: 7560,
      payload_capacity_lb: 1500,
      fuel_tank_capacity_gal: 22.5,
      fuel_type: 'gas',
      ground_clearance_inches: 8.6,
      wheelbase_in: 122.0,
      overall_width_in: 79.6,
      overall_height_in: 74.5,
      turning_diameter_ft: 39.2,
    },
  },
  {
    id: 'toyota-land-cruiser-200-2010-reference',
    label: 'Toyota Land Cruiser 200 Series OEM reference',
    make: 'toyota',
    model: 'land cruiser',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: 2021,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Land Cruiser 200 reference range. Verify market, trim, and payload placard; accessories reduce remaining payload quickly.',
    specs: {
      base_weight_lb: 5800,
      gvwr_lb: 7385,
      payload_capacity_lb: 1500,
      fuel_tank_capacity_gal: 24.6,
      fuel_type: 'gas',
      ground_clearance_inches: 8.9,
      wheelbase_in: 112.2,
      overall_width_in: 78.0,
      overall_height_in: 74.0,
      turning_diameter_ft: 38.7,
    },
  },
  {
    id: 'toyota-highlander-2020-reference',
    label: 'Toyota Highlander 2020+ OEM reference',
    make: 'toyota',
    model: 'highlander',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2020,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Highlander crossover reference. Hybrid and AWD trims vary; verify placard before cargo and trail-fit calculations.',
    specs: {
      base_weight_lb: 4300,
      gvwr_lb: 5950,
      payload_capacity_lb: 1450,
      fuel_tank_capacity_gal: 17.9,
      fuel_type: 'gas',
      ground_clearance_inches: 8.0,
      wheelbase_in: 112.2,
      overall_width_in: 76.0,
      overall_height_in: 68.1,
      turning_diameter_ft: 37.4,
    },
  },
  {
    id: 'lexus-gx-2010-reference',
    label: 'Lexus GX OEM reference',
    make: 'lexus',
    model: 'gx',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Lexus GX reference range. Verify trim, third row, tire package, and door placard.',
    specs: {
      base_weight_lb: 5200,
      gvwr_lb: 6600,
      payload_capacity_lb: 1300,
      fuel_tank_capacity_gal: 23.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.1,
      wheelbase_in: 109.8,
      overall_width_in: 74.2,
      overall_height_in: 74.2,
      turning_diameter_ft: 38.1,
    },
  },
  {
    id: 'lexus-lx-2010-reference',
    label: 'Lexus LX 2010-2021 OEM reference',
    make: 'lexus',
    model: 'lx',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: 2021,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Lexus LX reference range. Verify market, trim, tire package, and door placard.',
    specs: {
      base_weight_lb: 6000,
      gvwr_lb: 7385,
      payload_capacity_lb: 1300,
      fuel_tank_capacity_gal: 24.6,
      fuel_type: 'gas',
      ground_clearance_inches: 8.9,
      wheelbase_in: 112.2,
      overall_width_in: 78.0,
      overall_height_in: 75.2,
      turning_diameter_ft: 38.7,
    },
  },
  {
    id: 'ford-super-duty-2017-reference',
    label: 'Ford Super Duty 2017+ OEM reference',
    make: 'ford',
    model: 'f 250',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2017,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'Super Duty specs vary widely by F-250/F-350, cab, bed, axle, engine, and payload package. Verify door placard.',
    specs: {
      base_weight_lb: 7350,
      gvwr_lb: 10000,
      payload_capacity_lb: 2500,
      fuel_tank_capacity_gal: 34.0,
      fuel_type: 'diesel',
      ground_clearance_inches: 8.5,
      wheelbase_in: 160.0,
      overall_width_in: 80.0,
      overall_height_in: 81.5,
      turning_diameter_ft: 54.0,
    },
  },
  {
    id: 'ford-ranger-2019-reference',
    label: 'Ford Ranger 2019+ OEM reference',
    make: 'ford',
    model: 'ranger',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Ranger mid-size truck reference. Verify cab, drivetrain, FX4/Tremor, and placard payload.',
    specs: {
      base_weight_lb: 4450,
      gvwr_lb: 6050,
      payload_capacity_lb: 1600,
      fuel_tank_capacity_gal: 18.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.9,
      wheelbase_in: 126.8,
      overall_width_in: 73.3,
      overall_height_in: 71.5,
      turning_diameter_ft: 42.0,
    },
  },
  {
    id: 'ford-expedition-2018-reference',
    label: 'Ford Expedition 2018+ OEM reference',
    make: 'ford',
    model: 'expedition',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2018,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Expedition full-size SUV values vary by Max body, trim, tow package, and drivetrain. Verify placard.',
    specs: {
      base_weight_lb: 5600,
      gvwr_lb: 7400,
      payload_capacity_lb: 1600,
      fuel_tank_capacity_gal: 23.3,
      fuel_type: 'gas',
      ground_clearance_inches: 9.8,
      wheelbase_in: 122.5,
      overall_width_in: 79.9,
      overall_height_in: 76.6,
      turning_diameter_ft: 41.0,
    },
  },
  {
    id: 'ford-bronco-sport-2021-reference',
    label: 'Ford Bronco Sport 2021+ OEM reference',
    make: 'ford',
    model: 'bronco sport',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2021,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Bronco Sport crossover reference. Badlands and wheel/tire packages change clearance and trail-fit assumptions.',
    specs: {
      base_weight_lb: 3700,
      gvwr_lb: 4630,
      payload_capacity_lb: 900,
      fuel_tank_capacity_gal: 16.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.8,
      wheelbase_in: 105.1,
      overall_width_in: 74.3,
      overall_height_in: 70.2,
      turning_diameter_ft: 37.4,
    },
  },
  {
    id: 'chevrolet-silverado-1500-2019-reference',
    label: 'Chevrolet Silverado 1500 2019+ OEM reference',
    make: 'chevrolet',
    model: 'silverado 1500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'Silverado 1500 specs vary by cab, bed, engine, drivetrain, axle, and payload package. Verify door placard.',
    specs: {
      base_weight_lb: 5300,
      gvwr_lb: 7100,
      payload_capacity_lb: 1800,
      fuel_tank_capacity_gal: 24.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.1,
      wheelbase_in: 147.4,
      overall_width_in: 81.2,
      overall_height_in: 75.5,
      turning_diameter_ft: 46.9,
    },
  },
  {
    id: 'chevrolet-silverado-1500-2010-reference',
    label: 'Chevrolet Silverado 1500 2010-2018 OEM reference',
    make: 'chevrolet',
    model: 'silverado 1500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2010,
    yearEnd: 2018,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'Earlier Silverado 1500 values vary by cab, bed, engine, drivetrain, axle, and payload package. Verify door placard.',
    specs: {
      base_weight_lb: 5300,
      gvwr_lb: 7000,
      payload_capacity_lb: 1700,
      fuel_tank_capacity_gal: 26.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.9,
      wheelbase_in: 143.5,
      overall_width_in: 80.0,
      overall_height_in: 73.8,
      turning_diameter_ft: 47.2,
    },
  },
  {
    id: 'gmc-sierra-1500-2019-reference',
    label: 'GMC Sierra 1500 2019+ OEM reference',
    make: 'gmc',
    model: 'sierra 1500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'Sierra 1500 specs vary by cab, bed, engine, drivetrain, axle, and payload package. Verify door placard.',
    specs: {
      base_weight_lb: 5350,
      gvwr_lb: 7100,
      payload_capacity_lb: 1750,
      fuel_tank_capacity_gal: 24.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.1,
      wheelbase_in: 147.4,
      overall_width_in: 81.2,
      overall_height_in: 75.5,
      turning_diameter_ft: 46.9,
    },
  },
  {
    id: 'gmc-sierra-1500-2010-reference',
    label: 'GMC Sierra 1500 2010-2018 OEM reference',
    make: 'gmc',
    model: 'sierra 1500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2010,
    yearEnd: 2018,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'Earlier Sierra 1500 values vary by cab, bed, engine, drivetrain, axle, and payload package. Verify door placard.',
    specs: {
      base_weight_lb: 5350,
      gvwr_lb: 7000,
      payload_capacity_lb: 1650,
      fuel_tank_capacity_gal: 26.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.9,
      wheelbase_in: 143.5,
      overall_width_in: 80.0,
      overall_height_in: 73.8,
      turning_diameter_ft: 47.2,
    },
  },
  {
    id: 'chevrolet-silverado-2500-2020-reference',
    label: 'Chevrolet Silverado 2500HD 2020+ OEM reference',
    make: 'chevrolet',
    model: 'silverado 2500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2020,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 78,
    notes: 'Silverado HD specs vary materially by cab, bed, engine, axle, and GVWR package. Verify door placard.',
    specs: {
      base_weight_lb: 7600,
      gvwr_lb: 10650,
      payload_capacity_lb: 3000,
      fuel_tank_capacity_gal: 36.0,
      fuel_type: 'diesel',
      ground_clearance_inches: 10.1,
      wheelbase_in: 159.0,
      overall_width_in: 81.9,
      overall_height_in: 79.8,
      turning_diameter_ft: 52.7,
    },
  },
  {
    id: 'chevrolet-colorado-2015-reference',
    label: 'Chevrolet Colorado 2015-2022 OEM reference',
    make: 'chevrolet',
    model: 'colorado',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2015,
    yearEnd: 2022,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Colorado mid-size truck reference. Verify cab, bed, ZR2, diesel, and placard payload.',
    specs: {
      base_weight_lb: 4500,
      gvwr_lb: 6000,
      payload_capacity_lb: 1450,
      fuel_tank_capacity_gal: 21.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.3,
      wheelbase_in: 128.3,
      overall_width_in: 74.3,
      overall_height_in: 70.6,
      turning_diameter_ft: 41.3,
    },
  },
  {
    id: 'chevrolet-colorado-2023-reference',
    label: 'Chevrolet Colorado 2023+ OEM reference',
    make: 'chevrolet',
    model: 'colorado',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2023,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Modern Colorado reference. Trail Boss/Z71/ZR2, tire package, and payload package change exact values.',
    specs: {
      base_weight_lb: 4850,
      gvwr_lb: 6250,
      payload_capacity_lb: 1400,
      fuel_tank_capacity_gal: 21.4,
      fuel_type: 'gas',
      ground_clearance_inches: 9.5,
      wheelbase_in: 131.4,
      overall_width_in: 74.9,
      overall_height_in: 79.8,
      turning_diameter_ft: 42.3,
    },
  },
  {
    id: 'chevrolet-tahoe-2021-reference',
    label: 'Chevrolet Tahoe 2021+ OEM reference',
    make: 'chevrolet',
    model: 'tahoe',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2021,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Tahoe full-size SUV reference. Z71, diesel, wheel/tire, and tow package affect clearance and payload.',
    specs: {
      base_weight_lb: 5650,
      gvwr_lb: 7500,
      payload_capacity_lb: 1700,
      fuel_tank_capacity_gal: 24.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.0,
      wheelbase_in: 120.9,
      overall_width_in: 81.0,
      overall_height_in: 75.9,
      turning_diameter_ft: 39.7,
    },
  },
  {
    id: 'chevrolet-tahoe-2010-reference',
    label: 'Chevrolet Tahoe 2010-2020 OEM reference',
    make: 'chevrolet',
    model: 'tahoe',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: 2020,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Earlier Tahoe full-size SUV values vary by Z71, drivetrain, wheel/tire, and tow package. Verify placard.',
    specs: {
      base_weight_lb: 5600,
      gvwr_lb: 7300,
      payload_capacity_lb: 1600,
      fuel_tank_capacity_gal: 26.0,
      fuel_type: 'gas',
      ground_clearance_inches: 7.9,
      wheelbase_in: 116.0,
      overall_width_in: 80.5,
      overall_height_in: 74.4,
      turning_diameter_ft: 39.0,
    },
  },
  {
    id: 'gmc-yukon-2021-reference',
    label: 'GMC Yukon 2021+ OEM reference',
    make: 'gmc',
    model: 'yukon',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2021,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Yukon full-size SUV reference. AT4, diesel, wheel/tire, and tow package affect clearance and payload.',
    specs: {
      base_weight_lb: 5700,
      gvwr_lb: 7500,
      payload_capacity_lb: 1650,
      fuel_tank_capacity_gal: 24.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.0,
      wheelbase_in: 120.9,
      overall_width_in: 81.0,
      overall_height_in: 76.5,
      turning_diameter_ft: 39.7,
    },
  },
  {
    id: 'gmc-yukon-2010-reference',
    label: 'GMC Yukon 2010-2020 OEM reference',
    make: 'gmc',
    model: 'yukon',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: 2020,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Earlier Yukon full-size SUV values vary by trim, drivetrain, wheel/tire, and tow package. Verify placard.',
    specs: {
      base_weight_lb: 5650,
      gvwr_lb: 7300,
      payload_capacity_lb: 1550,
      fuel_tank_capacity_gal: 26.0,
      fuel_type: 'gas',
      ground_clearance_inches: 7.9,
      wheelbase_in: 116.0,
      overall_width_in: 80.5,
      overall_height_in: 74.4,
      turning_diameter_ft: 39.0,
    },
  },
  {
    id: 'ram-1500-2019-reference',
    label: 'RAM 1500 2019+ OEM reference',
    make: 'ram',
    model: '1500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'RAM 1500 values vary by cab, bed, engine, axle, air suspension, and payload package. Verify door placard.',
    specs: {
      base_weight_lb: 5500,
      gvwr_lb: 7100,
      payload_capacity_lb: 1600,
      fuel_tank_capacity_gal: 26.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.7,
      wheelbase_in: 144.5,
      overall_width_in: 82.1,
      overall_height_in: 77.6,
      turning_diameter_ft: 46.2,
    },
  },
  {
    id: 'ram-1500-2010-reference',
    label: 'RAM 1500 2010-2018 OEM reference',
    make: 'ram',
    model: '1500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2010,
    yearEnd: 2018,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'Earlier RAM 1500 values vary by cab, bed, engine, axle, air suspension, and payload package. Verify door placard.',
    specs: {
      base_weight_lb: 5400,
      gvwr_lb: 6900,
      payload_capacity_lb: 1500,
      fuel_tank_capacity_gal: 26.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.6,
      wheelbase_in: 140.5,
      overall_width_in: 79.4,
      overall_height_in: 77.5,
      turning_diameter_ft: 45.1,
    },
  },
  {
    id: 'ram-2500-2010-reference',
    label: 'RAM 2500 2010-2018 OEM reference',
    make: 'ram',
    model: '2500',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2010,
    yearEnd: 2018,
    source: 'ecs_oem_reference',
    confidence: 78,
    notes: 'Earlier RAM 2500 HD values vary by engine, cab, bed, axle, and GVWR package. Verify door placard.',
    specs: {
      base_weight_lb: 7300,
      gvwr_lb: 10000,
      payload_capacity_lb: 2600,
      fuel_tank_capacity_gal: 31.0,
      fuel_type: 'diesel',
      ground_clearance_inches: 8.1,
      wheelbase_in: 149.0,
      overall_width_in: 79.4,
      overall_height_in: 78.9,
      turning_diameter_ft: 49.2,
    },
  },
  {
    id: 'ram-promaster-2014-reference',
    label: 'RAM ProMaster 2014+ OEM reference',
    make: 'ram',
    model: 'promaster',
    trim: null,
    vehicleType: 'van',
    yearStart: 2014,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 80,
    notes: 'ProMaster van values vary by roof, wheelbase, length, and GVWR. Verify conversion weight and placard.',
    specs: {
      base_weight_lb: 5250,
      gvwr_lb: 8550,
      payload_capacity_lb: 3200,
      fuel_tank_capacity_gal: 24.0,
      fuel_type: 'gas',
      ground_clearance_inches: 6.9,
      wheelbase_in: 159.0,
      overall_width_in: 80.3,
      overall_height_in: 101.0,
      turning_diameter_ft: 46.8,
    },
  },
  {
    id: 'nissan-frontier-2010-reference',
    label: 'Nissan Frontier 2010-2021 OEM reference',
    make: 'nissan',
    model: 'frontier',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2010,
    yearEnd: 2021,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Frontier reference range. Verify cab, bed, Pro-4X, drivetrain, and payload placard.',
    specs: {
      base_weight_lb: 4400,
      gvwr_lb: 5815,
      payload_capacity_lb: 1300,
      fuel_tank_capacity_gal: 21.1,
      fuel_type: 'gas',
      ground_clearance_inches: 8.9,
      wheelbase_in: 125.9,
      overall_width_in: 72.8,
      overall_height_in: 70.1,
      turning_diameter_ft: 43.4,
    },
  },
  {
    id: 'nissan-frontier-2022-reference',
    label: 'Nissan Frontier 2022+ OEM reference',
    make: 'nissan',
    model: 'frontier',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2022,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Modern Frontier reference. Verify cab, bed, Pro-4X, drivetrain, and payload placard.',
    specs: {
      base_weight_lb: 4700,
      gvwr_lb: 6012,
      payload_capacity_lb: 1300,
      fuel_tank_capacity_gal: 21.1,
      fuel_type: 'gas',
      ground_clearance_inches: 8.9,
      wheelbase_in: 126.0,
      overall_width_in: 73.0,
      overall_height_in: 72.9,
      turning_diameter_ft: 43.3,
    },
  },
  {
    id: 'nissan-xterra-2010-reference',
    label: 'Nissan Xterra 2010-2015 OEM reference',
    make: 'nissan',
    model: 'xterra',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2010,
    yearEnd: 2015,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Xterra reference range. Verify Pro-4X, drivetrain, tire package, and payload placard.',
    specs: {
      base_weight_lb: 4400,
      gvwr_lb: 5400,
      payload_capacity_lb: 1000,
      fuel_tank_capacity_gal: 21.1,
      fuel_type: 'gas',
      ground_clearance_inches: 9.5,
      wheelbase_in: 106.3,
      overall_width_in: 72.8,
      overall_height_in: 74.9,
      turning_diameter_ft: 37.3,
    },
  },
  {
    id: 'nissan-armada-2017-reference',
    label: 'Nissan Armada 2017+ OEM reference',
    make: 'nissan',
    model: 'armada',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2017,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Armada full-size SUV reference. Verify drivetrain, trim, seating, and payload placard.',
    specs: {
      base_weight_lb: 5900,
      gvwr_lb: 7500,
      payload_capacity_lb: 1550,
      fuel_tank_capacity_gal: 26.0,
      fuel_type: 'gas',
      ground_clearance_inches: 9.1,
      wheelbase_in: 121.1,
      overall_width_in: 79.9,
      overall_height_in: 75.8,
      turning_diameter_ft: 41.3,
    },
  },
  {
    id: 'honda-ridgeline-2017-reference',
    label: 'Honda Ridgeline 2017+ OEM reference',
    make: 'honda',
    model: 'ridgeline',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2017,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Ridgeline unibody truck reference. Verify trim, AWD package, tire package, and payload placard.',
    specs: {
      base_weight_lb: 4500,
      gvwr_lb: 6019,
      payload_capacity_lb: 1500,
      fuel_tank_capacity_gal: 19.5,
      fuel_type: 'gas',
      ground_clearance_inches: 7.6,
      wheelbase_in: 125.2,
      overall_width_in: 78.6,
      overall_height_in: 70.8,
      turning_diameter_ft: 43.4,
    },
  },
  {
    id: 'honda-passport-2019-reference',
    label: 'Honda Passport 2019+ OEM reference',
    make: 'honda',
    model: 'passport',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Passport SUV reference. TrailSport, tire package, and AWD/2WD values differ; verify placard.',
    specs: {
      base_weight_lb: 4200,
      gvwr_lb: 5500,
      payload_capacity_lb: 1250,
      fuel_tank_capacity_gal: 19.5,
      fuel_type: 'gas',
      ground_clearance_inches: 8.1,
      wheelbase_in: 110.9,
      overall_width_in: 78.6,
      overall_height_in: 72.2,
      turning_diameter_ft: 39.5,
    },
  },
  {
    id: 'honda-pilot-2023-reference',
    label: 'Honda Pilot 2023+ OEM reference',
    make: 'honda',
    model: 'pilot',
    trim: null,
    vehicleType: 'suv',
    yearStart: 2023,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Modern Pilot SUV reference. TrailSport, drivetrain, and seating packages vary; verify placard.',
    specs: {
      base_weight_lb: 4700,
      gvwr_lb: 6173,
      payload_capacity_lb: 1400,
      fuel_tank_capacity_gal: 18.5,
      fuel_type: 'gas',
      ground_clearance_inches: 8.3,
      wheelbase_in: 113.8,
      overall_width_in: 78.5,
      overall_height_in: 72.0,
      turning_diameter_ft: 40.8,
    },
  },
  {
    id: 'subaru-forester-2019-reference',
    label: 'Subaru Forester 2019+ OEM reference',
    make: 'subaru',
    model: 'forester',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2019,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Forester crossover reference. Wilderness trim changes clearance, tires, and trail-fit assumptions.',
    specs: {
      base_weight_lb: 3600,
      gvwr_lb: 4891,
      payload_capacity_lb: 1200,
      fuel_tank_capacity_gal: 16.6,
      fuel_type: 'gas',
      ground_clearance_inches: 8.7,
      wheelbase_in: 105.1,
      overall_width_in: 71.5,
      overall_height_in: 68.1,
      turning_diameter_ft: 35.4,
    },
  },
  {
    id: 'subaru-crosstrek-2018-reference',
    label: 'Subaru Crosstrek 2018+ OEM reference',
    make: 'subaru',
    model: 'crosstrek',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2018,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 84,
    notes: 'Crosstrek crossover reference. Wilderness and hybrid trims vary; verify placard and tire package.',
    specs: {
      base_weight_lb: 3300,
      gvwr_lb: 4376,
      payload_capacity_lb: 1000,
      fuel_tank_capacity_gal: 16.6,
      fuel_type: 'gas',
      ground_clearance_inches: 8.7,
      wheelbase_in: 104.9,
      overall_width_in: 71.0,
      overall_height_in: 63.6,
      turning_diameter_ft: 35.4,
    },
  },
  {
    id: 'kia-telluride-2020-reference',
    label: 'Kia Telluride 2020+ OEM reference',
    make: 'kia',
    model: 'telluride',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2020,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Telluride three-row crossover reference. X-Pro/X-Line, AWD, and tire packages vary; verify placard.',
    specs: {
      base_weight_lb: 4500,
      gvwr_lb: 5917,
      payload_capacity_lb: 1400,
      fuel_tank_capacity_gal: 18.8,
      fuel_type: 'gas',
      ground_clearance_inches: 8.0,
      wheelbase_in: 114.2,
      overall_width_in: 78.3,
      overall_height_in: 69.3,
      turning_diameter_ft: 38.8,
    },
  },
  {
    id: 'hyundai-palisade-2020-reference',
    label: 'Hyundai Palisade 2020+ OEM reference',
    make: 'hyundai',
    model: 'palisade',
    trim: null,
    vehicleType: 'crossover',
    yearStart: 2020,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Palisade three-row crossover reference. AWD, XRT, tire package, and seating trim vary; verify placard.',
    specs: {
      base_weight_lb: 4500,
      gvwr_lb: 5871,
      payload_capacity_lb: 1350,
      fuel_tank_capacity_gal: 18.8,
      fuel_type: 'gas',
      ground_clearance_inches: 7.9,
      wheelbase_in: 114.2,
      overall_width_in: 77.8,
      overall_height_in: 68.9,
      turning_diameter_ft: 38.7,
    },
  },
  {
    id: 'hyundai-santa-cruz-2022-reference',
    label: 'Hyundai Santa Cruz 2022+ OEM reference',
    make: 'hyundai',
    model: 'santa cruz',
    trim: null,
    vehicleType: 'truck',
    yearStart: 2022,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 82,
    notes: 'Santa Cruz compact unibody truck reference. Turbo, AWD, and trim packages vary; verify placard.',
    specs: {
      base_weight_lb: 4100,
      gvwr_lb: 5732,
      payload_capacity_lb: 1600,
      fuel_tank_capacity_gal: 17.7,
      fuel_type: 'gas',
      ground_clearance_inches: 8.6,
      wheelbase_in: 118.3,
      overall_width_in: 75.0,
      overall_height_in: 66.7,
      turning_diameter_ft: 39.6,
    },
  },
  {
    id: 'chevrolet-express-2010-reference',
    label: 'Chevrolet Express 2010+ OEM reference',
    make: 'chevrolet',
    model: 'express',
    trim: null,
    vehicleType: 'van',
    yearStart: 2010,
    yearEnd: currentModelYear,
    source: 'ecs_oem_reference',
    confidence: 78,
    notes: 'Express van values vary by 2500/3500, passenger/cargo, wheelbase, engine, and conversion weight. Verify placard.',
    specs: {
      base_weight_lb: 6100,
      gvwr_lb: 9600,
      payload_capacity_lb: 3300,
      fuel_tank_capacity_gal: 31.0,
      fuel_type: 'gas',
      ground_clearance_inches: 7.7,
      wheelbase_in: 135.2,
      overall_width_in: 79.2,
      overall_height_in: 84.6,
      turning_diameter_ft: 49.2,
    },
  },
  {
    id: 'nissan-nv-2012-reference',
    label: 'Nissan NV 2012-2021 OEM reference',
    make: 'nissan',
    model: 'nv',
    trim: null,
    vehicleType: 'van',
    yearStart: 2012,
    yearEnd: 2021,
    source: 'ecs_oem_reference',
    confidence: 78,
    notes: 'Nissan NV values vary by NV1500/2500/3500, roof height, passenger/cargo body, and conversion weight. Verify placard.',
    specs: {
      base_weight_lb: 6200,
      gvwr_lb: 9100,
      payload_capacity_lb: 2900,
      fuel_tank_capacity_gal: 28.0,
      fuel_type: 'gas',
      ground_clearance_inches: 8.1,
      wheelbase_in: 146.1,
      overall_width_in: 79.9,
      overall_height_in: 84.0,
      turning_diameter_ft: 45.2,
    },
  },
];

let referenceIndexByMake: Map<string, readonly FleetOemVehicleSpecReference[]> | null = null;

function getReferenceIndexByMake(): Map<string, readonly FleetOemVehicleSpecReference[]> {
  if (referenceIndexByMake) return referenceIndexByMake;
  const index = new Map<string, FleetOemVehicleSpecReference[]>();
  for (const reference of FLEET_OEM_SPEC_REFERENCES) {
    const make = normalizeVehicleText(reference.make);
    const existing = index.get(make) ?? [];
    existing.push(reference);
    index.set(make, existing);
  }
  referenceIndexByMake = index;
  return referenceIndexByMake;
}

export function getFleetOemSpecReferenceCatalogStats(): {
  referenceCount: number;
  makeCount: number;
  vehicleTypes: string[];
  earliestYearStart: number;
  latestYearEnd: number;
} {
  const years = FLEET_OEM_SPEC_REFERENCES.flatMap((reference) => [reference.yearStart, reference.yearEnd ?? currentModelYear]);
  return {
    referenceCount: FLEET_OEM_SPEC_REFERENCES.length,
    makeCount: new Set(FLEET_OEM_SPEC_REFERENCES.map((reference) => normalizeVehicleText(reference.make))).size,
    vehicleTypes: Array.from(new Set(FLEET_OEM_SPEC_REFERENCES.map((reference) => normalizeVehicleText(reference.vehicleType)))).sort(),
    earliestYearStart: Math.min(...years),
    latestYearEnd: Math.max(...years),
  };
}

export function resolveFleetOemSpecReference(input: {
  year?: number | null;
  make?: string | null;
  model?: string | null;
  trim?: string | null;
  vehicleType?: string | null;
}): FleetOemSpecMatch {
  const make = normalizeVehicleText(input.make);
  const model = normalizeVehicleText(input.model);
  const trim = normalizeVehicleText(input.trim);
  const vehicleType = normalizeVehicleText(input.vehicleType);
  const year = typeof input.year === 'number' && Number.isFinite(input.year) ? input.year : null;
  if (!make || !model) {
    return {
      status: 'incomplete',
      reference: null,
      message: 'Enter year, make, and model for ECS to search OEM reference specs.',
    };
  }

  const search = normalizeVehicleText([input.make, input.model, input.trim, input.vehicleType].filter(Boolean).join(' '));
  const indexedReferences = getReferenceIndexByMake().get(make) ?? FLEET_OEM_SPEC_REFERENCES;
  const candidates = indexedReferences
    .filter((reference) => makeMatches(make, reference.make))
    .filter((reference) => modelMatches(model, reference.model, search));

  if (candidates.length === 0) {
    return {
      status: 'not_found',
      reference: null,
      message: 'No OEM reference is bundled for this vehicle yet. ECS will use class/model estimates until specs are confirmed.',
    };
  }

  const inYear = candidates.filter((reference) => yearInRange(year, reference));
  if (inYear.length === 0) {
    const range = candidates
      .map((reference) => `${reference.yearStart}${reference.yearEnd ? `-${reference.yearEnd}` : '+'}`)
      .join(', ');
    return {
      status: 'unsupported_year',
      reference: null,
      message: `This model/year combination is outside the bundled OEM reference window (${range}). Verify the year or enter specs manually.`,
    };
  }

  const scored = inYear
    .map((reference) => {
      let score = 10;
      const referenceModel = normalizeVehicleText(reference.model);
      if (model === referenceModel) score += 12;
      else if (model.includes(referenceModel)) score += Math.min(8, referenceModel.length);
      if (reference.trim && trim && trim.includes(normalizeVehicleText(reference.trim))) score += 8;
      if (reference.vehicleType && vehicleType && vehicleType.includes(normalizeVehicleText(reference.vehicleType))) score += 3;
      return { reference, score };
    })
    .sort((a, b) => b.score - a.score);

  const reference = scored[0]?.reference;
  if (!reference) {
    return {
      status: 'not_found',
      reference: null,
      message: 'No OEM reference is bundled for this vehicle yet. ECS will use class/model estimates until specs are confirmed.',
    };
  }

  return {
    status: 'matched',
    reference,
    message: `${reference.label} matched. Specs are OEM-reference estimates and should be verified against trim/package and door placard before final payload decisions.`,
  };
}
