import {
  getBadgeDefinition,
} from './expeditionBadgeRegistry';
import type {
  ExpeditionBadgeCategory,
} from './expeditionTripRecordTypes';

export type BadgeIdentitySignalStatus = 'existing_badge_path' | 'safe_future_signal' | 'deferred_until_verified';

export type BadgeIdentitySignal = {
  id: string;
  label: string;
  status: BadgeIdentitySignalStatus;
  reason: string;
};

export type BadgeIdentityCategoryRecommendation = {
  id: string;
  label: string;
  mapsToExistingCategories: ExpeditionBadgeCategory[];
  note: string;
};

export type BadgeIdentityTitle =
  | 'Trail Scout'
  | 'Route Analyst'
  | 'Field Planner'
  | 'Terrain Watch'
  | 'Basecamp Ready'
  | 'Expedition Lead'
  | 'Recovery Minded'
  | 'Field Commander';

export type BadgeIdentityTitleTier = {
  title: BadgeIdentityTitle;
  priority: number;
  description: string;
  derivedFrom: string[];
};

export type BadgeIdentityTitleInput = {
  earnedBadgeIds?: string[] | null;
  earnedBadgeCount?: number | null;
  categoryCounts?: Partial<Record<ExpeditionBadgeCategory, number>> | null;
};

export type BadgeIdentityTitleResult = {
  title: BadgeIdentityTitle;
  description: string;
  basis: string;
  earnedBadgeCount: number;
  isCredential: false;
};

export type BadgeIdentityProfileBadgeInput = {
  id?: string | null;
  title?: string | null;
  category?: ExpeditionBadgeCategory | null;
  unlockedAt?: string | null;
  sourceQuality?: string | null;
  dataQuality?: string | null;
  sourceLabel?: string | null;
  isDemo?: boolean | null;
  isMock?: boolean | null;
};

export type BadgeIdentityProfileModel = {
  title: BadgeIdentityTitle;
  titleDescription: string;
  titleBasis: string;
  earnedBadgeCount: number;
  earnedBadgeIds: string[];
  hasEarnedState: boolean;
  excludedBadgeCount: number;
  visibleEarnedBadges: Array<{
    id: string;
    title: string;
    category: ExpeditionBadgeCategory;
    unlockedAt: string;
  }>;
};

export const BADGE_IDENTITY_SOURCE_OF_TRUTH = {
  definitionRegistry: 'lib/expedition/expeditionBadgeRegistry.ts',
  earnedStateStore: 'lib/expedition/expeditionBadgeStore.ts',
  tripRecordStore: 'lib/expedition/expeditionTripRecordStore.ts',
  unlockEvaluator: 'evaluateBadgesForCompletedTrip',
  displaySurfaces: [
    'Dashboard Expedition Hub',
    'Completed trip detail',
    'Unlocked Badges collection',
    'Future Expedition/Profile identity surface',
    'Future trip completion summary',
  ],
  surfacesToAvoid: [
    'Offline Incident Packet',
    'Emergency/alert surfaces',
    'Provider connection panels',
  ],
  notes: [
    'Badge definitions are deterministic registry records.',
    'Earned state is persisted separately from Fleet, Active Trip, Offline Incident Packet, and provider state.',
    'Hidden locked badges stay hidden until earned.',
    'Demo, mock, stale, or unavailable data can inform caution copy but must not unlock trusted live accomplishments.',
  ],
} as const;

export const BADGE_IDENTITY_SAFE_SIGNALS: BadgeIdentitySignal[] = [
  {
    id: 'vehicle_profile_completed',
    label: 'Vehicle profile completed',
    status: 'safe_future_signal',
    reason: 'Can be derived from saved Fleet profile completeness without claiming hardware verification.',
  },
  {
    id: 'trip_confidence_summary_generated',
    label: 'Trip Confidence Summary generated',
    status: 'safe_future_signal',
    reason: 'Generated by the deterministic Route Confidence Engine and visible to the user.',
  },
  {
    id: 'active_trip_activated',
    label: 'Active Trip activated',
    status: 'safe_future_signal',
    reason: 'Derived from the local Active Trip snapshot lifecycle.',
  },
  {
    id: 'offline_incident_packet_created',
    label: 'Offline Incident Packet created',
    status: 'safe_future_signal',
    reason: 'Derived from local-only packet creation without implying sharing, SOS, or external dispatch.',
  },
  {
    id: 'active_trip_resumed_after_restart',
    label: 'Active Trip resumed after restart',
    status: 'safe_future_signal',
    reason: 'Derived from recovered local state and must retain recovered/stale copy.',
  },
  {
    id: 'terrain_risk_evaluated',
    label: 'Terrain Risk evaluated',
    status: 'existing_badge_path',
    reason: 'Existing completed-trip records can unlock terrain badges from recorded terrain risk events.',
  },
  {
    id: 'camp_viability_evaluated',
    label: 'Camp Viability evaluated',
    status: 'safe_future_signal',
    reason: 'Derived from deterministic Camp Viability output without asserting legal approval.',
  },
  {
    id: 'route_authority_recognized',
    label: 'Route authority recognized',
    status: 'safe_future_signal',
    reason: 'Can use existing route authority metadata when it is source-backed and visible.',
  },
  {
    id: 'clean_trip_stopped_or_completed',
    label: 'Clean trip stopped or completed',
    status: 'existing_badge_path',
    reason: 'Existing completed-trip evaluation already supports clean completion badges.',
  },
  {
    id: 'local_only_packet_viewed',
    label: 'Local-only packet viewed',
    status: 'safe_future_signal',
    reason: 'A local view action is safe if it never implies delivery, sync, or emergency response.',
  },
  {
    id: 'unavailable_state_handled',
    label: 'Unavailable state handled',
    status: 'safe_future_signal',
    reason: 'Can reward honest unavailable-state handling only when copy remains explicit.',
  },
];

export const BADGE_IDENTITY_DEFERRED_SIGNALS: BadgeIdentitySignal[] = [
  {
    id: 'unverified_ble_telemetry_live',
    label: 'Unverified BLE live data',
    status: 'deferred_until_verified',
    reason: 'Hardware data must be device-verified before it can unlock trusted accomplishments.',
  },
  {
    id: 'unverified_ecoflow_live',
    label: 'Unverified power-vendor live data',
    status: 'deferred_until_verified',
    reason: 'Partial vendor integrations cannot imply verified live power achievements.',
  },
  {
    id: 'unverified_mopeka_live',
    label: 'Unverified utility-sensor live data',
    status: 'deferred_until_verified',
    reason: 'Tank sensor paths need field-device verification before identity rewards.',
  },
  {
    id: 'convoy_role_or_presence',
    label: 'Convoy role or presence',
    status: 'deferred_until_verified',
    reason: 'Convoy identity display is not the same as completed-expedition identity.',
  },
  {
    id: 'community_route_published',
    label: 'Community route published',
    status: 'deferred_until_verified',
    reason: 'Publishing and public identity require privacy and moderation review.',
  },
  {
    id: 'cloud_shared_packet',
    label: 'Cloud shared packet',
    status: 'deferred_until_verified',
    reason: 'Offline Incident Packet is currently local-only and must not imply sharing.',
  },
  {
    id: 'mock_or_demo_fixture',
    label: 'Mock or demo fixture',
    status: 'deferred_until_verified',
    reason: 'Fixtures are useful for QA but cannot unlock production achievements.',
  },
  {
    id: 'hardware_connection_detected',
    label: 'Hardware connection detected',
    status: 'deferred_until_verified',
    reason: 'Connection presence alone does not prove reliable live data.',
  },
];

export const BADGE_IDENTITY_CATEGORIES: BadgeIdentityCategoryRecommendation[] = [
  {
    id: 'firsts',
    label: 'Firsts',
    mapsToExistingCategories: ['firsts'],
    note: 'Keep onboarding accomplishments compact and visible only after earned.',
  },
  {
    id: 'route_readiness',
    label: 'Route Readiness',
    mapsToExistingCategories: ['route_behavior', 'distance', 'exploration'],
    note: 'Use source-backed route authority, geometry, and completed-trip behavior.',
  },
  {
    id: 'vehicle_readiness',
    label: 'Vehicle Readiness',
    mapsToExistingCategories: ['expedition_history'],
    note: 'Future-only until Fleet completion signals are wired without mutating Fleet state.',
  },
  {
    id: 'field_planning',
    label: 'Field Planning',
    mapsToExistingCategories: ['exploration', 'notable_moments'],
    note: 'Trip Confidence, packet creation, resupply, and route planning belong here when implemented.',
  },
  {
    id: 'terrain_awareness',
    label: 'Terrain Awareness',
    mapsToExistingCategories: ['terrain', 'personal_records'],
    note: 'Terrain Risk can support conservative identity only when terrain state remains honest.',
  },
  {
    id: 'camp_readiness',
    label: 'Camp Readiness',
    mapsToExistingCategories: ['exploration'],
    note: 'Camp Viability can support identity without making legal, permitted, or safe claims.',
  },
  {
    id: 'recovery_readiness',
    label: 'Recovery Readiness',
    mapsToExistingCategories: ['recovery'],
    note: 'Recovery identity comes from saved expedition usage, not emergency authority.',
  },
  {
    id: 'expedition_history',
    label: 'Expedition History',
    mapsToExistingCategories: ['expedition_history', 'consistency'],
    note: 'Use completed local trip history and existing badge persistence.',
  },
  {
    id: 'hidden',
    label: 'Hidden',
    mapsToExistingCategories: ['hidden'],
    note: 'Hidden badges stay hidden until earned and must not expose locked catalog entries.',
  },
];

export const BADGE_IDENTITY_TITLE_TIERS: BadgeIdentityTitleTier[] = [
  {
    title: 'Trail Scout',
    priority: 10,
    description: 'Default expedition identity for a user with no earned badge state yet.',
    derivedFrom: ['missing state', 'no earned badges'],
  },
  {
    title: 'Field Planner',
    priority: 20,
    description: 'Planning-oriented identity derived from route preparation and logistics badges.',
    derivedFrom: ['trailhead-ready', 'resupply-scout', 'new-trailhead', 'early-start'],
  },
  {
    title: 'Route Analyst',
    priority: 30,
    description: 'Route-oriented identity derived from route behavior or distance badges.',
    derivedFrom: ['route_behavior', 'distance'],
  },
  {
    title: 'Terrain Watch',
    priority: 40,
    description: 'Terrain-aware identity derived from earned terrain or terrain risk badges.',
    derivedFrom: ['terrain', 'terrain-watch', 'terrain-risk-moment'],
  },
  {
    title: 'Basecamp Ready',
    priority: 50,
    description: 'Camp planning identity derived from camp or resupply planning badges.',
    derivedFrom: ['camp-scout'],
  },
  {
    title: 'Recovery Minded',
    priority: 60,
    description: 'Recovery-aware identity derived from recovery planning or recovery usage badges.',
    derivedFrom: ['recovery'],
  },
  {
    title: 'Expedition Lead',
    priority: 70,
    description: 'Experience identity derived from completed expedition history thresholds.',
    derivedFrom: ['expedition_history', 'consistency', 'five or more earned badges'],
  },
  {
    title: 'Field Commander',
    priority: 80,
    description: 'High-history product title for broad earned badge depth; it is a personal ECS label.',
    derivedFrom: ['twenty-five or more earned badges'],
  },
];

export const BADGE_IDENTITY_UI_SURFACES = [
  {
    id: 'dashboard_expedition_hub',
    label: 'Dashboard Expedition Hub',
    status: 'safe_now',
    note: 'Current badge collection and earned-badge surfaces live here.',
  },
  {
    id: 'completed_trip_detail',
    label: 'Completed trip detail',
    status: 'safe_now',
    note: 'Existing trip detail shows badges earned on that completed expedition.',
  },
  {
    id: 'trip_completion_summary',
    label: 'Future trip completion summary',
    status: 'safe_later',
    note: 'Safe after the completion summary has deterministic trip records and no live-provider dependency.',
  },
  {
    id: 'active_trip_summary',
    label: 'Active Trip summary',
    status: 'use_sparingly',
    note: 'Can show a compact title later, but should not distract from live trip state.',
  },
  {
    id: 'offline_incident_packet',
    label: 'Offline Incident Packet',
    status: 'avoid_badge_noise',
    note: 'Keep local-only recovery data clear, stale-labeled, and free of gamified clutter.',
  },
  {
    id: 'convoy_command',
    label: 'Convoy Command',
    status: 'defer_until_convoy_qa',
    note: 'Convoy may show optional title snapshots later, after privacy and device QA.',
  },
] as const;

export const BADGE_IDENTITY_PRODUCTION_GUARDS = {
  demoMockNeverUnlocks: true,
  hiddenLockedBadgesStayHidden: true,
  deterministicUnlocksOnly: true,
  missingStateNoCrash: true,
  identityPersistenceSeparate: true,
  titlesDoNotImplyCredentials: true,
} as const;

const FIELD_PLANNER_BADGES = new Set([
  'trailhead-ready',
  'resupply-scout',
  'new-trailhead',
  'early-start',
]);

const CAMPSITE_BADGES = new Set([
  'camp-scout',
]);

const TERRAIN_BADGES = new Set([
  'terrain-watch',
  'terrain-risk-moment',
  'toughest-terrain-yet',
]);

const HISTORY_BADGES = new Set([
  'trail-veteran',
  'five-trips-logged',
  'ten-trips-logged',
  'seasoned-operator',
  'expedition-habit',
]);

function safeSignalIds(): Set<string> {
  return new Set(BADGE_IDENTITY_SAFE_SIGNALS.map((signal) => signal.id));
}

function deferredSignalIds(): Set<string> {
  return new Set(BADGE_IDENTITY_DEFERRED_SIGNALS.map((signal) => signal.id));
}

function cleanBadgeIds(input: BadgeIdentityTitleInput | undefined): string[] {
  const values = input?.earnedBadgeIds;
  if (!Array.isArray(values)) return [];
  return Array.from(new Set(values.filter((value): value is string => typeof value === 'string' && value.trim().length > 0)));
}

function cleanText(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function isMockOrDemoBadge(input: BadgeIdentityProfileBadgeInput): boolean {
  if (input.isDemo || input.isMock) return true;
  const sourceText = [
    input.sourceQuality,
    input.dataQuality,
    input.sourceLabel,
  ]
    .map((value) => cleanText(value)?.toLowerCase() ?? '')
    .join(' ');
  return /(^|[^a-z0-9])(mock|demo|fixture|test-only|dev-only)([^a-z0-9]|$)/.test(sourceText);
}

function normalizeProfileBadge(input: BadgeIdentityProfileBadgeInput): BadgeIdentityProfileModel['visibleEarnedBadges'][number] | null {
  const id = cleanText(input.id);
  const unlockedAt = cleanText(input.unlockedAt);
  if (!id || !unlockedAt || isMockOrDemoBadge(input)) return null;
  const definition = getBadgeDefinition(id);
  return {
    id,
    title: cleanText(input.title) ?? definition?.title ?? 'Expedition Badge',
    category: input.category ?? definition?.category ?? 'exploration',
    unlockedAt,
  };
}

function buildCategoryCounts(input: BadgeIdentityTitleInput | undefined, badgeIds: string[]): Partial<Record<ExpeditionBadgeCategory, number>> {
  const counts: Partial<Record<ExpeditionBadgeCategory, number>> = {
    ...(input?.categoryCounts ?? {}),
  };
  for (const badgeId of badgeIds) {
    const definition = getBadgeDefinition(badgeId);
    if (!definition) continue;
    counts[definition.category] = (counts[definition.category] ?? 0) + 1;
  }
  return counts;
}

function hasAnyBadge(badgeIds: Set<string>, candidates: Set<string>): boolean {
  for (const candidate of candidates) {
    if (badgeIds.has(candidate)) return true;
  }
  return false;
}

function categoryCount(counts: Partial<Record<ExpeditionBadgeCategory, number>>, categories: ExpeditionBadgeCategory[]): number {
  return categories.reduce((sum, category) => sum + (counts[category] ?? 0), 0);
}

function titleTier(title: BadgeIdentityTitle): BadgeIdentityTitleTier {
  return BADGE_IDENTITY_TITLE_TIERS.find((tier) => tier.title === title) ?? BADGE_IDENTITY_TITLE_TIERS[0];
}

function titleResult(title: BadgeIdentityTitle, basis: string, earnedBadgeCount: number): BadgeIdentityTitleResult {
  const tier = titleTier(title);
  return {
    title: tier.title,
    description: tier.description,
    basis,
    earnedBadgeCount,
    isCredential: false,
  };
}

export function isBadgeIdentitySignalSafe(signalId: string): boolean {
  return safeSignalIds().has(signalId);
}

export function isBadgeIdentitySignalDeferred(signalId: string): boolean {
  return deferredSignalIds().has(signalId);
}

export function deriveExpeditionIdentityTitle(input: BadgeIdentityTitleInput = {}): BadgeIdentityTitleResult {
  const badgeIds = cleanBadgeIds(input);
  const badgeIdSet = new Set(badgeIds);
  const earnedBadgeCount = Math.max(0, Math.floor(Number(input.earnedBadgeCount ?? badgeIds.length) || 0));
  const categoryCounts = buildCategoryCounts(input, badgeIds);

  if (earnedBadgeCount >= 25) {
    return titleResult('Field Commander', 'Twenty-five or more earned badges.', earnedBadgeCount);
  }

  if (
    earnedBadgeCount >= 10 ||
    hasAnyBadge(badgeIdSet, HISTORY_BADGES) ||
    categoryCount(categoryCounts, ['expedition_history', 'consistency']) >= 2
  ) {
    return titleResult('Expedition Lead', 'Completed expedition history badges.', earnedBadgeCount);
  }

  if (categoryCount(categoryCounts, ['recovery']) > 0) {
    return titleResult('Recovery Minded', 'Recovery readiness badges earned.', earnedBadgeCount);
  }

  if (hasAnyBadge(badgeIdSet, CAMPSITE_BADGES)) {
    return titleResult('Basecamp Ready', 'Camp planning badge earned.', earnedBadgeCount);
  }

  if (hasAnyBadge(badgeIdSet, TERRAIN_BADGES) || categoryCount(categoryCounts, ['terrain']) > 0) {
    return titleResult('Terrain Watch', 'Terrain awareness badges earned.', earnedBadgeCount);
  }

  if (categoryCount(categoryCounts, ['route_behavior', 'distance']) > 0) {
    return titleResult('Route Analyst', 'Route behavior or distance badges earned.', earnedBadgeCount);
  }

  if (hasAnyBadge(badgeIdSet, FIELD_PLANNER_BADGES) || categoryCount(categoryCounts, ['exploration', 'notable_moments']) > 0) {
    return titleResult('Field Planner', 'Planning and field preparation badges earned.', earnedBadgeCount);
  }

  return titleResult('Trail Scout', 'No earned badge state available yet.', earnedBadgeCount);
}

export function buildBadgeIdentityProfileModel(input: { badges?: BadgeIdentityProfileBadgeInput[] | null } = {}): BadgeIdentityProfileModel {
  const rawBadges = Array.isArray(input.badges) ? input.badges : [];
  const visibleEarnedBadges = rawBadges
    .map(normalizeProfileBadge)
    .filter((badge): badge is BadgeIdentityProfileModel['visibleEarnedBadges'][number] => !!badge);
  const earnedBadgeIds = visibleEarnedBadges.map((badge) => badge.id);
  const title = deriveExpeditionIdentityTitle({
    earnedBadgeIds,
    earnedBadgeCount: visibleEarnedBadges.length,
  });

  return {
    title: title.title,
    titleDescription: title.description,
    titleBasis: title.basis,
    earnedBadgeCount: visibleEarnedBadges.length,
    earnedBadgeIds,
    hasEarnedState: visibleEarnedBadges.length > 0,
    excludedBadgeCount: Math.max(0, rawBadges.length - visibleEarnedBadges.length),
    visibleEarnedBadges,
  };
}
