export const DASHBOARD_WIDGET_GRAMMAR = {
  shellGap: 7,
  headerMinHeight: 20,
  footerMinHeight: 12,
  badgeHeight: 18,
  primaryMinHeight: 40,
  secondaryMinHeight: 28,
  microGap: 6,
  compact: {
    rowMinHeight: 24,
    titleMinWidth: 50,
    titleMaxWidth: '26%' as const,
    statusMinWidth: 62,
    statusMaxWidth: '36%' as const,
  },
  grid: {
    defaultPadX: 10,
    defaultPadY: 9,
    compactPadX: 10,
    compactPadY: 8,
    expandedPadX: 14,
    expandedPadY: 13,
    collapsedPadX: 8,
    collapsedPadY: 7,
    headerGap: 7,
    headerIconSlot: 18,
    titleFont: 11,
    titleCompactFont: 10,
    titleExpandedFont: 13,
    titleLetterSpacing: 1.15,
    titleLineHeight: 13,
  },
  detail: {
    cardRadius: 14,
    cardPadding: 14,
    cardGap: 7,
    sectionGap: 8,
    metricGap: 8,
    contentGap: 6,
  },
} as const;
