/**
 * ═══════════════════════════════════════════════════════════
 * ECS AI EXPEDITION ASSISTANT — Guidance Card List (Phase 7C)
 * ═══════════════════════════════════════════════════════════
 *
 * Renders proactive recommendation cards generated by the
 * Guided Recommendation Engine. Cards include:
 *   - Severity-colored left border and header
 *   - Priority badge
 *   - Live ECS data indicator
 *   - Expand/collapse for detailed explanation
 *   - Suggested action display
 *   - Dismiss button
 *   - Resolved state with subtle styling
 *   - Context basis badge
 *
 * Cards are concise, operationally useful, and non-intrusive.
 * They do not interrupt navigation or dashboard functions.
 */

import React, { useCallback } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
} from 'react-native';

import { SafeIcon as Ionicons } from '../SafeIcon';
import { ECS } from '../../lib/theme';

import { assistantStore } from '../../lib/assistantStore';
import type { AssistantGuidanceCard } from '../../lib/assistantTypes';
import {
  GUIDANCE_TRIGGER_DISPLAY,
  GUIDANCE_PRIORITY_DISPLAY,
  CONTEXT_BASIS_DISPLAY,
  RESPONSE_TYPE_DISPLAY,
} from '../../lib/assistantTypes';


// ── Single Guidance Card ─────────────────────────────────

function GuidanceCard({ card }: { card: AssistantGuidanceCard }) {
  const triggerDisplay = GUIDANCE_TRIGGER_DISPLAY[card.trigger];
  const priorityDisplay = GUIDANCE_PRIORITY_DISPLAY[String(card.priority)];
  const basisDisplay = CONTEXT_BASIS_DISPLAY[card.context_basis];
  const typeDisplay = RESPONSE_TYPE_DISPLAY[card.type];

  const severityColor = triggerDisplay?.color || typeDisplay?.color || '#FFB300';
  const isResolved = card.resolved;

  const handleToggleExpand = useCallback(() => {
    assistantStore.toggleCardExpanded(card.id);
  }, [card.id]);

  const handleDismiss = useCallback(() => {
    assistantStore.dismissCard(card.id);
  }, [card.id]);

  return (
    <View style={[
      styles.card,
      { borderLeftColor: isResolved ? ECS.strokeSoft : severityColor },
      isResolved && styles.cardResolved,
    ]}>
      {/* Card Header */}
      <TouchableOpacity
        style={styles.cardHeader}
        onPress={handleToggleExpand}
        activeOpacity={0.7}
      >
        <View style={styles.cardHeaderLeft}>
          <Ionicons
            name={(triggerDisplay?.icon || typeDisplay?.icon || 'alert-circle-outline') as any}
            size={16}
            color={isResolved ? ECS.muted : severityColor}
          />
          <View style={styles.cardTitleArea}>
            <Text
              style={[
                styles.cardTitle,
                isResolved && styles.cardTitleResolved,
              ]}
              numberOfLines={1}
            >
              {card.title}
            </Text>
            <View style={styles.cardBadges}>
              {/* Priority badge */}
              {priorityDisplay && !isResolved && (
                <View style={[styles.priorityBadge, { borderColor: priorityDisplay.color + '40' }]}>
                  <Text style={[styles.priorityText, { color: priorityDisplay.color }]}>
                    {priorityDisplay.label}
                  </Text>
                </View>
              )}

              {/* Live telemetry indicator */}
              {card.from_live_telemetry && !isResolved && (
                <View style={styles.liveBadge}>
                  <View style={styles.liveDot} />
                  <Text style={styles.liveText}>LIVE</Text>
                </View>
              )}

              {/* Context basis */}
              {basisDisplay && !isResolved && (
                <View style={[styles.basisBadge, { borderColor: basisDisplay.color + '40' }]}>
                  <Text style={[styles.basisText, { color: basisDisplay.color }]}>
                    {basisDisplay.shortLabel}
                  </Text>
                </View>
              )}

              {/* Resolved badge */}
              {isResolved && (
                <View style={styles.resolvedBadge}>
                  <Ionicons name="checkmark-circle-outline" size={9} color="#4CAF50" />
                  <Text style={styles.resolvedText}>RESOLVED</Text>
                </View>
              )}
            </View>
          </View>
        </View>

        <View style={styles.cardHeaderRight}>
          {/* Dismiss button */}
          <TouchableOpacity
            style={styles.dismissBtn}
            onPress={handleDismiss}
            activeOpacity={0.7}
            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
          >
            <Ionicons name="close" size={14} color={ECS.muted} />
          </TouchableOpacity>

          {/* Expand chevron */}
          <Ionicons
            name={card.expanded ? 'chevron-up' : 'chevron-down'}
            size={14}
            color={ECS.muted}
          />
        </View>
      </TouchableOpacity>

      {/* Card Body */}
      <Text style={[styles.cardBody, isResolved && styles.cardBodyResolved]}>
        {card.body}
      </Text>

      {/* Expanded Content */}
      {card.expanded && (
        <View style={styles.expandedContent}>
          {/* Explanation */}
          {card.explanation && card.explanation !== card.body && (
            <View style={styles.expandedSection}>
              <View style={styles.expandedSectionHeader}>
                <Ionicons name="information-circle-outline" size={12} color={ECS.muted} />
                <Text style={styles.expandedSectionLabel}>EXPLANATION</Text>
              </View>
              <Text style={styles.expandedText}>{card.explanation}</Text>
            </View>
          )}

          {/* Suggested Action */}
          {card.suggested_action && (
            <View style={[styles.expandedSection, styles.actionSection]}>
              <View style={styles.expandedSectionHeader}>
                <Ionicons name="arrow-forward-circle-outline" size={12} color="#42A5F5" />
                <Text style={[styles.expandedSectionLabel, { color: '#42A5F5' }]}>
                  SUGGESTED ACTION
                </Text>
              </View>
              <Text style={[styles.expandedText, styles.actionText]}>
                {card.suggested_action}
              </Text>
            </View>
          )}

          {/* Source categories */}
          {card.source_categories.length > 0 && (
            <View style={styles.sourcesRow}>
              <Text style={styles.sourcesLabel}>Sources: </Text>
              <Text style={styles.sourcesText}>
                {card.source_categories.join(', ')}
              </Text>
            </View>
          )}

          {/* Timestamp */}
          <Text style={styles.timestampText}>
            Generated: {new Date(card.generated_at).toLocaleTimeString()}
            {card.resolved_at ? ` | Resolved: ${new Date(card.resolved_at).toLocaleTimeString()}` : ''}
          </Text>
        </View>
      )}
    </View>
  );
}


// ── Main List Component ──────────────────────────────────

interface GuidanceCardListProps {
  cards: AssistantGuidanceCard[];
  showResolved?: boolean;
}

export default function GuidanceCardList({ cards, showResolved = true }: GuidanceCardListProps) {
  const activeCards = cards.filter(c => !c.dismissed && !c.resolved);
  const resolvedCards = showResolved ? cards.filter(c => !c.dismissed && c.resolved) : [];

  const handleClearResolved = useCallback(() => {
    assistantStore.clearResolvedCards();
  }, []);

  if (activeCards.length === 0 && resolvedCards.length === 0) {
    return null; // Don't render anything if no cards
  }

  return (
    <View style={styles.container}>
      {/* Section Header */}
      <View style={styles.sectionHeader}>
        <View style={styles.sectionHeaderLeft}>
          <Ionicons name="bulb-outline" size={14} color={ECS.accent} />
          <Text style={styles.sectionTitle}>RECOMMENDATIONS</Text>
        </View>
        {activeCards.length > 0 && (
          <View style={styles.countBadge}>
            <Text style={styles.countText}>{activeCards.length}</Text>
          </View>
        )}
      </View>

      {/* Active Cards */}
      {activeCards.map(card => (
        <GuidanceCard key={card.id} card={card} />
      ))}

      {/* Resolved Cards */}
      {resolvedCards.length > 0 && (
        <>
          <View style={styles.resolvedHeader}>
            <Text style={styles.resolvedHeaderText}>
              RESOLVED ({resolvedCards.length})
            </Text>
            <TouchableOpacity
              onPress={handleClearResolved}
              activeOpacity={0.7}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            >
              <Text style={styles.clearResolvedText}>Clear</Text>
            </TouchableOpacity>
          </View>
          {resolvedCards.map(card => (
            <GuidanceCard key={card.id} card={card} />
          ))}
        </>
      )}
    </View>
  );
}


// ── Styles ───────────────────────────────────────────────

const styles = StyleSheet.create({
  container: {
    marginBottom: 12,
  },

  // Section header
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 4,
    color: ECS.accent,
  },
  countBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(212,160,23,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  countText: {
    fontSize: 10,
    fontWeight: '800',
    color: ECS.accent,
  },

  // Card
  card: {
    backgroundColor: ECS.bgPanel,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: ECS.stroke,
    borderLeftWidth: 3,
    marginBottom: 8,
    overflow: 'hidden',
  },
  cardResolved: {
    opacity: 0.65,
    borderColor: ECS.strokeSoft,
  },

  // Card header
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 4,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    flex: 1,
  },
  cardTitleArea: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: ECS.text,
    marginBottom: 4,
  },
  cardTitleResolved: {
    color: ECS.muted,
    textDecorationLine: 'line-through',
  },
  cardBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  cardHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 8,
  },

  // Priority badge
  priorityBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
    borderWidth: 1,
  },
  priorityText: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1,
  },

  // Live badge
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
    backgroundColor: 'rgba(76,175,80,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(76,175,80,0.30)',
  },
  liveDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#4CAF50',
  },
  liveText: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1,
    color: '#4CAF50',
  },

  // Context basis badge
  basisBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
    borderWidth: 1,
  },
  basisText: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1,
  },

  // Resolved badge
  resolvedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
    backgroundColor: 'rgba(76,175,80,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(76,175,80,0.20)',
  },
  resolvedText: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1,
    color: '#4CAF50',
  },

  // Dismiss button
  dismissBtn: {
    padding: 2,
  },

  // Card body
  cardBody: {
    fontSize: 12,
    color: ECS.text,
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingBottom: 10,
    paddingLeft: 36, // Align with title (icon width + gap)
  },
  cardBodyResolved: {
    color: ECS.muted,
  },

  // Expanded content
  expandedContent: {
    borderTopWidth: 0.5,
    borderTopColor: ECS.stroke,
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingLeft: 36,
    backgroundColor: 'rgba(255,255,255,0.01)',
  },
  expandedSection: {
    marginBottom: 10,
  },
  expandedSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  expandedSectionLabel: {
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 2,
    color: ECS.muted,
  },
  expandedText: {
    fontSize: 12,
    color: ECS.text,
    lineHeight: 18,
  },
  actionSection: {
    backgroundColor: 'rgba(66,165,245,0.04)',
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(66,165,245,0.10)',
  },
  actionText: {
    color: '#B0D4F5',
  },
  sourcesRow: {
    flexDirection: 'row',
    marginTop: 4,
  },
  sourcesLabel: {
    fontSize: 9,
    color: ECS.muted,
    fontWeight: '600',
  },
  sourcesText: {
    fontSize: 9,
    color: ECS.muted,
    flex: 1,
  },
  timestampText: {
    fontSize: 8,
    color: ECS.muted,
    marginTop: 6,
    textAlign: 'right',
  },

  // Resolved section header
  resolvedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 6,
    paddingTop: 8,
    borderTopWidth: 0.5,
    borderTopColor: ECS.stroke,
  },
  resolvedHeaderText: {
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 2,
    color: ECS.muted,
  },
  clearResolvedText: {
    fontSize: 10,
    color: ECS.accent,
    fontWeight: '600',
  },
});



