/**
 * TripSummaries — Insert Tab Panel in Intel Tab
 *
 * Auto-generates structured expedition reports from:
 *   - Expedition snapshot data
 *   - Route data (from Navigate)
 *   - Consumables projections
 *   - Risk scoring
 *
 * Each summary includes:
 *   - Trip Title, Date range, Distance, Terrain classification
 *   - Estimated duration, Fuel projection, Water projection
 *   - Loadout summary, Risk score, Final readiness state
 *
 * Supports PDF export with ECS version footer and accuracy disclaimer.
 * Rendered inside an ECSModal overlay panel — uses ScrollView for internal scrolling.
 */
import React, { useMemo, useCallback } from 'react';
import { View, Text, TouchableOpacity, ScrollView, StyleSheet, Platform } from 'react-native';

import { SafeIcon as Ionicons } from '../SafeIcon';

import { TACTICAL } from '../../lib/theme';
import { ECS_VERSION, ECS_PRODUCT, ECS_ORG } from './DocumentPreviewModal';
import type { ImportedRoute } from '../../lib/routeStore';
import type { BuilderStepState } from '../../lib/expeditionCache';
import type { EcsExpedition } from '../../lib/expeditionTypes';

interface Props {
  builderState: BuilderStepState;
  activeRoute: ImportedRoute | null;
  riskScore: number | null;
  riskLevel: string;
  riskColor: string;
  loadoutStats: { totalActive: number; packedActive: number; pct: number };
  expeditions: EcsExpedition[];
  onExport: (content: string) => void;
  onViewDocument: (id: string, title: string, content: string) => void;
  onToast: (msg: string) => void;
}

export default function TripSummaries({
  builderState,
  activeRoute,
  riskScore,
  riskLevel,
  riskColor,
  loadoutStats,
  expeditions,
  onExport,
  onViewDocument,
  onToast,
}: Props) {
  // ── Generate Summary Content ─────────────────────────────
  const summaryContent = useMemo(() => {
    const now = new Date();
    const lines: string[] = [
      `${'═'.repeat(56)}`,
      `  EXPEDITION COMMAND SYSTEM — TRIP SUMMARY REPORT`,
      `${'═'.repeat(56)}`,
      '',
      `Report Generated: ${now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}`,
      `Time: ${now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}`,
      '',
      `${'─'.repeat(56)}`,
      '  VEHICLE CONFIGURATION',
      `${'─'.repeat(56)}`,
      `  Vehicle:    ${builderState.vehicleName || 'Not configured'}`,
      `  Framework:  ${builderState.frameworkType || 'Not set'}`,
      `  Zones:      ${builderState.zoneCount || 0} configured`,
      '',
    ];

    if (activeRoute) {
      lines.push(`${'─'.repeat(56)}`);
      lines.push('  ROUTE DATA');
      lines.push(`${'─'.repeat(56)}`);
      lines.push(`  Route Name:     ${activeRoute.name}`);
      lines.push(`  Distance:       ${activeRoute.total_distance_miles.toFixed(1)} mi`);
      lines.push(`  Waypoints:      ${activeRoute.waypoint_count}`);
      lines.push(`  Segments:       ${activeRoute.segment_count}`);
      if (activeRoute.elevation_gain_ft) {
        lines.push(`  Elevation Gain: ${activeRoute.elevation_gain_ft} ft`);
      }
      lines.push('');
    }

    if (riskScore !== null) {
      lines.push(`${'─'.repeat(56)}`);
      lines.push('  RISK ASSESSMENT');
      lines.push(`${'─'.repeat(56)}`);
      lines.push(`  Score:  ${riskScore.toFixed(2)}`);
      lines.push(`  Level:  ${riskLevel}`);
      lines.push('');
    }

    lines.push(`${'─'.repeat(56)}`);
    lines.push('  LOADOUT STATUS');
    lines.push(`${'─'.repeat(56)}`);
    lines.push(`  Active Items:  ${loadoutStats.totalActive}`);
    lines.push(`  Packed:        ${loadoutStats.packedActive} (${loadoutStats.pct}%)`);
    lines.push(`  Readiness:     ${loadoutStats.pct >= 100 ? 'READY' : loadoutStats.pct >= 75 ? 'NEAR READY' : 'IN PROGRESS'}`);
    lines.push('');

    lines.push(`${'═'.repeat(56)}`);
    lines.push('');
    lines.push('ACCURACY DISCLAIMER:');
    lines.push('This report is generated by ECS for planning purposes only.');
    lines.push('All projections, risk assessments, and calculations are');
    lines.push('estimates based on user-provided data. Verify all critical');
    lines.push('information independently before field deployment.');
    lines.push('');
    lines.push(`${'─'.repeat(56)}`);
    lines.push(`${ECS_PRODUCT} ${ECS_VERSION}`);
    lines.push(`${ECS_ORG}`);
    lines.push(`Report ID: RPT-${now.getTime().toString(36).toUpperCase()}`);
    lines.push(`${'─'.repeat(56)}`);

    return lines.join('\n');
  }, [builderState, activeRoute, riskScore, riskLevel, loadoutStats]);

  const handleExport = useCallback(() => {
    onExport(summaryContent);
  }, [summaryContent, onExport]);

  const handleViewFull = useCallback(() => {
    onViewDocument('trip-summary', 'Trip Summary Report', summaryContent);
  }, [summaryContent, onViewDocument]);

  const readinessLabel = useMemo(() => {
    if (loadoutStats.pct >= 100) return { text: 'READY', color: '#4CAF50' };
    if (loadoutStats.pct >= 75) return { text: 'NEAR READY', color: TACTICAL.amber };
    return { text: 'IN PROGRESS', color: TACTICAL.textMuted };
  }, [loadoutStats.pct]);

  return (
    <View style={styles.section}>


      {/* Section Header */}
      <View style={styles.sectionHeader}>
        <View style={styles.sectionHeaderLeft}>
          <View style={styles.sectionDot} />
          <Text style={styles.sectionTitle}>TRIP SUMMARIES</Text>
        </View>
      </View>

      {/* Current Expedition Summary Card */}
      <View style={styles.summaryCard}>
        <View style={styles.summaryCardHeader}>
          <View style={styles.summaryCardHeaderLeft}>
            <Ionicons name="flag-outline" size={15} color={TACTICAL.amber} />
            <Text style={styles.summaryCardTitle}>CURRENT EXPEDITION</Text>
          </View>
          <View style={[styles.readinessBadge, { borderColor: `${readinessLabel.color}40` }]}>
            <View style={[styles.readinessDot, { backgroundColor: readinessLabel.color }]} />
            <Text style={[styles.readinessText, { color: readinessLabel.color }]}>
              {readinessLabel.text}
            </Text>
          </View>
        </View>

        {/* Summary Grid */}
        <View style={styles.summaryGrid}>
          <SummaryTile label="VEHICLE" value={builderState.vehicleName || 'Not set'} />
          <SummaryTile label="FRAMEWORK" value={builderState.frameworkType || 'Not set'} />
          <SummaryTile label="ZONES" value={`${builderState.zoneCount || 0}`} />
          <SummaryTile
            label="RISK"
            value={riskScore !== null ? `${riskScore.toFixed(1)} ${riskLevel}` : 'N/A'}
            valueColor={riskColor}
          />
        </View>

        {/* Route Info */}
        {activeRoute && (
          <View style={styles.routeSection}>
            <Text style={styles.routeSectionLabel}>ROUTE</Text>
            <View style={styles.routeRow}>
              <Text style={styles.routeName}>{activeRoute.name}</Text>
              <Text style={styles.routeDistance}>
                {activeRoute.total_distance_miles.toFixed(1)} mi
              </Text>
            </View>
          </View>
        )}

        {/* Loadout Info */}
        <View style={styles.routeSection}>
          <Text style={styles.routeSectionLabel}>LOADOUT</Text>
          <View style={styles.routeRow}>
            <Text style={styles.routeName}>{loadoutStats.totalActive} items</Text>
            <Text style={styles.routeDistance}>{loadoutStats.pct}% packed</Text>
          </View>
          {/* Progress bar */}
          <View style={styles.progressBar}>
            <View style={[styles.progressFill, { width: `${Math.min(loadoutStats.pct, 100)}%` }]} />
          </View>
        </View>

        {/* Action Buttons */}
        <View style={styles.actionRow}>
          <TouchableOpacity
            style={styles.viewBtn}
            onPress={handleViewFull}
            activeOpacity={0.7}
          >
            <Ionicons name="document-text-outline" size={14} color={TACTICAL.amber} />
            <Text style={styles.viewBtnText}>VIEW FULL REPORT</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.exportBtn}
            onPress={handleExport}
            activeOpacity={0.7}
          >
            <Ionicons name="download-outline" size={14} color="#0B0F12" />
            <Text style={styles.exportBtnText}>EXPORT</Text>
          </TouchableOpacity>
        </View>
      </View>

      {/* ECS Version Footer */}
      <View style={styles.versionFooter}>
        <Text style={styles.versionFooterText}>
          {ECS_PRODUCT} {ECS_VERSION}
        </Text>
      </View>

      {/* Expedition History */}
      {expeditions.length > 0 && (
        <View style={styles.historyCard}>
          <View style={styles.historyHeader}>
            <Ionicons name="time-outline" size={13} color={TACTICAL.amber} />
            <Text style={styles.historyTitle}>
              EXPEDITION HISTORY ({expeditions.length})
            </Text>
          </View>
          {expeditions.slice(0, 6).map((exp: any, idx: number) => (
            <View key={exp.id || idx} style={styles.historyRow}>
              <View style={[styles.historyDot, {
                backgroundColor: exp.status === 'active' ? '#4CAF50'
                  : exp.status === 'completed' ? TACTICAL.amber
                  : TACTICAL.textMuted,
              }]} />
              <View style={styles.historyInfo}>
                <Text style={styles.historyName} numberOfLines={1}>{exp.title}</Text>
                <Text style={styles.historyMeta}>
                  {exp.status?.toUpperCase() || 'DRAFT'}
                  {exp.terrain ? ` \u2022 ${exp.terrain}` : ''}
                  {exp.duration_days ? ` \u2022 ${exp.duration_days}D` : ''}
                </Text>
              </View>
            </View>
          ))}
        </View>
      )}

      {/* Accuracy Disclaimer */}
      <View style={styles.disclaimerCard}>
        <View style={styles.disclaimerHeader}>
          <Ionicons name="alert-circle-outline" size={12} color={TACTICAL.textMuted} />
          <Text style={styles.disclaimerTitle}>ACCURACY DISCLAIMER</Text>
        </View>
        <Text style={styles.disclaimerText}>
          All trip summaries are generated from user-provided data and algorithmic estimates.
          Fuel projections, water calculations, and risk assessments should be independently
          verified before field deployment. ECS is a planning tool, not a substitute for
          professional judgment.
        </Text>
      </View>
    </View>

  );

}

function SummaryTile({ label, value, valueColor }: { label: string; value: string; valueColor?: string }) {
  return (
    <View style={styles.summaryTile}>
      <Text style={styles.summaryTileLabel}>{label}</Text>
      <Text style={[styles.summaryTileValue, valueColor ? { color: valueColor } : {}]} numberOfLines={1}>
        {value}
      </Text>
    </View>
  );
}
const styles = StyleSheet.create({
  scrollWrap: { flex: 1 },
  section: { gap: 10, padding: 16, paddingTop: 20, paddingBottom: 30 },



  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: TACTICAL.amber,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: TACTICAL.amber,
    letterSpacing: 2,
  },

  summaryCard: {
    backgroundColor: 'rgba(0,0,0,0.22)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(196, 138, 44, 0.2)',
    padding: 14,
    gap: 12,
  },
  summaryCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  summaryCardTitle: {
    fontSize: 10,
    fontWeight: '900',
    color: TACTICAL.amber,
    letterSpacing: 2,
  },
  readinessBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
  },
  readinessDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
  },
  readinessText: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.5,
  },

  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  summaryTile: {
    width: '47%',
    backgroundColor: 'rgba(62, 79, 60, 0.08)',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(62, 79, 60, 0.12)',
  },
  summaryTileLabel: {
    fontSize: 7,
    fontWeight: '800',
    color: TACTICAL.textMuted,
    letterSpacing: 2,
    marginBottom: 3,
  },
  summaryTileValue: {
    fontSize: 12,
    fontWeight: '700',
    color: TACTICAL.text,
  },

  routeSection: {
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(62, 79, 60, 0.12)',
    gap: 4,
  },
  routeSectionLabel: {
    fontSize: 8,
    fontWeight: '800',
    color: TACTICAL.amber,
    letterSpacing: 2,
  },
  routeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  routeName: {
    fontSize: 12,
    fontWeight: '600',
    color: TACTICAL.text,
  },
  routeDistance: {
    fontSize: 12,
    fontWeight: '700',
    color: TACTICAL.amber,
    fontFamily: 'Courier',
  },
  progressBar: {
    height: 3,
    backgroundColor: 'rgba(62, 79, 60, 0.15)',
    borderRadius: 2,
    marginTop: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: TACTICAL.amber,
    borderRadius: 2,
  },

  actionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
  },
  viewBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(196, 138, 44, 0.3)',
    backgroundColor: 'rgba(196, 138, 44, 0.06)',
  },
  viewBtnText: {
    fontSize: 9,
    fontWeight: '900',
    color: TACTICAL.amber,
    letterSpacing: 1.5,
  },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: TACTICAL.amber,
  },
  exportBtnText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#0B0F12',
    letterSpacing: 1.5,
  },

  versionFooter: {
    alignItems: 'center',
    paddingVertical: 4,
  },
  versionFooterText: {
    fontSize: 8,
    fontWeight: '600',
    color: 'rgba(138, 138, 133, 0.4)',
    letterSpacing: 1,
  },

  historyCard: {
    backgroundColor: 'rgba(0,0,0,0.15)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(62, 79, 60, 0.2)',
    padding: 12,
  },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginBottom: 8,
  },
  historyTitle: {
    fontSize: 9,
    fontWeight: '900',
    color: TACTICAL.amber,
    letterSpacing: 2,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(62, 79, 60, 0.08)',
  },
  historyDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  historyInfo: { flex: 1 },
  historyName: {
    fontSize: 12,
    fontWeight: '700',
    color: TACTICAL.text,
  },
  historyMeta: {
    fontSize: 9,
    color: TACTICAL.textMuted,
    letterSpacing: 0.5,
    marginTop: 1,
  },

  disclaimerCard: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(62, 79, 60, 0.15)',
    padding: 10,
    gap: 6,
  },
  disclaimerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  disclaimerTitle: {
    fontSize: 8,
    fontWeight: '800',
    color: TACTICAL.textMuted,
    letterSpacing: 2,
  },
  disclaimerText: {
    fontSize: 10,
    color: 'rgba(138, 138, 133, 0.6)',
    lineHeight: 15,
  },
});



