/**
 * Accessory → Container Mapping
 *
 * Deterministic mapping from Accessory Framework selections to container groups.
 * Each enabled accessory generates one or more container groups with smart defaults.
 *
 * RULES:
 *   - Only enabled accessories generate container groups
 *   - Each group has a sensible default container with name + slot count
 *   - Container allocations are auto-generated when the Accessory Framework is saved
 *   - Removing an accessory removes its container group(s) automatically
 *   - Preserves user-modified slot counts for zones that persist across edits
 *
 * The Accessory Framework is the single source of truth for container generation.
 * No separate container or loadout wizard step is required.
 */


import type { AccessorySelections } from '../components/vehicle-wizard/AccessoryConfigStep';

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

export interface ContainerGroup {
  /** Unique group identifier (matches accessory category ID) */
  groupId: string;
  /** Human-readable group label */
  groupLabel: string;
  /** The accessory category ID this group was derived from */
  accessoryCategoryId: string;
  /** Icon name (Ionicons) */
  icon: string;
  /** Accent color */
  color: string;
  /** Sort order for consistent display */
  sortOrder: number;
  /** Default containers auto-generated for this group */
  defaultContainers: ContainerDefault[];
}

export interface ContainerDefault {
  /** Unique container identifier */
  containerId: string;
  /** Default container name */
  name: string;
  /** Default slot count */
  defaultSlots: number;
  /** Zone type classification */
  zoneType: string;
  /** Icon name */
  icon: string;
  /** Accent color */
  color: string;
}

/**
 * A container allocation that the user can modify.
 * Extends ContainerDefault with the user's current slot count.
 */
export interface ContainerAllocation {
  /** Unique container identifier */
  containerId: string;
  /** Container name (user can rename) */
  name: string;
  /** Current slot count (user-adjustable) */
  slotCount: number;
  /** Default slot count (for reset) */
  defaultSlots: number;
  /** Zone type classification */
  zoneType: string;
  /** Icon name */
  icon: string;
  /** Accent color */
  color: string;
  /** Sort order */
  sortOrder: number;
  /** Parent group ID (accessory category) */
  groupId: string;
  /** Parent group label */
  groupLabel: string;
}


// ═══════════════════════════════════════════════════════════════
// ACCESSORY → CONTAINER GROUP MAPPING
// ═══════════════════════════════════════════════════════════════

/**
 * Defines the container group(s) generated by each accessory category.
 * Each accessory maps to exactly one container group with one or more default containers.
 */
const ACCESSORY_CONTAINER_MAP: Record<string, Omit<ContainerGroup, 'accessoryCategoryId'>> = {
  // ── Cab Rack → Cab Storage Containers ──────────────────
  cab_rack: {
    groupId: 'cab_storage',
    groupLabel: 'Cab Storage',
    icon: 'barbell-outline',
    color: '#FF6B6B',
    sortOrder: 0,
    defaultContainers: [
      {
        containerId: 'cab_rack_main',
        name: 'Cab Rack Storage',
        defaultSlots: 4,
        zoneType: 'RACK',
        icon: 'barbell-outline',
        color: '#FF6B6B',
      },
    ],
  },

  // ── Cab Rack Accessories → Cab Rack Acc Containers ─────
  // ── Bed / Drawer → Bed Drawer Containers ───────────────
  bed_drawer: {
    groupId: 'bed_drawer_storage',
    groupLabel: 'Drawer Storage',
    icon: 'server-outline',
    color: '#96CEB4',
    sortOrder: 1,
    defaultContainers: [
      {
        containerId: 'bed_drawer_main',
        name: 'Drawer Storage',
        defaultSlots: 8,
        zoneType: 'DRAWER',
        icon: 'server-outline',
        color: '#96CEB4',
      },
    ],
  },

  // ── Roof / Crossbars → Roof Containers ─────────────────
  roof_rack: {
    groupId: 'roof_storage',
    groupLabel: 'Roof Storage',
    icon: 'resize-outline',
    color: '#4FC3F7',
    sortOrder: 2,
    defaultContainers: [
      {
        containerId: 'roof_rack_main',
        name: 'Roof Rack Storage',
        defaultSlots: 4,
        zoneType: 'RACK',
        icon: 'resize-outline',
        color: '#4FC3F7',
      },
    ],
  },

  // ── RTT → Sleep Containers ─────────────────────────────
  rtt: {
    groupId: 'sleep_system',
    groupLabel: 'Sleep System',
    icon: 'trail-sign-outline',
    color: '#C77DFF',
    sortOrder: 3,
    defaultContainers: [
      {
        containerId: 'rtt_main',
        name: 'Roof Top Tent',
        defaultSlots: 2,
        zoneType: 'SHELTER',
        icon: 'trail-sign-outline',
        color: '#C77DFF',
      },
    ],
  },

  // ── Interior Storage → Interior Containers ─────────────
  interior_storage: {
    groupId: 'interior_storage',
    groupLabel: 'Interior Storage',
    icon: 'file-tray-stacked-outline',
    color: '#4ECDC4',
    sortOrder: 4,
    defaultContainers: [
      {
        containerId: 'interior_main',
        name: 'Interior Storage',
        defaultSlots: 6,
        zoneType: 'INTERIOR',
        icon: 'file-tray-stacked-outline',
        color: '#4ECDC4',
      },
    ],
  },

  // ── Fridge / Slide → Kitchen Containers ────────────────
  // ── Recovery Mount → Recovery Containers ───────────────
  recovery_mount: {
    groupId: 'recovery_system',
    groupLabel: 'Recovery Mount Hitch System',
    icon: 'construct-outline',
    color: '#AB47BC',
    sortOrder: 5,
    defaultContainers: [
      {
        containerId: 'recovery_main',
        name: 'Recovery Mount Hitch System',
        defaultSlots: 2,
        zoneType: 'RECOVERY',
        icon: 'construct-outline',
        color: '#AB47BC',
      },
    ],
  },

  // ── Water Storage → Water Containers ───────────────────
  water_storage: {
    groupId: 'water_system',
    groupLabel: 'Water System',
    icon: 'water-outline',
    color: '#26A69A',
    sortOrder: 6,
    defaultContainers: [
      {
        containerId: 'water_main',
        name: 'Water Storage',
        defaultSlots: 2,
        zoneType: 'WATER',
        icon: 'water-outline',
        color: '#26A69A',
      },
    ],
  },

  // ── Power / Battery → Power Containers ─────────────────
  power_system: {
    groupId: 'power_system',
    groupLabel: 'Power System',
    icon: 'flash-outline',
    color: '#FFB74D',
    sortOrder: 7,
    defaultContainers: [
      {
        containerId: 'power_main',
        name: 'Power / Battery',
        defaultSlots: 2,
        zoneType: 'POWER',
        icon: 'flash-outline',
        color: '#FFB74D',
      },
    ],
  },
};


// ═══════════════════════════════════════════════════════════════
// CORE FUNCTIONS
// ═══════════════════════════════════════════════════════════════

/**
 * Get the container groups that should be active based on current accessory selections.
 * Only enabled accessories generate container groups.
 *
 * @param accessories - Current accessory selections from Step 3
 * @returns ContainerGroup[] - Ordered array of active container groups
 */
export function getActiveContainerGroups(
  accessories: AccessorySelections
): ContainerGroup[] {
  const groups: ContainerGroup[] = [];

  for (const [categoryId, state] of Object.entries(accessories)) {
    if (!state?.enabled) continue;

    const mapping = ACCESSORY_CONTAINER_MAP[categoryId];
    if (!mapping) continue;

    groups.push({
      ...mapping,
      accessoryCategoryId: categoryId,
    });
  }

  // Sort by sortOrder for consistent display
  groups.sort((a, b) => a.sortOrder - b.sortOrder);

  return groups;
}

/**
 * Generate container allocations from accessory selections.
 * Each enabled accessory creates its default containers with smart defaults.
 *
 * Preserves user-modified slot counts for containers that still exist
 * from a previous generation (e.g., when going back to Step 3 and returning).
 *
 * @param accessories - Current accessory selections from Step 3
 * @param previousAllocations - Previous allocations to preserve user modifications
 * @returns ContainerAllocation[] - Ordered array of container allocations
 */
export function generateContainerAllocations(
  accessories: AccessorySelections,
  previousAllocations?: ContainerAllocation[],
): ContainerAllocation[] {
  const groups = getActiveContainerGroups(accessories);
  const allocations: ContainerAllocation[] = [];

  // Build lookup of previous slot counts by containerId
  const prevMap = new Map<string, { slotCount: number; name: string }>();
  if (previousAllocations) {
    for (const prev of previousAllocations) {
      prevMap.set(prev.containerId, { slotCount: prev.slotCount, name: prev.name });
    }
  }

  for (const group of groups) {
    for (const container of group.defaultContainers) {
      const prev = prevMap.get(container.containerId);
      allocations.push({
        containerId: container.containerId,
        name: prev?.name || container.name,
        slotCount: prev?.slotCount ?? container.defaultSlots,
        defaultSlots: container.defaultSlots,
        zoneType: container.zoneType,
        icon: container.icon,
        color: container.color,
        sortOrder: group.sortOrder,
        groupId: group.groupId,
        groupLabel: group.groupLabel,
      });
    }
  }

  return allocations;
}

/**
 * Clean orphaned allocations when accessories change.
 * Returns only allocations whose parent accessory is still enabled.
 *
 * @param allocations - Current container allocations
 * @param accessories - Current accessory selections
 * @returns ContainerAllocation[] - Cleaned allocations
 */
export function cleanOrphanedAllocations(
  allocations: ContainerAllocation[],
  accessories: AccessorySelections,
): ContainerAllocation[] {
  const activeGroups = getActiveContainerGroups(accessories);
  const activeGroupIds = new Set(activeGroups.map(g => g.groupId));

  return allocations.filter(a => activeGroupIds.has(a.groupId));
}

/**
 * Get total slot count across all allocations.
 */
export function getTotalSlots(allocations: ContainerAllocation[]): number {
  return allocations.reduce((sum, a) => sum + a.slotCount, 0);
}

/**
 * Get total group count (unique groups).
 */
export function getGroupCount(allocations: ContainerAllocation[]): number {
  const groups = new Set(allocations.map(a => a.groupId));
  return groups.size;
}

/**
 * Convert ContainerAllocations to the ZoneAllocation format used by the existing
 * vehicle config persistence layer. This bridges the new accessory-driven containers
 * with the existing save mechanism.
 */
export function allocationsToZonePayload(
  allocations: ContainerAllocation[],
): {
  zoneName: string;
  zoneType: string;
  slotCount: number;
  color: string;
  icon: string;
  sortOrder: number;
}[] {
  return allocations.map(a => ({
    zoneName: a.name,
    zoneType: a.zoneType,
    slotCount: a.slotCount,
    color: a.color,
    icon: a.icon,
    sortOrder: a.sortOrder,
  }));
}

