/**
 * ECS Adaptive Expedition Guidance — Type Definitions (Phase 11 + Phase 12)
 * ==========================================================================
 *
 * Defines the data structures for adaptive expedition guidance that
 * analyzes outputs from PredictiveExpeditionAwareness, OfflineExpeditionIntelligence,
 * CollaborativeExpeditionIntelligence, VehicleDisplayMode, route navigation,
 * and breadcrumb trail to generate recommended actions during an expedition.
 *
 * GUIDANCE CATEGORIES:
 *   1. Fuel Safety Guidance
 *   2. Daylight Safety Guidance
 *   3. Terrain Safety Guidance
 *   4. Remoteness Safety Guidance
 *   5. Weather Safety Guidance
 *   6. Bailout Route Awareness
 *   7. Collaborative Intelligence (Phase 12)
 *
 * PRIORITY SYSTEM:
 *   Info → Advisory → Warning → Critical
 *
 * DISMISSAL:
 *   Dismissed messages are suppressed for 10–15 minutes.
 *
 * All outputs are driver-safe: short messages, simple labels,
 * no complex charts or large text blocks.
 */

// ── Guidance Priority Levels ────────────────────────────────

export type GuidancePriority = 'info' | 'advisory' | 'warning' | 'critical';

// ── Guidance Categories ─────────────────────────────────────

export type GuidanceCategory =
  | 'fuel'
  | 'daylight'
  | 'terrain'
  | 'remoteness'
  | 'weather'
  | 'bailout'
  | 'collaborative';

// ── Guidance Message ────────────────────────────────────────

/**
 * A single guidance message generated by the adaptive guidance engine.
 */
export interface GuidanceMessage {
  /** Unique identifier for this message instance */
  id: string;
  /** Guidance category */
  category: GuidanceCategory;
  /** Priority level */
  priority: GuidancePriority;
  /** Short driver-safe message (max ~50 chars) */
  message: string;
  /** Optional secondary detail line */
  detail: string | null;
  /** Icon name (Ionicons) */
  icon: string;
  /** Display color */
  color: string;
  /** When this guidance was generated */
  generatedAt: string;
  /** Whether this message has been dismissed by the user */
  dismissed: boolean;
  /** When this message was dismissed (for suppression timer) */
  dismissedAt: string | null;
  /** A stable key for deduplication (category + condition hash) */
  deduplicationKey: string;
}

// ── Bailout Route Info ──────────────────────────────────────

/**
 * Information about a nearby bailout/exit route.
 */
export interface NearbyBailoutInfo {
  /** Whether bailout data is available */
  available: boolean;
  /** Name of nearest bailout point */
  nearestName: string | null;
  /** Distance to nearest bailout (miles) */
  nearestDistanceMi: number | null;
  /** Type of nearest bailout */
  nearestType: string | null;
  /** Total number of bailout points within range */
  totalNearby: number;
}

// ── Guidance Summary ────────────────────────────────────────

/**
 * Summary of all active guidance messages.
 */
export interface GuidanceSummary {
  /** Total active (non-dismissed) messages */
  totalActive: number;
  /** Count by priority */
  criticalCount: number;
  warningCount: number;
  advisoryCount: number;
  infoCount: number;
  /** Highest priority among active messages */
  highestPriority: GuidancePriority | null;
  /** The single most important message (highest priority, most recent) */
  topMessage: GuidanceMessage | null;
}

// ── Combined Guidance Output ────────────────────────────────

/**
 * Complete Adaptive Expedition Guidance output.
 */
export interface AdaptiveGuidanceOutput {
  /** Whether the guidance engine is active */
  isActive: boolean;
  /** When guidance was last evaluated */
  evaluatedAt: string;
  /** Whether the device is in ExpeditionDrive mode */
  isExpeditionDrive: boolean;

  /** All active guidance messages (sorted by priority, then time) */
  messages: GuidanceMessage[];
  /** Summary of active guidance */
  summary: GuidanceSummary;
  /** Nearby bailout route information */
  bailoutInfo: NearbyBailoutInfo;

  /** Total messages generated (including dismissed) */
  totalGenerated: number;
  /** Total messages currently dismissed/suppressed */
  totalDismissed: number;
}

// ── Display Constants ───────────────────────────────────────

export const GUIDANCE_PRIORITY_COLORS: Record<GuidancePriority, string> = {
  info: '#5AC8FA',
  advisory: '#FFB74D',
  warning: '#FF7043',
  critical: '#EF5350',
};

export const GUIDANCE_PRIORITY_ICONS: Record<GuidancePriority, string> = {
  info: 'information-circle-outline',
  advisory: 'alert-circle-outline',
  warning: 'warning-outline',
  critical: 'flame-outline',
};

export const GUIDANCE_PRIORITY_LABELS: Record<GuidancePriority, string> = {
  info: 'Info',
  advisory: 'Advisory',
  warning: 'Warning',
  critical: 'Critical',
};

/** Priority sort order (higher = more important) */
export const GUIDANCE_PRIORITY_ORDER: Record<GuidancePriority, number> = {
  info: 0,
  advisory: 1,
  warning: 2,
  critical: 3,
};

export const GUIDANCE_CATEGORY_ICONS: Record<GuidanceCategory, string> = {
  fuel: 'speedometer-outline',
  daylight: 'sunny-outline',
  terrain: 'trail-sign-outline',
  remoteness: 'radio-outline',
  weather: 'thunderstorm-outline',
  bailout: 'git-branch-outline',
  collaborative: 'people-outline',
};

export const GUIDANCE_CATEGORY_LABELS: Record<GuidanceCategory, string> = {
  fuel: 'Fuel',
  daylight: 'Daylight',
  terrain: 'Terrain',
  remoteness: 'Remoteness',
  weather: 'Weather',
  bailout: 'Exit Route',
  collaborative: 'Community',
};


/** Dismissal suppression duration (ms) — 12 minutes */
export const DISMISSAL_SUPPRESSION_MS = 12 * 60 * 1000;

