/**
 * ECS CAMPSITE CANDIDATE ENGINE — Predictive Campsite Detection

 * ============================================================================================
 *
 * Phase 1: Scans the currently loaded expedition route and identifies candidate
 * campsite zones using route segment data already generated by ECS.
 *
 * Phase 2: Scores campsite candidates using route timing, remoteness, and terrain
 * quality. Ranks candidates so ECS can suggest the best likely camp zones.
 *
 * Phase 3 Refinement: Smart Timing and Route-Day Filtering
 *   - Ideal camp timing window scoring (+4/+2/-3)
 *   - Too early in route penalty (-4)
 *   - Too late / too close to destination penalty (-4)
 *   - Route-length awareness (short routes < 60 mi suppress or reduce)
 *   - Overnight likelihood check (< 4.5 hrs drive → reduce scores)
 *   - Confidence field (LOW / MEDIUM / HIGH) per candidate
 *   - Forecast brief integration: only mention camps when confidence is HIGH
 *
 * DETECTION RULES (Phase 1):
 *   A. Flat or relatively stable terrain — elevationGain <= 150 ft per segment
 *   B. Not flagged as STEEP_GRADE or MOUNTAIN_PASS by Terrain Analysis
 *   C. Not in the first 20% of route distance (too close to departure)
 *   D. Not in the final 10% of route distance (too close to destination)
 *
 * SCORING RULES (Phase 2 + Phase 3 Refinement):
 *   - Flat terrain bonus: <= 100 ft → +3, <= 150 ft → +2
 *   - Remoteness bonus: high → +3, medium → +2, low → +0
 *   - Ideal camp timing window: 6–10 hrs → +4, 4–12 hrs → +2, else → -3
 *   - Terrain penalty: high elevation nearby → -2
 *   - Mountain pass proximity: within 1 segment → -3
 *   - Too early in route (< 35% distance) → -4
 *   - Too close to destination (> 90% distance) → -4
 *   - Short route (< 60 mi) → suppress or LOW confidence only
 *   - Quick trip (< 4.5 hrs) → reduce all scores by -3
 *
 * CONFIDENCE LEVELS:
 *   HIGH   = strong timing + strong terrain/remoteness score
 *   MEDIUM = reasonable timing or moderate score
 *   LOW    = short route, poor timing, or borderline conditions
 *
 * SUITABILITY LEVELS:
 *   0–2  = LOW
 *   3–6  = MEDIUM
 *   7+   = HIGH
 *
 * OUTPUTS:
 *   - CampsiteCandidate[] with scores, levels, confidence, and arrival estimates
 *   - Top 3 suggestedCampsites stored in state
 *   - Feeds map markers and forecast suggestions
 *
 * ARCHITECTURE:
 *   - Pure analysis functions (no side effects)
 *   - Subscriber pattern for UI updates
 *   - Stores locally (localStorage/memory)
 *   - Integrates with routeAnalysisEngine (Phase 1) and terrainAnalysisEngine (Phase 3)
 */

import { Platform } from 'react-native';
import type { RouteAnalysisSegment, RouteIntelligence } from './routeAnalysisEngine';
import type { TerrainIntelligence, TerrainWarningType } from './terrainAnalysisEngine';

const TAG = '[CAMPSITE_CANDIDATE]';

// ── Types ────────────────────────────────────────────────────

/**
 * Suitability level for a campsite candidate (Phase 2).
 */
export type SuitabilityLevel = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Confidence level for a campsite suggestion (Phase 3 Refinement).
 *
 * HIGH   = strong timing + strong terrain/remoteness score
 * MEDIUM = reasonable timing or moderate score
 * LOW    = short route, poor timing, or borderline conditions
 */
export type ConfidenceLevel = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Remoteness data snapshot for campsite scoring (Phase 2).
 */
export interface RemotenessSnapshot {
  /** Remoteness tier from remotenessStore */
  tier?: string | null;
  /** Remoteness score 0–100 */
  score?: number | null;
}

/**
 * A candidate campsite location inferred from route segment data.
 */
export interface CampsiteCandidate {
  /** Index of the route segment where this candidate was detected */
  segmentIndex: number;
  /** Representative coordinate for this candidate [lat, lon] */
  coordinates: [number, number];
  /** Distance from route start to segment midpoint (miles) */
  distanceMiles: number;
  /** Average elevation at this segment (feet) */
  avgElevation: number;
  /** Elevation gain within this segment (feet) */
  elevationGain: number;
  /** Human-readable reasons why this segment qualifies as a candidate */
  candidateReason: string[];
  /** Segment distance range label (e.g., "60–70 mi") */
  segmentRange: string;
  /** Terrain difficulty of this segment */
  difficulty: 'easy' | 'moderate' | 'challenging' | 'difficult';
  /** Candidate quality score from Phase 1 (higher = better, 0–100) */
  qualityScore: number;

  // ── Phase 2: Suitability Scoring ──

  /** Suitability score from Phase 2 scoring engine (0–15+ range) */
  suitabilityScore: number;
  /** Suitability level derived from score */
  suitabilityLevel: SuitabilityLevel;
  /** Estimated arrival hour from departure (null if not computable) */
  estimatedArrivalHour: number | null;
  /** Scoring breakdown for debug/display */
  scoringBreakdown: ScoringBreakdown;

  // ── Phase 3 Refinement: Confidence ──

  /** Confidence level reflecting timing and route-day plausibility */
  confidence: ConfidenceLevel;
  /** Human-readable confidence reasons (e.g., "Short route may not require overnight camp") */
  confidenceReasons: string[];
}

/**
 * Detailed scoring breakdown for transparency.
 */
export interface ScoringBreakdown {
  flatTerrainBonus: number;
  remotenessBonus: number;
  timingBonus: number;
  elevationPenalty: number;
  mountainPassPenalty: number;

  // ── Phase 3 Refinement additions ──

  /** Ideal camp timing window bonus/penalty (Phase 3) */
  idealTimingBonus: number;
  /** Too early in route penalty (Phase 3) */
  tooEarlyPenalty: number;
  /** Too close to destination penalty (Phase 3) */
  tooLatePenalty: number;
  /** Short route reduction (Phase 3) */
  shortRouteReduction: number;
  /** Overnight likelihood reduction (Phase 3) */
  overnightReduction: number;

  /** Human-readable scoring reasons */
  reasons: string[];
}

/**
 * Complete campsite candidate analysis result.
 */
export interface CampsiteCandidateResult {
  /** Unique analysis ID */
  id: string;
  /** Source route intelligence ID */
  routeIntelligenceId: string;
  /** Source route name */
  routeName: string;
  /** Total route distance (miles) */
  totalDistanceMiles: number;
  /** Estimated total drive time (hours) */
  estimatedDriveTimeHours: number;
  /** All detected campsite candidates (sorted by suitabilityScore desc) */
  candidates: CampsiteCandidate[];
  /** Top 3 suggested campsites (highest suitability) */
  suggestedCampsites: CampsiteCandidate[];
  /** Number of candidates found */
  candidateCount: number;
  /** Total segments analyzed */
  totalSegments: number;
  /** Segments excluded (too early, too late, steep, pass) */
  excludedSegments: number;
  /** Analysis timestamp */
  analyzedAt: string;
  /** Whether Phase 2 scoring was applied */
  scoringApplied: boolean;

  // ── Phase 3 Refinement metadata ──

  /** Whether the route is considered short (< 60 mi) */
  isShortRoute: boolean;
  /** Whether overnight stop is considered unlikely (< 4.5 hrs drive) */
  overnightUnlikely: boolean;
  /** Whether any suggestion has HIGH confidence */
  hasHighConfidence: boolean;
  /** Best confidence level among suggested campsites */
  bestConfidence: ConfidenceLevel | null;
}
// ── Constants ────────────────────────────────────────────────

/** Maximum elevation gain (ft) per segment for campsite candidacy */
const MAX_ELEVATION_GAIN_FT = 150;

/** Minimum route distance percentage to skip from start (20%) */
const ROUTE_START_EXCLUSION = 0.20;

/** Minimum route distance percentage to skip from end (10%) */
const ROUTE_END_EXCLUSION = 0.10;

/** Storage key for persistence */
const STORAGE_KEY = 'ecs_campsite_candidates';

/** Storage key for suggested campsites */
const SUGGESTED_STORAGE_KEY = 'ecs_suggested_campsites';

/** Terrain warning types that disqualify a segment */
const DISQUALIFYING_WARNINGS: TerrainWarningType[] = ['STEEP_GRADE', 'MOUNTAIN_PASS'];

/** Maximum number of suggested campsites to keep */
const MAX_SUGGESTED = 3;

/** Stabilization: Maximum number of candidates before scoring (prevents runaway lists) */
const MAX_CANDIDATES_BEFORE_SCORING = 20;

/** Stabilization: Minimum segment spacing between candidates (skip every N segments) */
const MIN_CANDIDATE_SEGMENT_SPACING = 2;

/** Stabilization: Minimum distance between candidates in miles */
const MIN_CANDIDATE_DISTANCE_MI = 8;


// ── Phase 3 Refinement Constants ─────────────────────────────

/** Short route threshold (miles) — below this, suppress or reduce suggestions */
const SHORT_ROUTE_THRESHOLD_MI = 60;

/** Quick trip threshold (hours) — below this, overnight stop unlikely */
const QUICK_TRIP_THRESHOLD_HRS = 4.5;

/** Too early in route threshold (% of total distance) */
const TOO_EARLY_THRESHOLD = 0.35;

/** Too close to destination threshold (% of total distance) */
const TOO_LATE_THRESHOLD = 0.90;

/** Ideal camp timing window — preferred (hours from departure) */
const IDEAL_TIMING_MIN_HRS = 6;
const IDEAL_TIMING_MAX_HRS = 10;

/** Ideal camp timing window — acceptable (hours from departure) */
const ACCEPTABLE_TIMING_MIN_HRS = 4;
const ACCEPTABLE_TIMING_MAX_HRS = 12;

// ── Suitability Thresholds ───────────────────────────────────

function classifySuitability(score: number): SuitabilityLevel {
  if (score >= 7) return 'HIGH';
  if (score >= 3) return 'MEDIUM';
  return 'LOW';
}

// ── Confidence Classification (Phase 3) ──────────────────────

/**
 * Classify confidence based on timing, suitability, and route context.
 *
 * HIGH   = strong timing + strong terrain/remoteness score
 * MEDIUM = reasonable timing or moderate score
 * LOW    = short route, poor timing, or borderline conditions
 */
function classifyConfidence(
  suitabilityScore: number,
  estimatedArrivalHour: number | null,
  isShortRoute: boolean,
  overnightUnlikely: boolean,
  tooEarly: boolean,
  tooLate: boolean,
): { confidence: ConfidenceLevel; reasons: string[] } {
  const reasons: string[] = [];
  let confidenceScore = 0;

  // ── Short route → LOW confidence ──
  if (isShortRoute) {
    reasons.push('Short route may not require overnight camp');
    return { confidence: 'LOW', reasons };
  }

  // ── Overnight unlikely → LOW confidence unless remoteness is very high ──
  if (overnightUnlikely) {
    reasons.push('Quick trip — overnight stop unlikely');
    if (suitabilityScore >= 7) {
      // High suitability can override overnight concern (remote area)
      reasons.push('High suitability in remote area overrides quick trip concern');
      return { confidence: 'MEDIUM', reasons };
    }
    return { confidence: 'LOW', reasons };
  }

  // ── Too early or too late → reduce confidence ──
  if (tooEarly) {
    reasons.push('Too early in route for likely camp stop');
    confidenceScore -= 2;
  }
  if (tooLate) {
    reasons.push('Too close to destination for likely camp stop');
    confidenceScore -= 2;
  }

  // ── Timing quality ──
  if (estimatedArrivalHour != null) {
    if (estimatedArrivalHour >= IDEAL_TIMING_MIN_HRS && estimatedArrivalHour <= IDEAL_TIMING_MAX_HRS) {
      confidenceScore += 3;
    } else if (estimatedArrivalHour >= ACCEPTABLE_TIMING_MIN_HRS && estimatedArrivalHour <= ACCEPTABLE_TIMING_MAX_HRS) {
      confidenceScore += 1;
    } else {
      confidenceScore -= 1;
    }
  }

  // ── Suitability quality ──
  if (suitabilityScore >= 7) {
    confidenceScore += 3;
  } else if (suitabilityScore >= 4) {
    confidenceScore += 1;
  } else {
    confidenceScore -= 1;
  }

  // ── Classify ──
  if (confidenceScore >= 4) {
    return { confidence: 'HIGH', reasons };
  }
  if (confidenceScore >= 1) {
    return { confidence: 'MEDIUM', reasons };
  }
  if (reasons.length === 0) {
    reasons.push('Borderline conditions');
  }
  return { confidence: 'LOW', reasons };
}

// ── Storage Helpers ──────────────────────────────────────────

const mem: Record<string, string> = {};

function sGet(key: string): string | null {
  try {
    if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
      return localStorage.getItem(key);
    }
    return mem[key] || null;
  } catch { return mem[key] || null; }
}

function sSet(key: string, value: string): void {
  try {
    if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
      localStorage.setItem(key, value);
    }
    mem[key] = value;
  } catch { mem[key] = value; }
}

function uuid(): string {
  const c: any = typeof crypto !== 'undefined' ? crypto : null;
  if (c && c.randomUUID) return c.randomUUID();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (ch) => {
    const r = (Math.random() * 16) | 0;
    return (ch === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

// ── Core Analysis Function (Phase 1) ─────────────────────────

/**
 * Find campsite candidates by analyzing route segments and terrain intelligence.
 *
 * A segment becomes a campsite candidate when ALL of the following are true:
 *   A. Flat or relatively stable terrain (elevationGain <= 150 ft)
 *   B. Not flagged as STEEP_GRADE or MOUNTAIN_PASS by Terrain Analysis
 *   C. Not in the first 20% of route distance
 *   D. Not in the final 10% of route distance
 *
 * @param routeSegments - Phase 1 RouteAnalysisSegment[] from route analysis
 * @param terrainIntel - Phase 3 TerrainIntelligence (optional, for warning exclusion)
 * @param totalDistanceMiles - Total route distance in miles
 * @returns CampsiteCandidate[] of qualifying segments (Phase 1 only, no scoring)
 */
export function findCampsiteCandidates(
  routeSegments: RouteAnalysisSegment[],
  terrainIntel: TerrainIntelligence | null,
  totalDistanceMiles: number,
): CampsiteCandidate[] {
  if (!routeSegments || routeSegments.length === 0 || totalDistanceMiles <= 0) {
    return [];
  }

  // ── Stabilization: Guard against NaN/Infinity distance ──
  if (!isFinite(totalDistanceMiles)) {
    console.warn(TAG, 'Total distance is not finite — returning empty candidates');
    return [];
  }

  // ── Build set of segment indices with disqualifying terrain warnings ──
  const disqualifiedSegments = new Set<number>();

  if (terrainIntel && terrainIntel.terrainWarnings && terrainIntel.terrainWarnings.length > 0) {
    for (const warning of terrainIntel.terrainWarnings) {
      if (DISQUALIFYING_WARNINGS.includes(warning.warningType)) {
        disqualifiedSegments.add(warning.segmentIndex);
      }
    }
  }

  // ── Compute distance exclusion thresholds ──
  const startExclusionMiles = totalDistanceMiles * ROUTE_START_EXCLUSION;
  const endExclusionMiles = totalDistanceMiles * (1 - ROUTE_END_EXCLUSION);

  const candidates: CampsiteCandidate[] = [];

  // ── Stabilization: Track last accepted candidate distance for spacing ──
  let lastAcceptedDistanceMi = -Infinity;
  // ── Stabilization: Track accepted segment indices to prevent duplicates ──
  const acceptedSegmentIndices = new Set<number>();
  // ── Stabilization: Track accepted coordinate keys to prevent near-duplicates ──
  const acceptedCoordKeys = new Set<string>();

  // ── Loop through all segments and apply candidacy rules ──
  for (const seg of routeSegments) {
    const reasons: string[] = [];
    let qualityScore = 50; // Base score

    // ── Stabilization: Validate segment data ──
    if (seg.segmentIndex == null || !seg.coordinates || seg.coordinates.length < 2) {
      continue; // Skip malformed segments
    }

    // Compute segment midpoint distance
    const segMidpointMiles = (seg.distanceStart + seg.distanceEnd) / 2;

    // ── Stabilization: Validate midpoint distance ──
    if (!isFinite(segMidpointMiles)) continue;

    // ── Rule C: Not too early in the route (first 20%) ──
    if (segMidpointMiles < startExclusionMiles) {
      continue; // Skip — too close to departure
    }

    // ── Rule D: Not too close to the end (final 10%) ──
    if (segMidpointMiles > endExclusionMiles) {
      continue; // Skip — too close to destination
    }

    // ── Rule B: Not flagged as steep terrain or mountain pass ──
    if (disqualifiedSegments.has(seg.segmentIndex)) {
      continue; // Skip — terrain analysis flagged this segment
    }

    // ── Rule A: Flat or relatively stable terrain ──
    if (seg.elevationGain > MAX_ELEVATION_GAIN_FT) {
      continue; // Skip — too much elevation change
    }

    // ── Stabilization: Prevent duplicate segment indices ──
    if (acceptedSegmentIndices.has(seg.segmentIndex)) {
      continue;
    }

    // ── Stabilization: Prevent candidates at identical/near-identical coordinates ──
    const coordKey = `${seg.coordinates[0].toFixed(3)},${seg.coordinates[1].toFixed(3)}`;
    if (acceptedCoordKeys.has(coordKey)) {
      continue;
    }

    // ── Stabilization: Enforce minimum distance spacing between candidates ──
    if (segMidpointMiles - lastAcceptedDistanceMi < MIN_CANDIDATE_DISTANCE_MI) {
      continue; // Skip — too close to last accepted candidate
    }

    // ── All rules passed — this is a campsite candidate ──

    // Build candidate reasons
    reasons.push('Low elevation change');

    // Mid-route location bonus
    const routeProgress = segMidpointMiles / totalDistanceMiles;
    if (routeProgress >= 0.35 && routeProgress <= 0.65) {
      reasons.push('Mid-route location');
      qualityScore += 15; // Bonus for being in the middle third
    }

    // Outside steep terrain zones
    if (terrainIntel && terrainIntel.steepSegments > 0) {
      reasons.push('Outside steep terrain zones');
      qualityScore += 10;
    }

    // Easy terrain bonus
    if (seg.difficulty === 'easy') {
      reasons.push('Easy terrain classification');
      qualityScore += 10;
    } else if (seg.difficulty === 'moderate') {
      reasons.push('Moderate terrain classification');
      qualityScore += 5;
    }

    // Very flat terrain bonus (< 50 ft gain)
    if (seg.elevationGain < 50) {
      reasons.push('Very flat terrain');
      qualityScore += 15;
    } else if (seg.elevationGain < 100) {
      reasons.push('Relatively flat terrain');
      qualityScore += 5;
    }

    // Low grade bonus
    if (seg.avgGradePercent < 2) {
      reasons.push('Low average grade');
      qualityScore += 5;
    }

    // Moderate elevation preference (not too high, not too low)
    if (seg.avgElevation >= 3000 && seg.avgElevation <= 8000) {
      qualityScore += 5;
    }

    // Cap quality score at 100
    qualityScore = Math.min(100, Math.max(0, qualityScore));

    const rangeLabel = `${seg.distanceStart.toFixed(0)}–${seg.distanceEnd.toFixed(0)} mi`;

    candidates.push({
      segmentIndex: seg.segmentIndex,
      coordinates: seg.coordinates,
      distanceMiles: Math.round(segMidpointMiles * 10) / 10,
      avgElevation: seg.avgElevation,
      elevationGain: seg.elevationGain,
      candidateReason: reasons,
      segmentRange: rangeLabel,
      difficulty: seg.difficulty,
      qualityScore,
      // Phase 2 defaults (will be overwritten by scoring)
      suitabilityScore: 0,
      suitabilityLevel: 'LOW',
      estimatedArrivalHour: null,
      scoringBreakdown: {
        flatTerrainBonus: 0,
        remotenessBonus: 0,
        timingBonus: 0,
        elevationPenalty: 0,
        mountainPassPenalty: 0,
        idealTimingBonus: 0,
        tooEarlyPenalty: 0,
        tooLatePenalty: 0,
        shortRouteReduction: 0,
        overnightReduction: 0,
        reasons: [],
      },
      // Phase 3 defaults
      confidence: 'LOW',
      confidenceReasons: [],
    });

    // ── Stabilization: Track accepted candidate for dedup/spacing ──
    lastAcceptedDistanceMi = segMidpointMiles;
    acceptedSegmentIndices.add(seg.segmentIndex);
    acceptedCoordKeys.add(coordKey);

    if (candidates.length >= MAX_CANDIDATES_BEFORE_SCORING) {
      break;
    }
  }

  candidates.sort((a, b) => b.qualityScore - a.qualityScore);

  return candidates;
}



// ══════════════════════════════════════════════════════════════
// PHASE 2 + PHASE 3 REFINEMENT: CAMPSITE SUITABILITY SCORING ENGINE
// ══════════════════════════════════════════════════════════════

/**
 * Score campsite candidates using route timing, remoteness, terrain quality,
 * and Phase 3 smart timing / route-day filtering.
 *
 * SCORING RULES (Phase 2):
 *   Flat terrain bonus:
 *     <= 100 ft → +3
 *     <= 150 ft → +2
 *
 *   Remoteness bonus:
 *     high remoteness → +3
 *     medium remoteness → +2
 *     low remoteness → +0
 *
 *   Terrain penalty:
 *     high elevation nearby → -2
 *
 *   Mountain pass proximity penalty:
 *     within 1 segment of a mountain pass warning → -3
 *
 * SCORING RULES (Phase 3 Refinement):
 *   Ideal camp timing window:
 *     6–10 hrs from departure → +4
 *     4–12 hrs from departure → +2
 *     < 4 hrs or > 12 hrs → -3
 *
 *   Too early in route (< 35% distance) → -4
 *   Too close to destination (> 90% distance) → -4
 *   Short route (< 60 mi) → all scores reduced by -3
 *   Quick trip (< 4.5 hrs drive) → all scores reduced by -3
 *
 * @param candidates - Phase 1 CampsiteCandidate[]
 * @param routeIntel - Phase 1 RouteIntelligence
 * @param terrainIntel - Phase 3 TerrainIntelligence
 * @param remotenessData - Optional remoteness snapshot
 * @returns CampsiteCandidate[] scored and sorted highest first
 */
export function scoreCampsiteCandidates(
  candidates: CampsiteCandidate[],
  routeIntel: RouteIntelligence,
  terrainIntel: TerrainIntelligence | null,
  remotenessData?: RemotenessSnapshot | null,
): CampsiteCandidate[] {
  if (!candidates || candidates.length === 0) return [];

  // ── Stabilization: Guard against null/undefined routeIntel ──
  if (!routeIntel) {
    console.warn(TAG, 'scoreCampsiteCandidates called with null routeIntel — returning unscored candidates');
    return candidates;
  }

  const totalDistanceMiles = routeIntel.totalDistanceMiles ?? 0;
  const estimatedDriveTimeHours = routeIntel.estimatedDriveTimeHours ?? 0;

  // ── Phase 3: Route-level context flags ──
  const isShortRoute = totalDistanceMiles < SHORT_ROUTE_THRESHOLD_MI;
  const overnightUnlikely = estimatedDriveTimeHours < QUICK_TRIP_THRESHOLD_HRS;

  // ── Build mountain pass segment index set (for proximity penalty) ──
  const mountainPassSegments = new Set<number>();
  if (terrainIntel) {
    for (const warning of terrainIntel.terrainWarnings) {
      if (warning.warningType === 'MOUNTAIN_PASS') {
        mountainPassSegments.add(warning.segmentIndex);
      }
    }
  }

  // ── Build high elevation segment index set (for elevation penalty) ──
  const highElevationSegments = new Set<number>();
  if (terrainIntel) {
    for (const warning of terrainIntel.terrainWarnings) {
      if (warning.warningType === 'HIGH_ELEVATION') {
        highElevationSegments.add(warning.segmentIndex);
      }
    }
  }

  // ── Resolve remoteness level ──
  let remotenessLevel: 'high' | 'medium' | 'low' = 'low';
  if (remotenessData) {
    if (remotenessData.tier) {
      const tier = remotenessData.tier.toUpperCase();
      if (tier === 'EXTREME' || tier === 'DEEP REMOTE' || tier === 'REMOTE') {
        remotenessLevel = 'high';
      } else if (tier === 'BACKCOUNTRY') {
        remotenessLevel = 'medium';
      }
    } else if (remotenessData.score != null) {
      if (remotenessData.score >= 36) remotenessLevel = 'high';
      else if (remotenessData.score >= 16) remotenessLevel = 'medium';
    }
  }

  // ── Score each candidate ──
  const scoredCandidates: CampsiteCandidate[] = candidates.map(candidate => {
    let score = 0;
    const breakdownReasons: string[] = [];

    // ── Arrival Time Estimation ──
    let estimatedArrivalHour: number | null = null;
    if (totalDistanceMiles > 0 && estimatedDriveTimeHours > 0) {
      const candidateProgress = candidate.distanceMiles / totalDistanceMiles;
      estimatedArrivalHour = Math.round(estimatedDriveTimeHours * candidateProgress * 10) / 10;
    }

    // ── Route progress for Phase 3 checks ──
    const routeProgress = totalDistanceMiles > 0
      ? candidate.distanceMiles / totalDistanceMiles
      : 0;
    const tooEarly = routeProgress < TOO_EARLY_THRESHOLD;
    const tooLate = routeProgress > TOO_LATE_THRESHOLD;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 1: Flat terrain bonus (Phase 2)
    // ══════════════════════════════════════════════════════════
    let flatTerrainBonus = 0;
    if (candidate.elevationGain <= 100) {
      flatTerrainBonus = 3;
      breakdownReasons.push('Flat terrain (+3)');
    } else if (candidate.elevationGain <= 150) {
      flatTerrainBonus = 2;
      breakdownReasons.push('Stable terrain (+2)');
    }
    score += flatTerrainBonus;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 2: Remoteness bonus (Phase 2)
    // ══════════════════════════════════════════════════════════
    let remotenessBonus = 0;
    if (remotenessLevel === 'high') {
      remotenessBonus = 3;
      breakdownReasons.push('Remote location (+3)');
    } else if (remotenessLevel === 'medium') {
      remotenessBonus = 2;
      breakdownReasons.push('Backcountry location (+2)');
    }
    score += remotenessBonus;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 3: Ideal camp timing window (Phase 3 — replaces Phase 2 timing)
    // ══════════════════════════════════════════════════════════
    let idealTimingBonus = 0;
    let timingBonus = 0; // Legacy Phase 2 field — kept for backward compat
    if (estimatedArrivalHour != null) {
      if (estimatedArrivalHour >= IDEAL_TIMING_MIN_HRS && estimatedArrivalHour <= IDEAL_TIMING_MAX_HRS) {
        // Preferred window: 6–10 hours from departure
        idealTimingBonus = 4;
        timingBonus = 4;
        breakdownReasons.push('Ideal camp timing window (+4)');
      } else if (estimatedArrivalHour >= ACCEPTABLE_TIMING_MIN_HRS && estimatedArrivalHour <= ACCEPTABLE_TIMING_MAX_HRS) {
        // Acceptable window: 4–12 hours from departure
        idealTimingBonus = 2;
        timingBonus = 2;
        breakdownReasons.push('Acceptable camp timing (+2)');
      } else {
        // Poor timing: < 4 hrs or > 12 hrs
        idealTimingBonus = -3;
        timingBonus = -3;
        breakdownReasons.push('Poor camp timing (-3)');
      }
    }
    score += idealTimingBonus;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 4: Terrain penalty — high elevation nearby (Phase 2)
    // ══════════════════════════════════════════════════════════
    let elevationPenalty = 0;
    // Check if this segment or adjacent segments are high elevation
    const adjRange = [candidate.segmentIndex - 1, candidate.segmentIndex, candidate.segmentIndex + 1];
    const nearHighElevation = adjRange.some(idx => highElevationSegments.has(idx));
    if (nearHighElevation) {
      elevationPenalty = -2;
      breakdownReasons.push('High elevation nearby (-2)');
    }
    score += elevationPenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 5: Mountain pass proximity penalty (Phase 2)
    // ══════════════════════════════════════════════════════════
    let mountainPassPenalty = 0;
    // Check if within 1 segment of a mountain pass warning
    const passRange = [
      candidate.segmentIndex - 1,
      candidate.segmentIndex,
      candidate.segmentIndex + 1,
    ];
    const nearMountainPass = passRange.some(idx => mountainPassSegments.has(idx));
    if (nearMountainPass) {
      mountainPassPenalty = -3;
      breakdownReasons.push('Near mountain pass (-3)');
    }
    score += mountainPassPenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 6: Too early in route penalty (Phase 3)
    // ══════════════════════════════════════════════════════════
    let tooEarlyPenalty = 0;
    if (tooEarly) {
      tooEarlyPenalty = -4;
      breakdownReasons.push('Too early in route (-4)');
    }
    score += tooEarlyPenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 7: Too close to destination penalty (Phase 3)
    // ══════════════════════════════════════════════════════════
    let tooLatePenalty = 0;
    if (tooLate) {
      tooLatePenalty = -4;
      breakdownReasons.push('Too close to destination (-4)');
    }
    score += tooLatePenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 8: Short route reduction (Phase 3)
    // ══════════════════════════════════════════════════════════
    let shortRouteReduction = 0;
    if (isShortRoute) {
      shortRouteReduction = -3;
      breakdownReasons.push('Short route reduction (-3)');
    }
    score += shortRouteReduction;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 9: Overnight likelihood reduction (Phase 3)
    // ══════════════════════════════════════════════════════════
    let overnightReduction = 0;
    if (overnightUnlikely) {
      // Only apply if remoteness is not very high (remote areas may still need camp)
      if (remotenessLevel !== 'high') {
        overnightReduction = -3;
        breakdownReasons.push('Quick trip — overnight unlikely (-3)');
      }
    }
    score += overnightReduction;

    // ── Clamp score to minimum 0 ──
    score = Math.max(0, score);

    // ── Classify suitability level ──
    const suitabilityLevel = classifySuitability(score);

    // ── Classify confidence (Phase 3) ──
    const { confidence, reasons: confidenceReasons } = classifyConfidence(
      score,
      estimatedArrivalHour,
      isShortRoute,
      overnightUnlikely,
      tooEarly,
      tooLate,
    );

    // ── Build scoring breakdown ──
    const scoringBreakdown: ScoringBreakdown = {
      flatTerrainBonus,
      remotenessBonus,
      timingBonus,
      elevationPenalty,
      mountainPassPenalty,
      idealTimingBonus,
      tooEarlyPenalty,
      tooLatePenalty,
      shortRouteReduction,
      overnightReduction,
      reasons: breakdownReasons,
    };

    return {
      ...candidate,
      suitabilityScore: score,
      suitabilityLevel,
      estimatedArrivalHour,
      scoringBreakdown,
      confidence,
      confidenceReasons,
    };
  });

  // ── Sort by suitability score (highest first), then by quality score as tiebreaker ──
  scoredCandidates.sort((a, b) => {
    if (b.suitabilityScore !== a.suitabilityScore) {
      return b.suitabilityScore - a.suitabilityScore;
    }
    return b.qualityScore - a.qualityScore;
  });




  return scoredCandidates;
}

// ── Full Analysis Function ───────────────────────────────────

/**
 * Run complete campsite candidate analysis from RouteIntelligence and TerrainIntelligence.
 * Includes Phase 2 suitability scoring and Phase 3 smart timing refinement.
 *
 * @param routeIntel - Phase 1 RouteIntelligence
 * @param terrainIntel - Phase 3 TerrainIntelligence (optional)
 * @param remotenessData - Optional remoteness snapshot for scoring
 * @returns CampsiteCandidateResult
 */
export function analyzeCampsiteCandidates(
  routeIntel: RouteIntelligence,
  terrainIntel: TerrainIntelligence | null,
  remotenessData?: RemotenessSnapshot | null,
): CampsiteCandidateResult {
  const now = new Date().toISOString();

  // ── Stabilization: Guard against null/undefined routeIntel ──
  if (!routeIntel) {
    console.warn(TAG, 'analyzeCampsiteCandidates called with null routeIntel — returning empty result');
    return {
      id: uuid(),
      routeIntelligenceId: 'unknown',
      routeName: 'Unknown Route',
      totalDistanceMiles: 0,
      estimatedDriveTimeHours: 0,
      candidates: [],
      suggestedCampsites: [],
      candidateCount: 0,
      totalSegments: 0,
      excludedSegments: 0,
      analyzedAt: now,
      scoringApplied: false,
      isShortRoute: true,
      overnightUnlikely: true,
      hasHighConfidence: false,
      bestConfidence: null,
    };
  }

  // ── Stabilization: Safe access to route properties ──
  const totalDistanceMiles = routeIntel.totalDistanceMiles ?? 0;
  const estimatedDriveTimeHours = routeIntel.estimatedDriveTimeHours ?? 0;

  const isShortRoute = totalDistanceMiles < SHORT_ROUTE_THRESHOLD_MI;
  const overnightUnlikely = estimatedDriveTimeHours < QUICK_TRIP_THRESHOLD_HRS;

  if (!routeIntel.segments || routeIntel.segments.length === 0) {
    console.warn(TAG, 'analyzeCampsiteCandidates: no segments — returning empty result');
    return {
      id: uuid(),
      routeIntelligenceId: routeIntel.id,
      routeName: routeIntel.routeName,
      totalDistanceMiles: totalDistanceMiles,
      estimatedDriveTimeHours: estimatedDriveTimeHours,
      candidates: [],
      suggestedCampsites: [],
      candidateCount: 0,
      totalSegments: 0,
      excludedSegments: 0,
      analyzedAt: now,
      scoringApplied: false,
      isShortRoute,
      overnightUnlikely,
      hasHighConfidence: false,
      bestConfidence: null,
    };
  }


  // Phase 1: Find candidates
  const rawCandidates = findCampsiteCandidates(
    routeIntel.segments,
    terrainIntel,
    routeIntel.totalDistanceMiles,
  );

  // Phase 2 + Phase 3: Score candidates with smart timing
  const scoredCandidates = scoreCampsiteCandidates(
    rawCandidates,
    routeIntel,
    terrainIntel,
    remotenessData,
  );

  // ── Phase 3: Filter suggested campsites based on route context ──
  let suggestedCampsites: CampsiteCandidate[];

  if (isShortRoute) {
    // Short routes: only allow LOW confidence suggestions
    suggestedCampsites = scoredCandidates
      .filter(c => c.confidence === 'LOW')
      .slice(0, MAX_SUGGESTED);
  } else {
    // Normal routes: take top 3
    suggestedCampsites = scoredCandidates.slice(0, MAX_SUGGESTED);
  }

  const excludedSegments = routeIntel.segments.length - scoredCandidates.length;

  // ── Phase 3: Compute confidence metadata ──
  const hasHighConfidence = suggestedCampsites.some(c => c.confidence === 'HIGH');
  const bestConfidence: ConfidenceLevel | null = suggestedCampsites.length > 0
    ? suggestedCampsites.reduce<ConfidenceLevel>((best, c) => {
        const order: Record<ConfidenceLevel, number> = { LOW: 0, MEDIUM: 1, HIGH: 2 };
        return order[c.confidence] > order[best] ? c.confidence : best;
      }, 'LOW')
    : null;

  const result: CampsiteCandidateResult = {
    id: uuid(),
    routeIntelligenceId: routeIntel.id,
    routeName: routeIntel.routeName,
    totalDistanceMiles: routeIntel.totalDistanceMiles,
    estimatedDriveTimeHours: routeIntel.estimatedDriveTimeHours,
    candidates: scoredCandidates,
    suggestedCampsites,
    candidateCount: scoredCandidates.length,
    totalSegments: routeIntel.segments.length,
    excludedSegments,
    analyzedAt: now,
    scoringApplied: true,
    isShortRoute,
    overnightUnlikely,
    hasHighConfidence,
    bestConfidence,
  };

  return result;
}


// ── Listeners ────────────────────────────────────────────────

type CampsiteListener = (result: CampsiteCandidateResult | null) => void;
const _listeners = new Set<CampsiteListener>();

function _notify(result: CampsiteCandidateResult | null) {
  _listeners.forEach(fn => {
    try { fn(result); } catch (e) { console.error(TAG, 'Listener error:', e); }
  });
}

// ── Internal State ───────────────────────────────────────────

let _currentResult: CampsiteCandidateResult | null = null;

// ── Persistence ──────────────────────────────────────────────

function loadStoredResult(): CampsiteCandidateResult | null {
  try {
    const raw = sGet(STORAGE_KEY);
    if (!raw) return null;
    return JSON.parse(raw);
  } catch { return null; }
}

function saveResult(result: CampsiteCandidateResult): void {
  try {
    sSet(STORAGE_KEY, JSON.stringify(result));
  } catch (e) {
    console.warn(TAG, 'Failed to save campsite candidates:', e);
  }
}

function clearStoredResult(): void {
  try {
    if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
      localStorage.removeItem(STORAGE_KEY);
      localStorage.removeItem(SUGGESTED_STORAGE_KEY);
    }
    delete mem[STORAGE_KEY];
    delete mem[SUGGESTED_STORAGE_KEY];
  } catch {}
}

// ══════════════════════════════════════════════════════════════
// PUBLIC API — campsiteCandidateEngine
// ══════════════════════════════════════════════════════════════

export const campsiteCandidateEngine = {
  /**
   * Subscribe to campsite candidate changes.
   * Returns unsubscribe function.
   */
  subscribe(listener: CampsiteListener): () => void {
    _listeners.add(listener);
    return () => { _listeners.delete(listener); };
  },

  /**
   * Analyze route for campsite candidates with Phase 2+3 scoring.
   * Stores result and notifies listeners.
   */
  analyze(
    routeIntel: RouteIntelligence,
    terrainIntel: TerrainIntelligence | null,
    remotenessData?: RemotenessSnapshot | null,
  ): CampsiteCandidateResult {
    const result = analyzeCampsiteCandidates(routeIntel, terrainIntel, remotenessData);
    _currentResult = result;
    saveResult(result);
    _notify(result);
    return result;
  },

  /**
   * Get the current campsite candidate result (in-memory or from storage).
   */
  getCurrent(): CampsiteCandidateResult | null {
    if (_currentResult) return _currentResult;
    _currentResult = loadStoredResult();
    return _currentResult;
  },

  /**
   * Check if campsite analysis exists for a given route intelligence ID.
   */
  isCurrentFor(routeIntelligenceId: string): boolean {
    const current = this.getCurrent();
    return current != null && current.routeIntelligenceId === routeIntelligenceId;
  },

  /**
   * Check if analysis needs recomputation.
   * Returns true if no result exists or the route intelligence ID has changed.
   */
  needsRecompute(routeIntelligenceId: string): boolean {
    const current = this.getCurrent();
    if (!current) return true;
    return current.routeIntelligenceId !== routeIntelligenceId;
  },

  /**
   * Clear current campsite candidates.
   */
  clear(): void {
    _currentResult = null;
    clearStoredResult();
    _notify(null);
    console.log(TAG, 'Campsite candidates cleared');
  },


  /**
   * Get the top N candidates by suitability score (Phase 2).
   */
  getTopCandidates(n: number = MAX_SUGGESTED): CampsiteCandidate[] {
    const current = this.getCurrent();
    if (!current) return [];
    return current.suggestedCampsites.slice(0, n);
  },

  /**
   * Get suggested campsites (top 3).
   */
  getSuggestedCampsites(): CampsiteCandidate[] {
    const current = this.getCurrent();
    if (!current) return [];
    return current.suggestedCampsites;
  },

  /**
   * Check if any suggested campsite has HIGH confidence (Phase 3).
   * Used by Expedition Brief to decide whether to mention camp zones.
   */
  hasHighConfidenceSuggestion(): boolean {
    const current = this.getCurrent();
    if (!current) return false;
    return current.hasHighConfidence;
  },

  /**
   * Get the best confidence level among suggested campsites (Phase 3).
   */
  getBestConfidence(): ConfidenceLevel | null {
    const current = this.getCurrent();
    if (!current) return null;
    return current.bestConfidence;
  },

  /**
   * Check if the route is considered short (Phase 3).
   */
  isShortRoute(): boolean {
    const current = this.getCurrent();
    if (!current) return false;
    return current.isShortRoute;
  },

  /**
   * Check if overnight stop is unlikely (Phase 3).
   */
  isOvernightUnlikely(): boolean {
    const current = this.getCurrent();
    if (!current) return false;
    return current.overnightUnlikely;
  },

  /**
   * Format distance as human-readable string.
   */
  formatDistance(miles: number): string {
    return `Mile ${miles.toFixed(0)}`;
  },

  /**
   * Format elevation as human-readable string with commas.
   */
  formatElevation(feet: number): string {
    return feet.toLocaleString('en-US');
  },

  /**
   * Format arrival time as human-readable string.
   */
  formatArrivalTime(hours: number | null): string {
    if (hours == null) return '—';
    const h = Math.floor(hours);
    const m = Math.round((hours - h) * 60);
    if (h === 0) return `${m}m`;
    if (m === 0) return `${h}h`;
    return `${h}h ${m}m`;
  },

  /**
   * Get a compact summary string.
   */
  getSummary(result: CampsiteCandidateResult): string {
    if (result.candidateCount === 0) return 'No campsite candidates detected';

    // Phase 3: Include route context
    if (result.isShortRoute) {
      return `Short route — ${result.candidateCount} candidate${result.candidateCount > 1 ? 's' : ''} (low confidence)`;
    }
    if (result.overnightUnlikely) {
      return `Quick trip — ${result.candidateCount} candidate${result.candidateCount > 1 ? 's' : ''} (overnight unlikely)`;
    }

    const suggested = result.suggestedCampsites.length;
    if (suggested > 0) {
      const topLevel = result.suggestedCampsites[0].suitabilityLevel;
      const topConf = result.suggestedCampsites[0].confidence;
      return `${suggested} suggested campsite${suggested > 1 ? 's' : ''} (best: ${topLevel}, ${topConf} confidence)`;
    }
    return `${result.candidateCount} campsite candidate${result.candidateCount > 1 ? 's' : ''} detected`;
  },

  /**
   * Get suitability level metadata for display.
   */
  getSuitabilityMeta(level: SuitabilityLevel): { label: string; color: string; icon: string } {
    switch (level) {
      case 'HIGH':
        return { label: 'HIGH', color: '#66BB6A', icon: 'star' };
      case 'MEDIUM':
        return { label: 'MEDIUM', color: '#FFB74D', icon: 'star-half' };
      case 'LOW':
      default:
        return { label: 'LOW', color: '#8A8A85', icon: 'star-outline' };
    }
  },

  /**
   * Get confidence level metadata for display (Phase 3).
   */
  getConfidenceMeta(level: ConfidenceLevel): { label: string; color: string; icon: string } {
    switch (level) {
      case 'HIGH':
        return { label: 'HIGH', color: '#66BB6A', icon: 'shield-checkmark' };
      case 'MEDIUM':
        return { label: 'MEDIUM', color: '#FFB74D', icon: 'shield-half' };
      case 'LOW':
      default:
        return { label: 'LOW', color: '#8A8A85', icon: 'shield-outline' };
    }
  },

  /**
   * Generate a campsite brief sentence for the Expedition Brief (Phase 3).
   * Only returns a sentence if at least one suggestion has HIGH confidence.
   * Returns null if no high-confidence suggestions exist.
   */
  generateCampsiteBrief(): string | null {
    const current = this.getCurrent();
    if (!current) return null;
    if (!current.hasHighConfidence) return null;
    if (current.suggestedCampsites.length === 0) return null;

    const highConfCount = current.suggestedCampsites.filter(c => c.confidence === 'HIGH').length;

    if (highConfCount > 1) {
      return 'Likely camp zones appear along the mid-to-late route.';
    }
    return 'A likely camp zone appears along the route.';
  },
};

