/**
 * ECS CAMPSITE CANDIDATE ENGINE — Predictive Campsite Detection

 * ============================================================================================
 *
 * Phase 1: Scans the currently loaded expedition route and identifies candidate
 * campsite zones using route segment data already generated by ECS.
 *
 * Phase 2: Scores campsite candidates using route timing, remoteness, and terrain
 * quality. Ranks candidates so ECS can suggest the best likely camp zones.
 *
 * Phase 3 Refinement: Smart Timing and Route-Day Filtering
 *   - Ideal camp timing window scoring (+4/+2/-3)
 *   - Too early in route penalty (-4)
 *   - Too late / too close to destination penalty (-4)
 *   - Route-length awareness (short routes < 60 mi suppress or reduce)
 *   - Overnight likelihood check (< 4.5 hrs drive → reduce scores)
 *   - Confidence field (LOW / MEDIUM / HIGH) per candidate
 *   - Forecast brief integration: only mention camps when confidence is HIGH
 *
 * DETECTION RULES (Phase 1):
 *   A. Flat or relatively stable terrain — elevationGain <= 150 ft per segment
 *   B. Not flagged as STEEP_GRADE or MOUNTAIN_PASS by Terrain Analysis
 *   C. Not in the first 20% of route distance (too close to departure)
 *   D. Not in the final 10% of route distance (too close to destination)
 *
 * SCORING RULES (Phase 2 + Phase 3 Refinement):
 *   - Flat terrain bonus: <= 100 ft → +3, <= 150 ft → +2
 *   - Remoteness bonus: high → +3, medium → +2, low → +0
 *   - Ideal camp timing window: 6–10 hrs → +4, 4–12 hrs → +2, else → -3
 *   - Terrain penalty: high elevation nearby → -2
 *   - Mountain pass proximity: within 1 segment → -3
 *   - Too early in route (< 35% distance) → -4
 *   - Too close to destination (> 90% distance) → -4
 *   - Short route (< 60 mi) → suppress or LOW confidence only
 *   - Quick trip (< 4.5 hrs) → reduce all scores by -3
 *
 * CONFIDENCE LEVELS:
 *   HIGH   = strong timing + strong terrain/remoteness score
 *   MEDIUM = reasonable timing or moderate score
 *   LOW    = short route, poor timing, or borderline conditions
 *
 * SUITABILITY LEVELS:
 *   0–2  = LOW
 *   3–6  = MEDIUM
 *   7+   = HIGH
 *
 * OUTPUTS:
 *   - CampsiteCandidate[] with scores, levels, confidence, and arrival estimates
 *   - Suggested campsites stored in state, capped by MAX_CAMPSITE_MARKERS
 *   - Feeds map markers and forecast suggestions
 *
 * ARCHITECTURE:
 *   - Pure analysis functions (no side effects)
 *   - Subscriber pattern for UI updates
 *   - Stores locally (localStorage/memory)
 *   - Integrates with routeAnalysisEngine (Phase 1) and terrainAnalysisEngine (Phase 3)
 */

import { Platform } from 'react-native';
import type { RouteAnalysisSegment, RouteIntelligence } from './routeAnalysisEngine';
import type { TerrainIntelligence } from './terrainAnalysisEngine';
import type { CampRecommendationSet } from './campops/campOpsTypes';
import {
  CAMPSITE_ACCEPTABLE_MIN_RESULTS as CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD,
  CAMPSITE_HEALTHY_MIN_RESULTS as CAMPSITE_HEALTHY_THRESHOLD,
  CAMPSITE_MAX_MARKERS_RENDERED,
  CampsiteFallbackStage,
  denormalizeCampsiteScore,
  getCampsiteFallbackStageDefinition as getCampsiteFallbackStage,
  getMaxCampsiteFallbackStage,
  normalizeCampsiteScore,
  type CampsiteCredibilityTier,
  type CampsiteMode as CampsiteFallbackMode,
  type CampsiteFallbackStageDefinition,
} from './campsites/campsiteThresholds';
import type { CampsiteRating, CampsiteRatingFactor } from './campsites/campsiteRatingTypes';
import {
  CAMPSITE_GOOD_FALLBACK_SCORE,
  CAMPSITE_LIMITED_CONFIDENCE_SCORE,
  CAMPSITE_POSSIBLE_FALLBACK_SCORE,
  evaluateCampsiteCandidateViability,
  MIN_CAMPSITE_CORE_SCORE,
  type CampsiteCoreScoreKey,
  type CampsiteViabilityTier,
} from './campsites/campsiteViabilityFilter';
import { ecsLog } from './ecsLogger';

const TAG = '[CAMPSITE_CANDIDATE]';

function logCampsiteCandidateDebug(event: string, details?: Record<string, unknown>): void {
  ecsLog.dev('CAMPOPS', event, details, {
    tag: TAG,
    debugFlag: 'ECS_DEBUG_CAMP',
    fingerprint: `${event}:${JSON.stringify(details ?? {})}`,
    throttleMs: 2500,
    aggregateWindowMs: 30_000,
  });
}

// ── Types ────────────────────────────────────────────────────

/**
 * Suitability level for a campsite candidate (Phase 2).
 */
export type SuitabilityLevel = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Confidence level for a campsite suggestion (Phase 3 Refinement).
 *
 * HIGH   = strong timing + strong terrain/remoteness score
 * MEDIUM = reasonable timing or moderate score
 * LOW    = short route, poor timing, or borderline conditions
 */
export type ConfidenceLevel = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Remoteness data snapshot for campsite scoring (Phase 2).
 */
export interface RemotenessSnapshot {
  /** Remoteness tier from remotenessStore */
  tier?: string | null;
  /** Remoteness score 0–100 */
  score?: number | null;
}

/**
 * A candidate campsite location inferred from route segment data.
 */
export interface CampsiteCandidate {
  /** Index of the route segment where this candidate was detected */
  segmentIndex: number;
  /** Representative coordinate for this candidate [lat, lon] */
  coordinates: [number, number];
  /** Distance from route start to segment midpoint (miles) */
  distanceMiles: number;
  /** Average elevation at this segment (feet) */
  avgElevation: number;
  /** Elevation gain within this segment (feet) */
  elevationGain: number;
  /** Human-readable reasons why this segment qualifies as a candidate */
  candidateReason: string[];
  /** Segment distance range label (e.g., "60–70 mi") */
  segmentRange: string;
  /** Terrain difficulty of this segment */
  difficulty: 'easy' | 'moderate' | 'challenging' | 'difficult';
  /** Candidate quality score from Phase 1 (higher = better, 0–100) */
  qualityScore: number;

  // ── Phase 2: Suitability Scoring ──

  /** Suitability score from Phase 2 scoring engine (0–15+ range) */
  suitabilityScore: number;
  /** Marker-facing A/B/C/D rating derived from the existing campsite score */
  rating?: CampsiteRating;
  /** Marker-facing score normalized to a 0-100 display scale */
  score?: number;
  /** Existing remoteness scoring contribution normalized for explanation UI */
  remotenessScore?: number | null;
  /** Existing campsite suitability score normalized for explanation UI */
  campingSuitabilityScore?: number | null;
  /** Existing access confidence score when available */
  legalAccessScore?: number | null;
  /** Existing terrain/campability score when available */
  terrainScore?: number | null;
  /** Existing route proximity score when available */
  routeProximityScore?: number | null;
  /** Explanation factors behind the marker-facing rating */
  ratingFactors?: CampsiteRatingFactor[];
  /** Fallback confidence tier applied by final viability filtering */
  viabilityTier?: CampsiteViabilityTier;
  /** Human-readable confidence label for fallback-surfaced candidates */
  viabilityConfidenceLabel?: 'Preferred' | 'Good' | 'Possible' | 'Limited confidence' | 'Rejected';
  /** Suitability level derived from score */
  suitabilityLevel: SuitabilityLevel;
  /** Estimated arrival hour from departure (null if not computable) */
  estimatedArrivalHour: number | null;
  /** Scoring breakdown for debug/display */
  scoringBreakdown: ScoringBreakdown;

  // ── Phase 3 Refinement: Confidence ──

  /** Confidence level reflecting timing and route-day plausibility */
  confidence: ConfidenceLevel;
  /** Human-readable confidence reasons (e.g., "Short route may not require overnight camp") */
  confidenceReasons: string[];
  /** Fallback stage that surfaced this candidate */
  fallbackStage: number;
  /** Internal density mode used when this candidate was surfaced */
  fallbackMode: CampsiteFallbackMode;
  /** Whether broader-than-strict criteria were applied */
  criteriaBroadened: boolean;
  /** Internal credibility label for truthful UI language */
  credibilityTier: CampsiteCredibilityTier;
}

/**
 * Detailed scoring breakdown for transparency.
 */
export interface ScoringBreakdown {
  flatTerrainBonus: number;
  remotenessBonus: number;
  timingBonus: number;
  elevationPenalty: number;
  mountainPassPenalty: number;

  // ── Phase 3 Refinement additions ──

  /** Ideal camp timing window bonus/penalty (Phase 3) */
  idealTimingBonus: number;
  /** Too early in route penalty (Phase 3) */
  tooEarlyPenalty: number;
  /** Too close to destination penalty (Phase 3) */
  tooLatePenalty: number;
  /** Short route reduction (Phase 3) */
  shortRouteReduction: number;
  /** Overnight likelihood reduction (Phase 3) */
  overnightReduction: number;

  /** Human-readable scoring reasons */
  reasons: string[];
}

/**
 * Complete campsite candidate analysis result.
 */
export interface CampsiteCandidateResult {
  /** Unique analysis ID */
  id: string;
  /** Source route intelligence ID */
  routeIntelligenceId: string;
  /** Source route name */
  routeName: string;
  /** Total route distance (miles) */
  totalDistanceMiles: number;
  /** Estimated total drive time (hours) */
  estimatedDriveTimeHours: number;
  /** All detected campsite candidates (sorted by suitabilityScore desc) */
  candidates: CampsiteCandidate[];
  /** Suggested campsites retained for map/panel display */
  suggestedCampsites: CampsiteCandidate[];
  /** Number of candidates found */
  candidateCount: number;
  /** Total segments analyzed */
  totalSegments: number;
  /** Segments excluded (too early, too late, steep, pass) */
  excludedSegments: number;
  /** Analysis timestamp */
  analyzedAt: string;
  /** Whether Phase 2 scoring was applied */
  scoringApplied: boolean;

  // ── Phase 3 Refinement metadata ──

  /** Whether the route is considered short (< 60 mi) */
  isShortRoute: boolean;
  /** Whether overnight stop is considered unlikely (< 4.5 hrs drive) */
  overnightUnlikely: boolean;
  /** Whether any suggestion has HIGH confidence */
  hasHighConfidence: boolean;
  /** Best confidence level among suggested campsites */
  bestConfidence: ConfidenceLevel | null;
  /** Fallback stage applied to generate this result */
  fallbackStage: number;
  /** Internal density mode used when generating this result */
  fallbackMode: CampsiteFallbackMode;
  /** Whether broader-than-strict criteria were applied */
  criteriaBroadened: boolean;
  /** Healthy result threshold used for this analysis */
  healthyThreshold: number;
  /** Minimum acceptable threshold used for this analysis */
  minimumAcceptableThreshold: number;
  /** Truthful UI note when broader criteria were used */
  uiNotice: string | null;
  /** Machine-readable reason when route/polygon locating intentionally produced no displayable candidates */
  emptyReason?: string | null;
  /** Human-readable empty state detail for route/polygon locating */
  emptyStateMessage?: string | null;
  /** Candidate viability diagnostics for developer/debug surfaces */
  viabilitySummary?: {
    generationId?: string;
    generatedCount: number;
    totalBeforeFiltering?: number;
    afterSafetyCount?: number;
    afterScoreCount?: number;
    renderCount?: number;
    acceptedCount: number;
    rejectedCount: number;
    activeThreshold?: number;
    fallbackTier?: CampsiteViabilityTier | null;
    tierCounts?: Partial<Record<CampsiteViabilityTier, number>>;
    failingFactors: CampsiteCoreScoreKey[];
  };
  /** Explicit locator entry point that produced this result */
  analysisSource?: 'route' | 'polygon' | 'manual';
  /** Ownership source used by UI cleanup when route/polygon context changes */
  source?: 'route' | 'polygon' | 'manual';
  /** Candidate creation timestamp for stale ownership diagnostics */
  createdAt?: string;
  /** Source polygon ID when generated from a completed map drawing */
  polygonId?: string | null;
  /** Optional CampOps operational recommendation payload, gated by rollout config */
  campOps?: {
    enabled: boolean;
    recommendationSet: CampRecommendationSet | null;
  };
}

export type CampsiteCandidateOwnerSource = 'route' | 'polygon' | 'manual';

export interface CampsiteCandidateOwnerRef {
  source: CampsiteCandidateOwnerSource;
  routeIntelligenceId?: string | null;
  polygonId?: string | null;
}

export interface CampsiteCandidateRefreshOptions extends CampsiteCandidateOwnerRef {
  reason: string;
}

export interface CampsiteCandidatePublishOptions {
  requestToken?: string | null;
}

export interface CampsiteCandidateClearOptions extends Partial<CampsiteCandidateOwnerRef> {
  requestToken?: string | null;
}
// ── Constants ────────────────────────────────────────────────

/** Storage key for persistence */
const STORAGE_KEY = 'ecs_campsite_candidates';

/** Storage key for suggested campsites */
const SUGGESTED_STORAGE_KEY = 'ecs_suggested_campsites';

/** Maximum number of suggested campsites to keep */
const MAX_SUGGESTED = CAMPSITE_MAX_MARKERS_RENDERED;

/** Stabilization: Maximum number of candidates before scoring (prevents runaway lists) */
const MAX_CANDIDATES_BEFORE_SCORING = 20;



// ── Phase 3 Refinement Constants ─────────────────────────────

/** Short route threshold (miles) — below this, suppress or reduce suggestions */
const SHORT_ROUTE_THRESHOLD_MI = 60;

/** Quick trip threshold (hours) — below this, overnight stop unlikely */
const QUICK_TRIP_THRESHOLD_HRS = 4.5;

/** Too early in route threshold (% of total distance) */

/** Too close to destination threshold (% of total distance) */

/** Ideal camp timing window — preferred (hours from departure) */

/** Ideal camp timing window — acceptable (hours from departure) */

// ── Suitability Thresholds ───────────────────────────────────

function classifySuitability(score: number): SuitabilityLevel {
  if (score >= 7) return 'HIGH';
  if (score >= 3) return 'MEDIUM';
  return 'LOW';
}

// ── Confidence Classification (Phase 3) ──────────────────────

/**
 * Classify confidence based on timing, suitability, and route context.
 *
 * HIGH   = strong timing + strong terrain/remoteness score
 * MEDIUM = reasonable timing or moderate score
 * LOW    = short route, poor timing, or borderline conditions
 */
function classifyConfidence(
  suitabilityScore: number,
  estimatedArrivalHour: number | null,
  isShortRoute: boolean,
  overnightUnlikely: boolean,
  tooEarly: boolean,
  tooLate: boolean,
  fallbackStage: CampsiteFallbackStageDefinition,
  credibilityTier: CampsiteCredibilityTier,
): { confidence: ConfidenceLevel; reasons: string[] } {
  const reasons: string[] = [];
  let confidenceScore = 0;

  // ── Short route → LOW confidence ──
  if (isShortRoute) {
    reasons.push('Short route may not require overnight camp');
    return { confidence: 'LOW', reasons };
  }

  // ── Overnight unlikely → LOW confidence unless remoteness is very high ──
  if (overnightUnlikely) {
    reasons.push('Quick trip — overnight stop unlikely');
    if (suitabilityScore >= 7) {
      // High suitability can override overnight concern (remote area)
      reasons.push('High suitability in remote area overrides quick trip concern');
      return { confidence: 'MEDIUM', reasons };
    }
    return { confidence: 'LOW', reasons };
  }

  // ── Too early or too late → reduce confidence ──
  if (tooEarly) {
    reasons.push('Too early in route for likely camp stop');
    confidenceScore -= 2;
  }
  if (tooLate) {
    reasons.push('Too close to destination for likely camp stop');
    confidenceScore -= 2;
  }

  // ── Timing quality ──
  if (estimatedArrivalHour != null) {
    if (
      estimatedArrivalHour >= fallbackStage.scoring.idealTimingMinHrs &&
      estimatedArrivalHour <= fallbackStage.scoring.idealTimingMaxHrs
    ) {
      confidenceScore += 3;
    } else if (
      estimatedArrivalHour >= fallbackStage.scoring.acceptableTimingMinHrs &&
      estimatedArrivalHour <= fallbackStage.scoring.acceptableTimingMaxHrs
    ) {
      confidenceScore += 1;
    } else {
      confidenceScore -= 1;
    }
  }

  // ── Suitability quality ──
  if (suitabilityScore >= 7) {
    confidenceScore += 3;
  } else if (suitabilityScore >= 4) {
    confidenceScore += 1;
  } else {
    confidenceScore -= 1;
  }

  // ── Classify ──
  let confidence: ConfidenceLevel;
  if (confidenceScore >= 4) confidence = 'HIGH';
  else if (confidenceScore >= 1) confidence = 'MEDIUM';
  else confidence = 'LOW';

  if (credibilityTier === 'possible_stop' && confidence === 'HIGH') {
    confidence = 'MEDIUM';
  }
  if (fallbackStage.stage > 0) {
    reasons.push(
      credibilityTier === 'possible_stop'
        ? 'Surfaced as a possible stop/camp candidate under broader corridor criteria'
        : 'Surfaced under broader corridor criteria to maintain route coverage',
    );
  }
  if (confidence !== 'LOW') {
    return { confidence, reasons };
  }
  if (reasons.length === 0) {
    reasons.push('Borderline conditions');
  }
  return { confidence: 'LOW', reasons };
}

// ── Storage Helpers ──────────────────────────────────────────

const mem: Record<string, string> = {};

function sGet(key: string): string | null {
  try {
    if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
      return localStorage.getItem(key);
    }
    return mem[key] || null;
  } catch { return mem[key] || null; }
}

function sSet(key: string, value: string): void {
  try {
    if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
      localStorage.setItem(key, value);
    }
    mem[key] = value;
  } catch { mem[key] = value; }
}

function uuid(): string {
  const c: any = typeof crypto !== 'undefined' ? crypto : null;
  if (c && c.randomUUID) return c.randomUUID();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (ch) => {
    const r = (Math.random() * 16) | 0;
    return (ch === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

type CampsitePolygonPoint = { latitude: number; longitude: number };

function isFinitePolygonPoint(point: CampsitePolygonPoint): boolean {
  return (
    Number.isFinite(point.latitude) &&
    Number.isFinite(point.longitude) &&
    point.latitude >= -90 &&
    point.latitude <= 90 &&
    point.longitude >= -180 &&
    point.longitude <= 180
  );
}

function pointInPolygon(point: CampsitePolygonPoint, polygon: CampsitePolygonPoint[]): boolean {
  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const xi = polygon[i].longitude;
    const yi = polygon[i].latitude;
    const xj = polygon[j].longitude;
    const yj = polygon[j].latitude;
    const intersects =
      yi > point.latitude !== yj > point.latitude &&
      point.longitude < ((xj - xi) * (point.latitude - yi)) / ((yj - yi) || 1e-9) + xi;
    if (intersects) inside = !inside;
  }
  return inside;
}

function polygonBounds(points: CampsitePolygonPoint[]) {
  return points.reduce(
    (bounds, point) => ({
      minLat: Math.min(bounds.minLat, point.latitude),
      maxLat: Math.max(bounds.maxLat, point.latitude),
      minLon: Math.min(bounds.minLon, point.longitude),
      maxLon: Math.max(bounds.maxLon, point.longitude),
    }),
    { minLat: 90, maxLat: -90, minLon: 180, maxLon: -180 },
  );
}

function polygonCentroid(points: CampsitePolygonPoint[]): CampsitePolygonPoint {
  const sum = points.reduce(
    (acc, point) => ({
      latitude: acc.latitude + point.latitude,
      longitude: acc.longitude + point.longitude,
    }),
    { latitude: 0, longitude: 0 },
  );
  return {
    latitude: sum.latitude / Math.max(points.length, 1),
    longitude: sum.longitude / Math.max(points.length, 1),
  };
}

function distanceMi(a: CampsitePolygonPoint, b: CampsitePolygonPoint): number {
  const r = 3958.8;
  const dLat = ((b.latitude - a.latitude) * Math.PI) / 180;
  const dLon = ((b.longitude - a.longitude) * Math.PI) / 180;
  const lat1 = (a.latitude * Math.PI) / 180;
  const lat2 = (b.latitude * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
  return r * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

function buildPolygonCandidateRouteIntel(
  polygon: CampsitePolygonPoint[],
  polygonId: string,
  routeName: string,
  candidatePoints: CampsitePolygonPoint[],
): RouteIntelligence {
  const bounds = polygonBounds(polygon);
  const totalDistanceMiles = Math.max(80, distanceMi(
    { latitude: bounds.minLat, longitude: bounds.minLon },
    { latitude: bounds.maxLat, longitude: bounds.maxLon },
  ) * 12);
  const segmentDistance = totalDistanceMiles / Math.max(candidatePoints.length, 1);
  const segments: RouteAnalysisSegment[] = candidatePoints.map((point, index) => {
    const distanceStart = Math.max(0, index * segmentDistance);
    const distanceEnd = Math.min(totalDistanceMiles, distanceStart + segmentDistance);
    const variation = (index % 5) * 8;
    return {
      segmentIndex: index,
      distanceStart,
      distanceEnd,
      avgElevation: 4200 + variation * 12,
      elevationGain: 42 + variation,
      elevationLoss: 28 + variation,
      maxElevation: 4300 + variation * 12,
      minElevation: 4100 + variation * 10,
      coordinates: [point.latitude, point.longitude],
      pointCount: 3,
      avgGradePercent: 1.2 + (index % 3) * 0.4,
      maxGradePercent: 2.4 + (index % 4) * 0.6,
      difficulty: index % 4 === 0 ? 'moderate' : 'easy',
      estimatedDriveTimeHours: segmentDistance / 14,
    };
  });

  return {
    id: `polygon-camp-intel-${polygonId}`,
    sourceId: polygonId,
    routeName,
    totalDistanceMiles,
    estimatedDriveTimeHours: Math.max(6.5, totalDistanceMiles / 14),
    elevationGainFeet: segments.reduce((sum, segment) => sum + segment.elevationGain, 0),
    elevationLossFeet: segments.reduce((sum, segment) => sum + segment.elevationLoss, 0),
    highestElevationFeet: Math.max(...segments.map((segment) => segment.maxElevation), 0),
    lowestElevationFeet: Math.min(...segments.map((segment) => segment.minElevation), 0),
    avgElevationFeet:
      segments.reduce((sum, segment) => sum + segment.avgElevation, 0) / Math.max(segments.length, 1),
    totalPoints: candidatePoints.length,
    segments,
    segmentCount: segments.length,
    overallDifficulty: 'moderate',
    bounds,
    elevationProfile: segments.map((segment) => ({
      distanceMi: segment.distanceStart,
      elevationFt: segment.avgElevation,
    })),
    analyzedAt: new Date().toISOString(),
    hasElevation: false,
    avgSpeedAssumption: 14,
  };
}

function generatePolygonCampsiteCandidatePoints(
  polygon: CampsitePolygonPoint[],
  maxPoints = 14,
): CampsitePolygonPoint[] {
  const bounds = polygonBounds(polygon);
  const centroid = polygonCentroid(polygon);
  const points: CampsitePolygonPoint[] = [];
  const pushIfInside = (point: CampsitePolygonPoint) => {
    if (!isFinitePolygonPoint(point)) return;
    if (!pointInPolygon(point, polygon)) return;
    const key = `${point.latitude.toFixed(5)},${point.longitude.toFixed(5)}`;
    if (points.some((existing) => `${existing.latitude.toFixed(5)},${existing.longitude.toFixed(5)}` === key)) return;
    points.push(point);
  };

  pushIfInside(centroid);

  const rows = 5;
  const cols = 5;
  for (let row = 1; row < rows; row += 1) {
    for (let col = 1; col < cols; col += 1) {
      const latitude = bounds.minLat + ((bounds.maxLat - bounds.minLat) * row) / rows;
      const longitude = bounds.minLon + ((bounds.maxLon - bounds.minLon) * col) / cols;
      pushIfInside({ latitude, longitude });
      if (points.length >= maxPoints) return points;
    }
  }

  for (const point of polygon) {
    pushIfInside({
      latitude: (point.latitude + centroid.latitude) / 2,
      longitude: (point.longitude + centroid.longitude) / 2,
    });
    if (points.length >= maxPoints) return points;
  }

  return points;
}

// ── Core Analysis Function (Phase 1) ─────────────────────────

/**
 * Find campsite candidates by analyzing route segments and terrain intelligence.
 *
 * A segment becomes a campsite candidate when ALL of the following are true:
 *   A. Flat or relatively stable terrain (elevationGain <= 150 ft)
 *   B. Not flagged as STEEP_GRADE or MOUNTAIN_PASS by Terrain Analysis
 *   C. Not in the first 20% of route distance
 *   D. Not in the final 10% of route distance
 *
 * @param routeSegments - Phase 1 RouteAnalysisSegment[] from route analysis
 * @param terrainIntel - Phase 3 TerrainIntelligence (optional, for warning exclusion)
 * @param totalDistanceMiles - Total route distance in miles
 * @returns CampsiteCandidate[] of qualifying segments (Phase 1 only, no scoring)
 */
export function findCampsiteCandidates(
  routeSegments: RouteAnalysisSegment[],
  terrainIntel: TerrainIntelligence | null,
  totalDistanceMiles: number,
  fallbackStage: CampsiteFallbackStageDefinition = getCampsiteFallbackStage(0),
): CampsiteCandidate[] {
  if (!routeSegments || routeSegments.length === 0 || totalDistanceMiles <= 0) {
    return [];
  }

  // ── Stabilization: Guard against NaN/Infinity distance ──
  if (!isFinite(totalDistanceMiles)) {
    console.warn(TAG, 'Total distance is not finite — returning empty candidates');
    return [];
  }

  // ── Build set of segment indices with disqualifying terrain warnings ──
  const disqualifiedSegments = new Set<number>();

  if (terrainIntel && terrainIntel.terrainWarnings && terrainIntel.terrainWarnings.length > 0) {
    for (const warning of terrainIntel.terrainWarnings) {
      if (fallbackStage.detection.disqualifyingWarnings.includes(warning.warningType)) {
        disqualifiedSegments.add(warning.segmentIndex);
      }
    }
  }

  // ── Compute distance exclusion thresholds ──
  const startExclusionMiles = totalDistanceMiles * fallbackStage.detection.routeStartExclusion;
  const endExclusionMiles = totalDistanceMiles * (1 - fallbackStage.detection.routeEndExclusion);

  const candidates: CampsiteCandidate[] = [];

  // ── Stabilization: Track last accepted candidate distance for spacing ──
  let lastAcceptedDistanceMi = -Infinity;
  let lastAcceptedSegmentIndex = -Infinity;
  // ── Stabilization: Track accepted segment indices to prevent duplicates ──
  const acceptedSegmentIndices = new Set<number>();
  // ── Stabilization: Track accepted coordinate keys to prevent near-duplicates ──
  const acceptedCoordKeys = new Set<string>();

  // ── Loop through all segments and apply candidacy rules ──
  for (const seg of routeSegments) {
    const reasons: string[] = [];
    let qualityScore = 50; // Base score

    // ── Stabilization: Validate segment data ──
    if (seg.segmentIndex == null || !seg.coordinates || seg.coordinates.length < 2) {
      continue; // Skip malformed segments
    }

    // Compute segment midpoint distance
    const segMidpointMiles = (seg.distanceStart + seg.distanceEnd) / 2;

    // ── Stabilization: Validate midpoint distance ──
    if (!isFinite(segMidpointMiles)) continue;

    // ── Rule C: Not too early in the route (first 20%) ──
    if (segMidpointMiles < startExclusionMiles) {
      continue; // Skip — too close to departure
    }

    // ── Rule D: Not too close to the end (final 10%) ──
    if (segMidpointMiles > endExclusionMiles) {
      continue; // Skip — too close to destination
    }

    // ── Rule B: Not flagged as steep terrain or mountain pass ──
    if (disqualifiedSegments.has(seg.segmentIndex)) {
      continue; // Skip — terrain analysis flagged this segment
    }

    // ── Rule A: Flat or relatively stable terrain ──
    if (seg.elevationGain > fallbackStage.detection.maxElevationGainFt) {
      continue; // Skip — too much elevation change
    }

    // ── Stabilization: Prevent duplicate segment indices ──
    if (acceptedSegmentIndices.has(seg.segmentIndex)) {
      continue;
    }
    if (seg.segmentIndex - lastAcceptedSegmentIndex < fallbackStage.detection.minCandidateSegmentSpacing) {
      continue;
    }

    // ── Stabilization: Prevent candidates at identical/near-identical coordinates ──
    const coordKey = `${seg.coordinates[0].toFixed(3)},${seg.coordinates[1].toFixed(3)}`;
    if (acceptedCoordKeys.has(coordKey)) {
      continue;
    }

    // ── Stabilization: Enforce minimum distance spacing between candidates ──
    if (segMidpointMiles - lastAcceptedDistanceMi < fallbackStage.detection.minCandidateDistanceMi) {
      continue; // Skip — too close to last accepted candidate
    }

    // ── All rules passed — this is a campsite candidate ──

    // Build candidate reasons
    reasons.push('Low elevation change');

    // Mid-route location bonus
    const routeProgress = segMidpointMiles / totalDistanceMiles;
    if (routeProgress >= 0.35 && routeProgress <= 0.65) {
      reasons.push('Mid-route location');
      qualityScore += 15; // Bonus for being in the middle third
    }

    // Outside steep terrain zones
    if (terrainIntel && terrainIntel.steepSegments > 0) {
      reasons.push('Outside steep terrain zones');
      qualityScore += 10;
    }

    // Easy terrain bonus
    if (seg.difficulty === 'easy') {
      reasons.push('Easy terrain classification');
      qualityScore += 10;
    } else if (seg.difficulty === 'moderate') {
      reasons.push('Moderate terrain classification');
      qualityScore += 5;
    }

    // Very flat terrain bonus (< 50 ft gain)
    if (seg.elevationGain < 50) {
      reasons.push('Very flat terrain');
      qualityScore += 15;
    } else if (seg.elevationGain < 100) {
      reasons.push('Relatively flat terrain');
      qualityScore += 5;
    }

    // Low grade bonus
    if (seg.avgGradePercent < 2) {
      reasons.push('Low average grade');
      qualityScore += 5;
    }

    // Moderate elevation preference (not too high, not too low)
    if (seg.avgElevation >= 3000 && seg.avgElevation <= 8000) {
      qualityScore += 5;
    }

    // Cap quality score at 100
    qualityScore = Math.min(100, Math.max(0, qualityScore));

    const rangeLabel = `${seg.distanceStart.toFixed(0)}–${seg.distanceEnd.toFixed(0)} mi`;

    candidates.push({
      segmentIndex: seg.segmentIndex,
      coordinates: seg.coordinates,
      distanceMiles: Math.round(segMidpointMiles * 10) / 10,
      avgElevation: seg.avgElevation,
      elevationGain: seg.elevationGain,
      candidateReason: reasons,
      segmentRange: rangeLabel,
      difficulty: seg.difficulty,
      qualityScore,
      // Phase 2 defaults (will be overwritten by scoring)
      suitabilityScore: 0,
      suitabilityLevel: 'LOW',
      estimatedArrivalHour: null,
      scoringBreakdown: {
        flatTerrainBonus: 0,
        remotenessBonus: 0,
        timingBonus: 0,
        elevationPenalty: 0,
        mountainPassPenalty: 0,
        idealTimingBonus: 0,
        tooEarlyPenalty: 0,
        tooLatePenalty: 0,
        shortRouteReduction: 0,
        overnightReduction: 0,
        reasons: [],
      },
      // Phase 3 defaults
      confidence: 'LOW',
      confidenceReasons: [],
      fallbackStage: fallbackStage.stage,
      fallbackMode: fallbackStage.mode,
      criteriaBroadened: fallbackStage.stage > 0,
      credibilityTier: fallbackStage.credibilityTier,
    });

    // ── Stabilization: Track accepted candidate for dedup/spacing ──
    lastAcceptedDistanceMi = segMidpointMiles;
    lastAcceptedSegmentIndex = seg.segmentIndex;
    acceptedSegmentIndices.add(seg.segmentIndex);
    acceptedCoordKeys.add(coordKey);

    if (candidates.length >= MAX_CANDIDATES_BEFORE_SCORING) {
      break;
    }
  }

  candidates.sort((a, b) => b.qualityScore - a.qualityScore);

  return candidates;
}



// ══════════════════════════════════════════════════════════════
// PHASE 2 + PHASE 3 REFINEMENT: CAMPSITE SUITABILITY SCORING ENGINE
// ══════════════════════════════════════════════════════════════

/**
 * Score campsite candidates using route timing, remoteness, terrain quality,
 * and Phase 3 smart timing / route-day filtering.
 *
 * SCORING RULES (Phase 2):
 *   Flat terrain bonus:
 *     <= 100 ft → +3
 *     <= 150 ft → +2
 *
 *   Remoteness bonus:
 *     high remoteness → +3
 *     medium remoteness → +2
 *     low remoteness → +0
 *
 *   Terrain penalty:
 *     high elevation nearby → -2
 *
 *   Mountain pass proximity penalty:
 *     within 1 segment of a mountain pass warning → -3
 *
 * SCORING RULES (Phase 3 Refinement):
 *   Ideal camp timing window:
 *     6–10 hrs from departure → +4
 *     4–12 hrs from departure → +2
 *     < 4 hrs or > 12 hrs → -3
 *
 *   Too early in route (< 35% distance) → -4
 *   Too close to destination (> 90% distance) → -4
 *   Short route (< 60 mi) → all scores reduced by -3
 *   Quick trip (< 4.5 hrs drive) → all scores reduced by -3
 *
 * @param candidates - Phase 1 CampsiteCandidate[]
 * @param routeIntel - Phase 1 RouteIntelligence
 * @param terrainIntel - Phase 3 TerrainIntelligence
 * @param remotenessData - Optional remoteness snapshot
 * @returns CampsiteCandidate[] scored and sorted highest first
 */
export function scoreCampsiteCandidates(
  candidates: CampsiteCandidate[],
  routeIntel: RouteIntelligence,
  terrainIntel: TerrainIntelligence | null,
  remotenessData?: RemotenessSnapshot | null,
  fallbackStage: CampsiteFallbackStageDefinition = getCampsiteFallbackStage(0),
): CampsiteCandidate[] {
  if (!candidates || candidates.length === 0) return [];

  // ── Stabilization: Guard against null/undefined routeIntel ──
  if (!routeIntel) {
    console.warn(TAG, 'scoreCampsiteCandidates called with null routeIntel — returning unscored candidates');
    return candidates;
  }

  const totalDistanceMiles = routeIntel.totalDistanceMiles ?? 0;
  const estimatedDriveTimeHours = routeIntel.estimatedDriveTimeHours ?? 0;

  // ── Phase 3: Route-level context flags ──
  const isShortRoute = totalDistanceMiles < SHORT_ROUTE_THRESHOLD_MI;
  const overnightUnlikely = estimatedDriveTimeHours < QUICK_TRIP_THRESHOLD_HRS;

  // ── Build mountain pass segment index set (for proximity penalty) ──
  const mountainPassSegments = new Set<number>();
  if (terrainIntel) {
    for (const warning of terrainIntel.terrainWarnings) {
      if (warning.warningType === 'MOUNTAIN_PASS') {
        mountainPassSegments.add(warning.segmentIndex);
      }
    }
  }

  // ── Build high elevation segment index set (for elevation penalty) ──
  const highElevationSegments = new Set<number>();
  if (terrainIntel) {
    for (const warning of terrainIntel.terrainWarnings) {
      if (warning.warningType === 'HIGH_ELEVATION') {
        highElevationSegments.add(warning.segmentIndex);
      }
    }
  }

  // ── Resolve remoteness level ──
  let remotenessLevel: 'high' | 'medium' | 'low' = 'low';
  if (remotenessData) {
    if (remotenessData.tier) {
      const tier = remotenessData.tier.toUpperCase();
      if (tier === 'EXTREME' || tier === 'DEEP REMOTE' || tier === 'REMOTE') {
        remotenessLevel = 'high';
      } else if (tier === 'BACKCOUNTRY') {
        remotenessLevel = 'medium';
      }
    } else if (remotenessData.score != null) {
      if (remotenessData.score >= 36) remotenessLevel = 'high';
      else if (remotenessData.score >= 16) remotenessLevel = 'medium';
    }
  }

  // ── Score each candidate ──
  const scoredCandidates: CampsiteCandidate[] = candidates.map(candidate => {
    let score = 0;
    const breakdownReasons: string[] = [];

    // ── Arrival Time Estimation ──
    let estimatedArrivalHour: number | null = null;
    if (totalDistanceMiles > 0 && estimatedDriveTimeHours > 0) {
      const candidateProgress = candidate.distanceMiles / totalDistanceMiles;
      estimatedArrivalHour = Math.round(estimatedDriveTimeHours * candidateProgress * 10) / 10;
    }

    // ── Route progress for Phase 3 checks ──
    const routeProgress = totalDistanceMiles > 0
      ? candidate.distanceMiles / totalDistanceMiles
      : 0;
    const tooEarly = routeProgress < fallbackStage.scoring.tooEarlyThreshold;
    const tooLate = routeProgress > fallbackStage.scoring.tooLateThreshold;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 1: Flat terrain bonus (Phase 2)
    // ══════════════════════════════════════════════════════════
    let flatTerrainBonus = 0;
    if (candidate.elevationGain <= 100) {
      flatTerrainBonus = 3;
      breakdownReasons.push('Flat terrain (+3)');
    } else if (candidate.elevationGain <= 150) {
      flatTerrainBonus = 2;
      breakdownReasons.push('Stable terrain (+2)');
    }
    score += flatTerrainBonus;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 2: Remoteness bonus (Phase 2)
    // ══════════════════════════════════════════════════════════
    let remotenessBonus = 0;
    if (fallbackStage.scoring.remotenessMode === 'preferred_band') {
      if (remotenessLevel === 'high') {
        remotenessBonus = 3;
        breakdownReasons.push('Remote location (+3)');
      } else if (remotenessLevel === 'medium') {
        remotenessBonus = 2;
        breakdownReasons.push('Backcountry location (+2)');
      }
    } else if (fallbackStage.scoring.remotenessMode === 'soft_preference') {
      if (remotenessLevel === 'high') {
        remotenessBonus = 2;
        breakdownReasons.push('Remote location (+2)');
      } else if (remotenessLevel === 'medium') {
        remotenessBonus = 1;
        breakdownReasons.push('Backcountry location (+1)');
      }
    } else if (remotenessLevel === 'high') {
      remotenessBonus = 1;
      breakdownReasons.push('Remote context bonus (+1)');
    } else if (remotenessLevel === 'medium') {
      remotenessBonus = 1;
      breakdownReasons.push('Contextual backcountry bonus (+1)');
    }
    score += remotenessBonus;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 3: Ideal camp timing window (Phase 3 — replaces Phase 2 timing)
    // ══════════════════════════════════════════════════════════
    let idealTimingBonus = 0;
    let timingBonus = 0; // Legacy Phase 2 field — kept for backward compat
    if (estimatedArrivalHour != null) {
      if (
        estimatedArrivalHour >= fallbackStage.scoring.idealTimingMinHrs &&
        estimatedArrivalHour <= fallbackStage.scoring.idealTimingMaxHrs
      ) {
        // Preferred window: 6–10 hours from departure
        idealTimingBonus = 4;
        timingBonus = 4;
        breakdownReasons.push('Ideal camp timing window (+4)');
      } else if (
        estimatedArrivalHour >= fallbackStage.scoring.acceptableTimingMinHrs &&
        estimatedArrivalHour <= fallbackStage.scoring.acceptableTimingMaxHrs
      ) {
        // Acceptable window: 4–12 hours from departure
        idealTimingBonus = 2;
        timingBonus = 2;
        breakdownReasons.push('Acceptable camp timing (+2)');
      } else {
        // Poor timing: < 4 hrs or > 12 hrs
        idealTimingBonus = -3;
        timingBonus = -3;
        breakdownReasons.push('Poor camp timing (-3)');
      }
    }
    score += idealTimingBonus;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 4: Terrain penalty — high elevation nearby (Phase 2)
    // ══════════════════════════════════════════════════════════
    let elevationPenalty = 0;
    // Check if this segment or adjacent segments are high elevation
    const highElevationWindow = fallbackStage.scoring.highElevationPenaltyWindow;
    const adjRange = Array.from(
      { length: (highElevationWindow * 2) + 1 },
      (_, index) => candidate.segmentIndex - highElevationWindow + index,
    );
    const nearHighElevation = adjRange.some(idx => highElevationSegments.has(idx));
    if (nearHighElevation) {
      elevationPenalty = -2;
      breakdownReasons.push('High elevation nearby (-2)');
    }
    score += elevationPenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 5: Mountain pass proximity penalty (Phase 2)
    // ══════════════════════════════════════════════════════════
    let mountainPassPenalty = 0;
    // Check if within 1 segment of a mountain pass warning
    const mountainPassWindow = fallbackStage.scoring.mountainPassPenaltyWindow;
    const passRange = Array.from(
      { length: (mountainPassWindow * 2) + 1 },
      (_, index) => candidate.segmentIndex - mountainPassWindow + index,
    );
    const nearMountainPass = passRange.some(idx => mountainPassSegments.has(idx));
    if (nearMountainPass) {
      mountainPassPenalty = -3;
      breakdownReasons.push('Near mountain pass (-3)');
    }
    score += mountainPassPenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 6: Too early in route penalty (Phase 3)
    // ══════════════════════════════════════════════════════════
    let tooEarlyPenalty = 0;
    if (tooEarly) {
      tooEarlyPenalty = fallbackStage.scoring.tooEarlyPenalty;
      breakdownReasons.push('Too early in route (-4)');
    }
    score += tooEarlyPenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 7: Too close to destination penalty (Phase 3)
    // ══════════════════════════════════════════════════════════
    let tooLatePenalty = 0;
    if (tooLate) {
      tooLatePenalty = fallbackStage.scoring.tooLatePenalty;
      breakdownReasons.push('Too close to destination (-4)');
    }
    score += tooLatePenalty;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 8: Short route reduction (Phase 3)
    // ══════════════════════════════════════════════════════════
    let shortRouteReduction = 0;
    if (isShortRoute) {
      shortRouteReduction = fallbackStage.scoring.shortRouteReduction;
      breakdownReasons.push('Short route reduction (-3)');
    }
    score += shortRouteReduction;

    // ══════════════════════════════════════════════════════════
    // SCORING RULE 9: Overnight likelihood reduction (Phase 3)
    // ══════════════════════════════════════════════════════════
    let overnightReduction = 0;
    if (overnightUnlikely) {
      // Only apply if remoteness is not very high (remote areas may still need camp)
      if (remotenessLevel !== 'high') {
        overnightReduction = fallbackStage.scoring.overnightReduction;
        breakdownReasons.push('Quick trip — overnight unlikely (-3)');
      }
    }
    score += overnightReduction;

    // ── Clamp score to minimum 0 ──
    score = Math.max(0, score);

    // ── Classify suitability level ──
    const suitabilityLevel = classifySuitability(score);

    // ── Classify confidence (Phase 3) ──
    const { confidence, reasons: confidenceReasons } = classifyConfidence(
      score,
      estimatedArrivalHour,
      isShortRoute,
      overnightUnlikely,
      tooEarly,
      tooLate,
      fallbackStage,
      candidate.credibilityTier,
    );

    // ── Build scoring breakdown ──
    const scoringBreakdown: ScoringBreakdown = {
      flatTerrainBonus,
      remotenessBonus,
      timingBonus,
      elevationPenalty,
      mountainPassPenalty,
      idealTimingBonus,
      tooEarlyPenalty,
      tooLatePenalty,
      shortRouteReduction,
      overnightReduction,
      reasons: breakdownReasons,
    };

    return {
      ...candidate,
      suitabilityScore: score,
      suitabilityLevel,
      estimatedArrivalHour,
      scoringBreakdown,
      confidence,
      confidenceReasons,
    };
  });

  // ── Sort by suitability score (highest first), then by quality score as tiebreaker ──
  scoredCandidates.sort((a, b) => {
    if (b.suitabilityScore !== a.suitabilityScore) {
      return b.suitabilityScore - a.suitabilityScore;
    }
    return b.qualityScore - a.qualityScore;
  });




  return scoredCandidates;
}

function rankConfidence(confidence: ConfidenceLevel | null | undefined): number {
  switch (confidence) {
    case 'HIGH':
      return 3;
    case 'MEDIUM':
      return 2;
    case 'LOW':
      return 1;
    default:
      return 0;
  }
}

function selectSuggestedCampsites(
  scoredCandidates: CampsiteCandidate[],
  isShortRoute: boolean,
  fallbackStage: CampsiteFallbackStageDefinition,
): CampsiteCandidate[] {
  const minSuitabilityScore = denormalizeCampsiteScore(fallbackStage.scoring.minScoreNormalized);
  const stageEligibleCandidates = scoredCandidates.filter(
    (candidate) => normalizeCampsiteScore(candidate.suitabilityScore) >= fallbackStage.scoring.minScoreNormalized,
  );

  if (isShortRoute) {
    return stageEligibleCandidates
      .filter(
        (candidate) =>
          (candidate.confidence === 'LOW' || candidate.confidence === 'MEDIUM') &&
          candidate.suitabilityScore >= minSuitabilityScore,
      )
      .slice(0, MAX_SUGGESTED);
  }
  return stageEligibleCandidates
    .filter((candidate) => candidate.suitabilityScore >= minSuitabilityScore)
    .slice(0, MAX_SUGGESTED);
}

function buildStageCampsiteResult(args: {
  routeIntel: RouteIntelligence;
  terrainIntel: TerrainIntelligence | null;
  remotenessData?: RemotenessSnapshot | null;
  fallbackStage: CampsiteFallbackStageDefinition;
  nowIso: string;
}): CampsiteCandidateResult {
  const { routeIntel, terrainIntel, remotenessData, fallbackStage, nowIso } = args;
  const totalDistanceMiles = routeIntel.totalDistanceMiles ?? 0;
  const estimatedDriveTimeHours = routeIntel.estimatedDriveTimeHours ?? 0;
  const isShortRoute = totalDistanceMiles < SHORT_ROUTE_THRESHOLD_MI;
  const overnightUnlikely = estimatedDriveTimeHours < QUICK_TRIP_THRESHOLD_HRS;
  const rawCandidates = findCampsiteCandidates(
    routeIntel.segments,
    terrainIntel,
    totalDistanceMiles,
    fallbackStage,
  );
  const scoredCandidates = scoreCampsiteCandidates(
    rawCandidates,
    routeIntel,
    terrainIntel,
    remotenessData,
    fallbackStage,
  );
  const suggestedCampsites = selectSuggestedCampsites(scoredCandidates, isShortRoute, fallbackStage);
  const hasHighConfidence = suggestedCampsites.some((candidate) => candidate.confidence === 'HIGH');
  const bestConfidence: ConfidenceLevel | null =
    suggestedCampsites.length > 0
      ? suggestedCampsites.reduce<ConfidenceLevel>((best, candidate) => {
          const order: Record<ConfidenceLevel, number> = { LOW: 0, MEDIUM: 1, HIGH: 2 };
          return order[candidate.confidence] > order[best] ? candidate.confidence : best;
        }, 'LOW')
      : null;

  return {
    id: uuid(),
    routeIntelligenceId: routeIntel.id,
    routeName: routeIntel.routeName,
    totalDistanceMiles,
    estimatedDriveTimeHours,
    candidates: scoredCandidates,
    suggestedCampsites,
    candidateCount: scoredCandidates.length,
    totalSegments: routeIntel.segments.length,
    excludedSegments: routeIntel.segments.length - scoredCandidates.length,
    analyzedAt: nowIso,
    scoringApplied: true,
    isShortRoute,
    overnightUnlikely,
    hasHighConfidence,
    bestConfidence,
    fallbackStage: fallbackStage.stage,
    fallbackMode: fallbackStage.mode,
    criteriaBroadened: fallbackStage.stage > 0,
    healthyThreshold: CAMPSITE_HEALTHY_THRESHOLD,
    minimumAcceptableThreshold: CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD,
    uiNotice: fallbackStage.uiNotice,
  };
}

function isBetterCampsiteResult(
  candidate: CampsiteCandidateResult,
  current: CampsiteCandidateResult,
): boolean {
  if (candidate.suggestedCampsites.length !== current.suggestedCampsites.length) {
    return candidate.suggestedCampsites.length > current.suggestedCampsites.length;
  }
  if (candidate.candidateCount !== current.candidateCount) {
    return candidate.candidateCount > current.candidateCount;
  }
  if (rankConfidence(candidate.bestConfidence) !== rankConfidence(current.bestConfidence)) {
    return rankConfidence(candidate.bestConfidence) > rankConfidence(current.bestConfidence);
  }
  return (
    (candidate.suggestedCampsites[0]?.suitabilityScore ?? -1) >
    (current.suggestedCampsites[0]?.suitabilityScore ?? -1)
  );
}

// ── Full Analysis Function ───────────────────────────────────

/**
 * Run complete campsite candidate analysis from RouteIntelligence and TerrainIntelligence.
 * Includes Phase 2 suitability scoring and Phase 3 smart timing refinement.
 *
 * @param routeIntel - Phase 1 RouteIntelligence
 * @param terrainIntel - Phase 3 TerrainIntelligence (optional)
 * @param remotenessData - Optional remoteness snapshot for scoring
 * @returns CampsiteCandidateResult
 */
export function analyzeCampsiteCandidates(
  routeIntel: RouteIntelligence,
  terrainIntel: TerrainIntelligence | null,
  remotenessData?: RemotenessSnapshot | null,
): CampsiteCandidateResult {
  const now = new Date().toISOString();

  // ── Stabilization: Guard against null/undefined routeIntel ──
  if (!routeIntel) {
    console.warn(TAG, 'analyzeCampsiteCandidates called with null routeIntel — returning empty result');
    return {
      id: uuid(),
      routeIntelligenceId: 'unknown',
      routeName: 'Unknown Route',
      totalDistanceMiles: 0,
      estimatedDriveTimeHours: 0,
      candidates: [],
      suggestedCampsites: [],
      candidateCount: 0,
      totalSegments: 0,
      excludedSegments: 0,
      analyzedAt: now,
      scoringApplied: false,
      isShortRoute: true,
      overnightUnlikely: true,
      hasHighConfidence: false,
      bestConfidence: null,
      fallbackStage: 0,
      fallbackMode: 'strict',
      criteriaBroadened: false,
      healthyThreshold: CAMPSITE_HEALTHY_THRESHOLD,
      minimumAcceptableThreshold: CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD,
      uiNotice: null,
    };
  }

  // ── Stabilization: Safe access to route properties ──
  const totalDistanceMiles = routeIntel.totalDistanceMiles ?? 0;
  const estimatedDriveTimeHours = routeIntel.estimatedDriveTimeHours ?? 0;

  const isShortRoute = totalDistanceMiles < SHORT_ROUTE_THRESHOLD_MI;
  const overnightUnlikely = estimatedDriveTimeHours < QUICK_TRIP_THRESHOLD_HRS;

  if (!routeIntel.segments || routeIntel.segments.length === 0) {
    console.warn(TAG, 'analyzeCampsiteCandidates: no segments — returning empty result');
    return {
      id: uuid(),
      routeIntelligenceId: routeIntel.id,
      routeName: routeIntel.routeName,
      totalDistanceMiles: totalDistanceMiles,
      estimatedDriveTimeHours: estimatedDriveTimeHours,
      candidates: [],
      suggestedCampsites: [],
      candidateCount: 0,
      totalSegments: 0,
      excludedSegments: 0,
      analyzedAt: now,
      scoringApplied: false,
      isShortRoute,
      overnightUnlikely,
      hasHighConfidence: false,
      bestConfidence: null,
      fallbackStage: 0,
      fallbackMode: 'strict',
      criteriaBroadened: false,
      healthyThreshold: CAMPSITE_HEALTHY_THRESHOLD,
      minimumAcceptableThreshold: CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD,
      uiNotice: null,
    };
  }


  // Phase 1: Find candidates
  const strictStageResult = buildStageCampsiteResult({
    routeIntel,
    terrainIntel,
    remotenessData,
    fallbackStage: getCampsiteFallbackStage(0),
    nowIso: now,
  });
  const strictSuggestionCount = strictStageResult.suggestedCampsites.length;
  const maxFallbackStage = getMaxCampsiteFallbackStage(strictSuggestionCount);
  const targetCount =
    strictSuggestionCount >= CAMPSITE_HEALTHY_THRESHOLD
      ? CAMPSITE_HEALTHY_THRESHOLD
      : strictSuggestionCount >= CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD
        ? strictSuggestionCount
        : CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD;
  let selectedResult = strictStageResult;

  // ── Phase 3: Filter suggested campsites based on route context ──
  for (let stage = 1; stage <= maxFallbackStage; stage += 1) {

    const stageResult = buildStageCampsiteResult({
      routeIntel,
      terrainIntel,
      remotenessData,
      fallbackStage: getCampsiteFallbackStage(stage),
      nowIso: now,
    });

    if (isBetterCampsiteResult(stageResult, selectedResult)) {
      selectedResult = stageResult;
    }

  // ── Phase 3: Compute confidence metadata ──
    if (stageResult.candidateCount >= targetCount && stageResult.suggestedCampsites.length > 0) {
      selectedResult = stageResult;
      break;
    }
  }

  return selectedResult;
}

export function analyzePolygonCampsiteCandidates(
  polygon: CampsitePolygonPoint[],
  remotenessData?: RemotenessSnapshot | null,
  args?: { polygonId?: string | null; routeName?: string | null },
): CampsiteCandidateResult {
  const now = new Date().toISOString();
  const validPolygon = polygon.filter(isFinitePolygonPoint);
  const polygonId =
    args?.polygonId ??
    `polygon-${validPolygon.map((point) => `${point.latitude.toFixed(4)},${point.longitude.toFixed(4)}`).join('|')}`;
  const routeName = args?.routeName ?? 'Drawn Campsite Area';

  if (validPolygon.length < 3) {
    return {
      id: uuid(),
      routeIntelligenceId: polygonId,
      routeName,
      totalDistanceMiles: 0,
      estimatedDriveTimeHours: 0,
      candidates: [],
      suggestedCampsites: [],
      candidateCount: 0,
      totalSegments: 0,
      excludedSegments: 0,
      analyzedAt: now,
      scoringApplied: false,
      isShortRoute: false,
      overnightUnlikely: false,
      hasHighConfidence: false,
      bestConfidence: null,
      fallbackStage: CampsiteFallbackStage.LowerScoreModerately,
      fallbackMode: 'relaxed',
      criteriaBroadened: true,
      healthyThreshold: CAMPSITE_HEALTHY_THRESHOLD,
      minimumAcceptableThreshold: CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD,
      uiNotice: 'Draw a closed area to locate campsite options',
      analysisSource: 'polygon',
      polygonId,
    };
  }

  const candidatePoints = generatePolygonCampsiteCandidatePoints(validPolygon);
  const routeIntel = buildPolygonCandidateRouteIntel(validPolygon, polygonId, routeName, candidatePoints);
  const fallbackStage = getCampsiteFallbackStage(CampsiteFallbackStage.LowerScoreModerately);
  const rawCandidates = routeIntel.segments.map((segment, index): CampsiteCandidate => {
    const center = polygonCentroid(validPolygon);
    const fromCenter = distanceMi(
      { latitude: segment.coordinates[0], longitude: segment.coordinates[1] },
      center,
    );
    const remotenessBoost = Math.max(0, Math.min(14, Math.round((remotenessData?.score ?? 50) / 8)));
    const qualityScore = Math.max(0, Math.min(100, 72 + remotenessBoost - Math.round(fromCenter * 1.8) + (index % 3) * 4));
    return {
      segmentIndex: segment.segmentIndex,
      coordinates: segment.coordinates,
      distanceMiles: Number((((index + 3) / Math.max(routeIntel.segments.length + 5, 1)) * routeIntel.totalDistanceMiles).toFixed(1)),
      avgElevation: segment.avgElevation,
      elevationGain: segment.elevationGain,
      candidateReason: [
        'Inside selected campsite search area',
        'Predicted level terrain pocket',
        remotenessData?.tier ? `${remotenessData.tier} remoteness context` : 'Remote-context campsite scan',
      ],
      segmentRange: `Area ${index + 1}`,
      difficulty: segment.difficulty,
      qualityScore,
      suitabilityScore: 0,
      suitabilityLevel: 'LOW',
      estimatedArrivalHour: null,
      scoringBreakdown: {
        flatTerrainBonus: 0,
        remotenessBonus: 0,
        timingBonus: 0,
        elevationPenalty: 0,
        mountainPassPenalty: 0,
        idealTimingBonus: 0,
        tooEarlyPenalty: 0,
        tooLatePenalty: 0,
        shortRouteReduction: 0,
        overnightReduction: 0,
        reasons: [],
      },
      confidence: 'LOW',
      confidenceReasons: [],
      fallbackStage: fallbackStage.stage,
      fallbackMode: fallbackStage.mode,
      criteriaBroadened: true,
      credibilityTier: fallbackStage.credibilityTier,
    };
  });

  const scoredCandidates = scoreCampsiteCandidates(
    rawCandidates,
    routeIntel,
    null,
    remotenessData,
    fallbackStage,
  ).sort((a, b) => b.suitabilityScore - a.suitabilityScore || b.qualityScore - a.qualityScore);
  const suggestedCampsites = scoredCandidates.slice(0, MAX_SUGGESTED);
  const bestConfidence =
    suggestedCampsites.length > 0
      ? suggestedCampsites.reduce<ConfidenceLevel>((best, candidate) =>
          rankConfidence(candidate.confidence) > rankConfidence(best) ? candidate.confidence : best,
        'LOW')
      : null;

  return {
    id: uuid(),
    routeIntelligenceId: polygonId,
    routeName,
    totalDistanceMiles: routeIntel.totalDistanceMiles,
    estimatedDriveTimeHours: routeIntel.estimatedDriveTimeHours,
    candidates: scoredCandidates,
    suggestedCampsites,
    candidateCount: scoredCandidates.length,
    totalSegments: routeIntel.segments.length,
    excludedSegments: Math.max(0, routeIntel.segments.length - scoredCandidates.length),
    analyzedAt: now,
    scoringApplied: true,
    isShortRoute: false,
    overnightUnlikely: false,
    hasHighConfidence: suggestedCampsites.some((candidate) => candidate.confidence === 'HIGH'),
    bestConfidence,
    fallbackStage: fallbackStage.stage,
    fallbackMode: fallbackStage.mode,
    criteriaBroadened: true,
    healthyThreshold: CAMPSITE_HEALTHY_THRESHOLD,
    minimumAcceptableThreshold: CAMPSITE_MINIMUM_ACCEPTABLE_THRESHOLD,
    uiNotice: 'Showing campsite candidates inside selected drawing',
    analysisSource: 'polygon',
    polygonId,
  };
}


// ── Listeners ────────────────────────────────────────────────

type CampsiteListener = (result: CampsiteCandidateResult | null) => void;
const _listeners = new Set<CampsiteListener>();

function _notify(result: CampsiteCandidateResult | null) {
  _listeners.forEach(fn => {
    try { fn(result); } catch (e) { console.error(TAG, 'Listener error:', e); }
  });
}

// ── Internal State ───────────────────────────────────────────

let _currentResult: CampsiteCandidateResult | null = null;
let _candidateGenerationSequence = 0;
let _latestGeneration:
  | {
      ownerKey: string;
      requestToken: string;
      state: 'refreshing' | 'active' | 'cleared';
      reason: string;
      source: CampsiteCandidateOwnerSource;
      routeIntelligenceId?: string | null;
      polygonId?: string | null;
    }
  | null = null;

function createCandidateGenerationToken(): string {
  _candidateGenerationSequence += 1;
  return `campgen-${_candidateGenerationSequence}`;
}

function redactLocationBearingId(value: string | null | undefined): string | null {
  if (!value) return value ?? null;
  const hasCoordinatePairs = /-?\d{1,2}\.\d{3,}_-?\d{1,3}\.\d{3,}/.test(value);
  return hasCoordinatePairs ? 'coordinate-id-redacted' : value;
}

function buildOwnerKey(owner: CampsiteCandidateOwnerRef): string {
  if (owner.source === 'polygon') {
    return `polygon:${owner.polygonId ?? owner.routeIntelligenceId ?? 'unknown'}`;
  }
  if (owner.source === 'manual') {
    return 'manual';
  }
  return `route:${owner.routeIntelligenceId ?? 'unknown'}`;
}

function latestGenerationFromOwner(
  owner: CampsiteCandidateOwnerRef,
  requestToken: string,
  state: 'refreshing' | 'active' | 'cleared',
  reason: string,
) {
  return {
    ownerKey: buildOwnerKey(owner),
    requestToken,
    state,
    reason,
    source: owner.source,
    routeIntelligenceId: owner.routeIntelligenceId ?? null,
    polygonId: owner.polygonId ?? null,
  };
}

function isRouteUnknownToResolvedOwnerTransition(
  latest: NonNullable<typeof _latestGeneration>,
  owner: CampsiteCandidateOwnerRef,
  nextOwnerKey: string,
): boolean {
  return (
    latest.source === 'route' &&
    owner.source === 'route' &&
    latest.ownerKey === 'route:unknown' &&
    nextOwnerKey !== 'route:unknown' &&
    nextOwnerKey.startsWith('route:')
  );
}

function markRouteOwnerResolved(
  latest: NonNullable<typeof _latestGeneration>,
  owner: CampsiteCandidateOwnerRef,
  nextOwnerKey: string,
): void {
  const previousOwnerKey = latest.ownerKey;
  latest.ownerKey = nextOwnerKey;
  latest.routeIntelligenceId = owner.routeIntelligenceId ?? null;
  logCampsiteCandidateDebug('route_owner_resolved', {
    previousOwnerKey,
    nextOwnerKey,
    requestToken: latest.requestToken,
    routeIntelligenceId: redactLocationBearingId(owner.routeIntelligenceId),
  });
}

function resultOwnerRef(result: CampsiteCandidateResult): CampsiteCandidateOwnerRef {
  const source = result.source ?? result.analysisSource ?? 'route';
  return {
    source,
    routeIntelligenceId: result.routeIntelligenceId,
    polygonId: result.polygonId,
  };
}

function logCandidateSet(result: CampsiteCandidateResult, generatedCount = result.suggestedCampsites.length): void {
  const summary = result.viabilitySummary;
  const acceptedCount = summary?.acceptedCount ?? result.suggestedCampsites.length;
  const rejectedCount = summary?.rejectedCount ?? Math.max(0, generatedCount - acceptedCount);
  const failingFactors = summary?.failingFactors ?? [];
  logCampsiteCandidateDebug('viability_filter', {
    generationId: summary?.generationId ?? result.id,
    generatedCount,
    totalBeforeFiltering: summary?.totalBeforeFiltering ?? generatedCount,
    afterSafetyCount: summary?.afterSafetyCount ?? acceptedCount,
    afterScoreCount: summary?.afterScoreCount ?? acceptedCount,
    renderCount: summary?.renderCount ?? result.suggestedCampsites.length,
    acceptedCount,
    rejectedCount,
    activeThreshold: summary?.activeThreshold ?? null,
    fallbackTier: summary?.fallbackTier ?? null,
    tierCounts: summary?.tierCounts ?? null,
    failingFactors,
    source: result.source ?? result.analysisSource ?? 'unknown',
    routeIntelligenceId: redactLocationBearingId(result.routeIntelligenceId),
    polygonId: redactLocationBearingId(result.polygonId),
  });
  logCampsiteCandidateDebug('set', {
    generationId: result.id,
    candidateCount: result.candidateCount,
    renderCount: result.suggestedCampsites.length,
    source: result.source ?? result.analysisSource ?? 'unknown',
    routeIntelligenceId: redactLocationBearingId(result.routeIntelligenceId),
    polygonId: redactLocationBearingId(result.polygonId),
  });
}

function withCandidateOwnership(result: CampsiteCandidateResult): CampsiteCandidateResult {
  return {
    ...result,
    source: result.source ?? result.analysisSource ?? 'route',
    createdAt: result.createdAt ?? new Date().toISOString(),
  };
}

function buildCandidateKey(candidate: CampsiteCandidate): string {
  const record = candidate as CampsiteCandidate & { id?: string | null; latitude?: number; longitude?: number };
  const latitude = Number(record.latitude ?? candidate.coordinates?.[0]);
  const longitude = Number(record.longitude ?? candidate.coordinates?.[1]);
  return [
    record.id ?? candidate.segmentRange ?? candidate.segmentIndex ?? 'candidate',
    Number.isFinite(latitude) ? latitude.toFixed(5) : 'na',
    Number.isFinite(longitude) ? longitude.toFixed(5) : 'na',
  ].join('|');
}

const CAMPSITE_VIABILITY_TIER_RANK: Record<CampsiteViabilityTier, number> = {
  preferred: 4,
  good: 3,
  possible: 2,
  limited_confidence: 1,
  rejected_safety: 0,
};

const CAMPSITE_VIABILITY_FALLBACK_ORDER: CampsiteViabilityTier[] = [
  'preferred',
  'good',
  'possible',
  'limited_confidence',
];

function getViabilityTierThreshold(tier: CampsiteViabilityTier | null): number | undefined {
  switch (tier) {
    case 'preferred':
      return MIN_CAMPSITE_CORE_SCORE;
    case 'good':
      return CAMPSITE_GOOD_FALLBACK_SCORE;
    case 'possible':
      return CAMPSITE_POSSIBLE_FALLBACK_SCORE;
    case 'limited_confidence':
      return CAMPSITE_LIMITED_CONFIDENCE_SCORE;
    default:
      return undefined;
  }
}

function applyViabilityConfidence(candidate: CampsiteCandidate, tier: CampsiteViabilityTier): CampsiteCandidate {
  const evaluation = evaluateCampsiteCandidateViability(candidate);
  const confidence =
    tier === 'preferred'
      ? candidate.confidence
      : tier === 'good'
        ? candidate.confidence === 'HIGH'
          ? 'MEDIUM'
          : candidate.confidence
        : 'LOW';
  const label = evaluation.confidenceLabel;
  const fallbackReason =
    tier === 'preferred'
      ? null
      : tier === 'good'
        ? 'Good fallback candidate surfaced below preferred campsite threshold'
        : tier === 'possible'
          ? 'Possible lower-confidence campsite candidate surfaced by fallback tiers'
          : 'Limited confidence campsite candidate surfaced after broader fallback';
  return {
    ...candidate,
    confidence,
    viabilityTier: tier,
    viabilityConfidenceLabel: label,
    confidenceReasons:
      fallbackReason && !candidate.confidenceReasons.includes(fallbackReason)
        ? [...candidate.confidenceReasons, fallbackReason]
        : candidate.confidenceReasons,
  };
}

function applyLegacyCampsiteDisplayFilter(result: CampsiteCandidateResult): CampsiteCandidateResult {
  const source = result.source ?? result.analysisSource ?? 'route';
  if (source === 'manual') {
    return {
      ...result,
      candidateCount: result.suggestedCampsites.length,
      viabilitySummary: {
        generationId: result.id,
        generatedCount: result.suggestedCampsites.length,
        totalBeforeFiltering: result.suggestedCampsites.length,
        afterSafetyCount: result.suggestedCampsites.length,
        afterScoreCount: result.suggestedCampsites.length,
        renderCount: result.suggestedCampsites.length,
        acceptedCount: result.suggestedCampsites.length,
        rejectedCount: 0,
        activeThreshold: undefined,
        fallbackTier: null,
        tierCounts: {},
        failingFactors: [],
      },
    };
  }

  const suggestedKeys = new Set(result.suggestedCampsites.map(buildCandidateKey));
  const suggestedEvaluations = new Map<string, ReturnType<typeof evaluateCampsiteCandidateViability>>();
  const failingFactors = new Set<CampsiteCoreScoreKey>();
  const tierCounts: Partial<Record<CampsiteViabilityTier, number>> = {};
  const generationId = result.id;
  const routeIntelligenceId = redactLocationBearingId(result.routeIntelligenceId);
  const polygonId = redactLocationBearingId(result.polygonId);

  for (const candidate of result.suggestedCampsites) {
    const key = buildCandidateKey(candidate);
    const evaluation = evaluateCampsiteCandidateViability(candidate, {
      source,
      debugLog: true,
      generationId,
      routeIntelligenceId,
      polygonId,
      analysisLayer: 'display_filter',
    });
    suggestedEvaluations.set(key, evaluation);
    tierCounts[evaluation.tier] = (tierCounts[evaluation.tier] ?? 0) + 1;
    evaluation.failingScoreNames.forEach((factor) => failingFactors.add(factor));
  }

  const activeTier =
    CAMPSITE_VIABILITY_FALLBACK_ORDER.find((tier) =>
      result.suggestedCampsites.some((candidate) => {
        const evaluation = suggestedEvaluations.get(buildCandidateKey(candidate));
        return evaluation?.isViable && evaluation.tier === tier;
      }),
    ) ?? null;
  const activeTierRank = activeTier ? CAMPSITE_VIABILITY_TIER_RANK[activeTier] : 0;
  const acceptedKeys = new Set<string>();
  const acceptedSuggested = result.suggestedCampsites
    .filter((candidate) => {
      const key = buildCandidateKey(candidate);
      const evaluation = suggestedEvaluations.get(key);
      const accepted =
        !!evaluation?.isViable &&
        activeTier != null &&
        CAMPSITE_VIABILITY_TIER_RANK[evaluation.tier] >= activeTierRank;
      if (accepted) acceptedKeys.add(key);
      return accepted;
    })
    .map((candidate) => {
      const evaluation = suggestedEvaluations.get(buildCandidateKey(candidate));
      return evaluation ? applyViabilityConfidence(candidate, evaluation.tier) : candidate;
    });
  const acceptedCandidates = result.candidates.reduce<CampsiteCandidate[]>((accepted, candidate) => {
    const key = buildCandidateKey(candidate);
    if (!suggestedKeys.has(key)) return accepted;
    const evaluation =
      suggestedEvaluations.get(key) ??
      evaluateCampsiteCandidateViability(candidate, {
        source,
        debugLog: true,
        generationId,
        routeIntelligenceId,
        polygonId,
        analysisLayer: 'display_filter',
      });
    const isAccepted =
      acceptedKeys.has(key) ||
      (!!evaluation.isViable &&
        activeTier != null &&
        CAMPSITE_VIABILITY_TIER_RANK[evaluation.tier] >= activeTierRank);
    if (isAccepted) {
      accepted.push(applyViabilityConfidence(candidate, evaluation.tier));
    }
    return accepted;
  }, []);
  const bestConfidence =
    acceptedSuggested.length > 0
      ? acceptedSuggested.reduce<ConfidenceLevel>((best, candidate) =>
          rankConfidence(candidate.confidence) > rankConfidence(best) ? candidate.confidence : best,
        'LOW')
      : null;

  return {
    ...result,
    candidates: acceptedCandidates,
    suggestedCampsites: acceptedSuggested,
    candidateCount: acceptedSuggested.length,
    excludedSegments: Math.max(0, result.totalSegments - acceptedCandidates.length),
    hasHighConfidence: acceptedSuggested.some((candidate) => candidate.confidence === 'HIGH'),
    bestConfidence,
    viabilitySummary: {
      generationId,
      generatedCount: result.suggestedCampsites.length,
      acceptedCount: acceptedSuggested.length,
      rejectedCount: Math.max(0, result.suggestedCampsites.length - acceptedSuggested.length),
      totalBeforeFiltering: result.suggestedCampsites.length,
      afterSafetyCount: result.suggestedCampsites.filter((candidate) => {
        const evaluation = suggestedEvaluations.get(buildCandidateKey(candidate));
        return !!evaluation?.isViable;
      }).length,
      afterScoreCount: acceptedSuggested.length,
      renderCount: acceptedSuggested.length,
      activeThreshold: getViabilityTierThreshold(activeTier),
      fallbackTier: activeTier,
      tierCounts,
      failingFactors: Array.from(failingFactors),
    },
  };
}

function prepareCampsiteResultForDisplay(result: CampsiteCandidateResult): CampsiteCandidateResult {
  return applyLegacyCampsiteDisplayFilter(withCandidateOwnership(result));
}

// ── Persistence ──────────────────────────────────────────────

function loadStoredResult(): CampsiteCandidateResult | null {
  try {
    const raw = sGet(STORAGE_KEY);
    if (!raw) return null;
    return JSON.parse(raw);
  } catch { return null; }
}

function saveResult(result: CampsiteCandidateResult): void {
  try {
    sSet(STORAGE_KEY, JSON.stringify(result));
  } catch (e) {
    console.warn(TAG, 'Failed to save campsite candidates:', e);
  }
}

function clearStoredResult(): void {
  try {
    if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
      localStorage.removeItem(STORAGE_KEY);
      localStorage.removeItem(SUGGESTED_STORAGE_KEY);
    }
    delete mem[STORAGE_KEY];
    delete mem[SUGGESTED_STORAGE_KEY];
  } catch {}
}

// ══════════════════════════════════════════════════════════════
// PUBLIC API — campsiteCandidateEngine
// ══════════════════════════════════════════════════════════════

export const campsiteCandidateEngine = {
  /**
   * Subscribe to campsite candidate changes.
   * Returns unsubscribe function.
   */
  subscribe(listener: CampsiteListener): () => void {
    _listeners.add(listener);
    return () => { _listeners.delete(listener); };
  },

  /**
   * Analyze route for campsite candidates with Phase 2+3 scoring.
   * Stores result and notifies listeners.
   */
  analyze(
    routeIntel: RouteIntelligence,
    terrainIntel: TerrainIntelligence | null,
    remotenessData?: RemotenessSnapshot | null,
  ): CampsiteCandidateResult {
    const result = prepareCampsiteResultForDisplay({
      ...analyzeCampsiteCandidates(routeIntel, terrainIntel, remotenessData),
      analysisSource: 'route' as const,
      source: 'route' as const,
      polygonId: null,
    });
    _currentResult = result;
    logCandidateSet(result, result.viabilitySummary?.generatedCount);
    saveResult(result);
    _notify(result);
    return result;
  },

  /**
   * Mark a route/polygon candidate refresh as in-flight without clearing current
   * display state. The returned token must be supplied when publishing the result.
   */
  beginRefresh(options: CampsiteCandidateRefreshOptions): string {
    const requestToken = createCandidateGenerationToken();
    _latestGeneration = latestGenerationFromOwner(
      options,
      requestToken,
      'refreshing',
      options.reason,
    );
    logCampsiteCandidateDebug('refresh_started', {
      reason: options.reason,
      requestToken,
      source: options.source,
      routeIntelligenceId: redactLocationBearingId(options.routeIntelligenceId),
      polygonId: redactLocationBearingId(options.polygonId),
    });
    return requestToken;
  },

  /**
   * Publish a locator-produced result through the existing campsite engine state.
   * This keeps storage/subscriptions centralized while route and polygon locating
   * can be orchestrated by the campsite locator service.
   */
  publishResult(result: CampsiteCandidateResult, options: CampsiteCandidatePublishOptions = {}): CampsiteCandidateResult {
    const owner = resultOwnerRef(result);
    const ownerKey = buildOwnerKey(owner);
    if (options.requestToken && _latestGeneration) {
      const rejectReason =
        _latestGeneration.requestToken !== options.requestToken
          ? 'request_token_mismatch'
          : _latestGeneration.state === 'cleared'
            ? 'owner_cleared'
            : _latestGeneration.source !== owner.source
              ? 'source_mismatch'
              : _latestGeneration.ownerKey !== ownerKey &&
                  !isRouteUnknownToResolvedOwnerTransition(_latestGeneration, owner, ownerKey)
                ? 'owner_key_mismatch'
                : null;

      if (rejectReason) {
        logCampsiteCandidateDebug('stale_generation_ignored', {
          requestToken: options.requestToken,
          latestRequestToken: _latestGeneration.requestToken,
          reason: _latestGeneration.reason,
          rejectReason,
          ownerKey,
          latestOwnerKey: _latestGeneration.ownerKey,
          source: owner.source,
          routeIntelligenceId: redactLocationBearingId(owner.routeIntelligenceId),
          polygonId: redactLocationBearingId(owner.polygonId),
        });
        return _currentResult ?? result;
      }

      if (_latestGeneration.ownerKey !== ownerKey) {
        markRouteOwnerResolved(_latestGeneration, owner, ownerKey);
      }
    }
    const ownedResult = prepareCampsiteResultForDisplay(result);
    _currentResult = ownedResult;
    _latestGeneration = latestGenerationFromOwner(
      owner,
      options.requestToken ?? createCandidateGenerationToken(),
      'active',
      'publish_result',
    );
    logCandidateSet(ownedResult, ownedResult.viabilitySummary?.generatedCount);
    saveResult(ownedResult);
    _notify(ownedResult);
    return ownedResult;
  },

  /**
   * Analyze a completed map polygon for campsite candidates.
   * Stores result and notifies listeners.
   */
  analyzePolygon(
    polygon: CampsitePolygonPoint[],
    remotenessData?: RemotenessSnapshot | null,
    args?: { polygonId?: string | null; routeName?: string | null },
  ): CampsiteCandidateResult {
    const result = prepareCampsiteResultForDisplay(analyzePolygonCampsiteCandidates(polygon, remotenessData, args));
    _currentResult = result;
    logCandidateSet(result, result.viabilitySummary?.generatedCount);
    saveResult(result);
    _notify(result);
    return result;
  },

  /**
   * Get the current campsite candidate result (in-memory or from storage).
   */
  getCurrent(): CampsiteCandidateResult | null {
    if (_currentResult) return _currentResult;
    const stored = loadStoredResult();
    _currentResult = stored ? prepareCampsiteResultForDisplay(stored) : null;
    return _currentResult;
  },

  /**
   * Check if campsite analysis exists for a given route intelligence ID.
   */
  isCurrentFor(routeIntelligenceId: string): boolean {
    const current = this.getCurrent();
    return current != null && current.routeIntelligenceId === routeIntelligenceId;
  },

  /**
   * Check if analysis needs recomputation.
   * Returns true if no result exists or the route intelligence ID has changed.
   */
  needsRecompute(routeIntelligenceId: string): boolean {
    const current = this.getCurrent();
    if (!current) return true;
    return current.routeIntelligenceId !== routeIntelligenceId;
  },

  /**
   * Clear current campsite candidates.
   */
  clear(reason: string = 'unspecified', options: CampsiteCandidateClearOptions = {}): void {
    const previousCount = _currentResult?.suggestedCampsites.length ?? 0;
    const previousSource = _currentResult?.source ?? _currentResult?.analysisSource ?? 'none';
    const previousOwner = _currentResult ? resultOwnerRef(_currentResult) : null;
    const owner: CampsiteCandidateOwnerRef | null =
      previousOwner ??
      (options.source
        ? {
            source: options.source,
            routeIntelligenceId: options.routeIntelligenceId ?? null,
            polygonId: options.polygonId ?? null,
          }
        : null) ??
      null;
    const requestToken = owner ? createCandidateGenerationToken() : null;
    if (owner && requestToken) {
      _latestGeneration = latestGenerationFromOwner(
        owner,
        requestToken,
        'cleared',
        reason,
      );
    }
    _currentResult = null;
    clearStoredResult();
    _notify(null);
    logCampsiteCandidateDebug('clear_completed', {
      reason,
      requestToken,
      previousCount,
      previousSource,
      previousRouteIntelligenceId: redactLocationBearingId(previousOwner?.routeIntelligenceId),
      previousPolygonId: redactLocationBearingId(previousOwner?.polygonId),
    });
  },


  /**
   * Get the top N candidates by suitability score (Phase 2).
   */
  getTopCandidates(n: number = MAX_SUGGESTED): CampsiteCandidate[] {
    const current = this.getCurrent();
    if (!current) return [];
    return current.suggestedCampsites.slice(0, n);
  },

  /**
   * Get suggested campsites.
   */
  getSuggestedCampsites(): CampsiteCandidate[] {
    const current = this.getCurrent();
    if (!current) return [];
    return current.suggestedCampsites;
  },

  /**
   * Check if any suggested campsite has HIGH confidence (Phase 3).
   * Used by Expedition Brief to decide whether to mention camp zones.
   */
  hasHighConfidenceSuggestion(): boolean {
    const current = this.getCurrent();
    if (!current) return false;
    return current.hasHighConfidence;
  },

  /**
   * Get the best confidence level among suggested campsites (Phase 3).
   */
  getBestConfidence(): ConfidenceLevel | null {
    const current = this.getCurrent();
    if (!current) return null;
    return current.bestConfidence;
  },

  /**
   * Check if the route is considered short (Phase 3).
   */
  isShortRoute(): boolean {
    const current = this.getCurrent();
    if (!current) return false;
    return current.isShortRoute;
  },

  /**
   * Check if overnight stop is unlikely (Phase 3).
   */
  isOvernightUnlikely(): boolean {
    const current = this.getCurrent();
    if (!current) return false;
    return current.overnightUnlikely;
  },

  /**
   * Format distance as human-readable string.
   */
  formatDistance(miles: number): string {
    return `Mile ${miles.toFixed(0)}`;
  },

  /**
   * Format elevation as human-readable string with commas.
   */
  formatElevation(feet: number): string {
    return feet.toLocaleString('en-US');
  },

  /**
   * Format arrival time as human-readable string.
   */
  formatArrivalTime(hours: number | null): string {
    if (hours == null) return '—';
    const h = Math.floor(hours);
    const m = Math.round((hours - h) * 60);
    if (h === 0) return `${m}m`;
    if (m === 0) return `${h}h`;
    return `${h}h ${m}m`;
  },

  /**
   * Get a compact summary string.
   */
  getSummary(result: CampsiteCandidateResult): string {
    if (result.candidateCount === 0) return 'No campsite candidates detected';

    // Phase 3: Include route context
    if (result.isShortRoute) {
      return `Short route — ${result.candidateCount} candidate${result.candidateCount > 1 ? 's' : ''} (low confidence)`;
    }
    if (result.overnightUnlikely) {
      return `Quick trip — ${result.candidateCount} candidate${result.candidateCount > 1 ? 's' : ''} (overnight unlikely)`;
    }

    const suggested = result.suggestedCampsites.length;
    if (suggested > 0) {
      const topLevel = result.suggestedCampsites[0].suitabilityLevel;
      const topConf = result.suggestedCampsites[0].confidence;
      return `${suggested} suggested campsite${suggested > 1 ? 's' : ''} (best: ${topLevel}, ${topConf} confidence)`;
    }
    return `${result.candidateCount} campsite candidate${result.candidateCount > 1 ? 's' : ''} detected`;
  },

  /**
   * Get suitability level metadata for display.
   */
  getSuitabilityMeta(level: SuitabilityLevel): { label: string; color: string; icon: string } {
    switch (level) {
      case 'HIGH':
        return { label: 'HIGH', color: '#66BB6A', icon: 'star' };
      case 'MEDIUM':
        return { label: 'MEDIUM', color: '#FFB74D', icon: 'star-half' };
      case 'LOW':
      default:
        return { label: 'LOW', color: '#8A8A85', icon: 'star-outline' };
    }
  },

  /**
   * Get confidence level metadata for display (Phase 3).
   */
  getConfidenceMeta(level: ConfidenceLevel): { label: string; color: string; icon: string } {
    switch (level) {
      case 'HIGH':
        return { label: 'HIGH', color: '#66BB6A', icon: 'shield-checkmark' };
      case 'MEDIUM':
        return { label: 'MEDIUM', color: '#FFB74D', icon: 'shield-half' };
      case 'LOW':
      default:
        return { label: 'LOW', color: '#8A8A85', icon: 'shield-outline' };
    }
  },

  /**
   * Generate a campsite brief sentence for the Expedition Brief (Phase 3).
   * Only returns a sentence if at least one suggestion has HIGH confidence.
   * Returns null if no high-confidence suggestions exist.
   */
  generateCampsiteBrief(): string | null {
    const current = this.getCurrent();
    if (!current) return null;
    if (!current.hasHighConfidence) return null;
    if (current.suggestedCampsites.length === 0) return null;

    const highConfCount = current.suggestedCampsites.filter(c => c.confidence === 'HIGH').length;

    if (highConfCount > 1) {
      return 'Likely camp zones appear along the mid-to-late route.';
    }
    return 'A likely camp zone appears along the route.';
  },
};

export const campsiteCandidateEngineTestHooks = {
  prepareCampsiteResultForDisplay,
};

