import type {
  DispatchAssignment,
  DispatchCadEvent,
  DispatchCadLinkedContext,
  DispatchLinkedContext,
  DispatchPing,
  DispatchQueueItem,
  DispatchTeamMember,
  DispatchTimelineEvent,
} from './dispatchTypes';
import {
  createCadEventFromAiAdvisory,
  sortCadEvents,
} from './dispatchTypes';
import {
  type DispatchAdvisoryContext,
  createCadEventFromAdvisory,
  generateDispatchAdvisories,
  getTopDispatchAdvisory,
} from './dispatchAdvisoryEngine';

export const MOCK_DISPATCH_CONTEXTS: Record<string, DispatchLinkedContext> = {
  expedition: {
    id: 'expedition-ruby-ridge',
    type: 'expedition',
    title: 'Ruby Ridge Field Loop',
    subtitle: 'Primary expedition channel',
  },
  rallyPoint: {
    id: 'pin-rally-alpha',
    type: 'pin',
    title: 'Rally Point Alpha',
    subtitle: 'North wash turnout',
    coordinates: { latitude: 37.2142, longitude: -112.9418 },
  },
  hazardShelf: {
    id: 'pin-hazard-shelf-road',
    type: 'pin',
    title: 'Shelf Road Washout',
    subtitle: 'Hazard confirmation requested',
    coordinates: { latitude: 37.2215, longitude: -112.9341 },
  },
  waypointMesa: {
    id: 'waypoint-mesa-03',
    type: 'waypoint',
    title: 'Mesa Waypoint 03',
    subtitle: 'Route scout checkpoint',
    coordinates: { latitude: 37.2294, longitude: -112.9264 },
  },
  routeSegment: {
    id: 'route-segment-north-spur',
    type: 'route_segment',
    title: 'North Spur Connector',
    subtitle: 'Scout before convoy commit',
    routeSegmentId: 'north-spur-connector',
  },
  resourceWater: {
    id: 'resource-water-fuel',
    type: 'resource',
    title: 'Fuel / Water Reserve',
    subtitle: 'Resource check before camp push',
  },
  vehicleLead: {
    id: 'vehicle-lead-rig',
    type: 'vehicle',
    title: 'Lead Vehicle',
    subtitle: 'Recovery gear and fuel status',
  },
  powerGlacier: {
    id: 'power-glacier-delta-mini',
    type: 'power',
    title: 'Glacier / Delta Mini Power',
    subtitle: 'Fridge and auxiliary battery status',
  },
};

export const MOCK_DISPATCH_TEAM_MEMBERS: DispatchTeamMember[] = [
  {
    id: 'member-logan',
    displayName: 'Logan Pierce',
    callSign: 'Command',
    role: 'owner',
    status: 'connected',
    lastSeenAt: '2026-04-24T18:41:00Z',
    currentContext: MOCK_DISPATCH_CONTEXTS.expedition,
    coordinates: { latitude: 37.2139, longitude: -112.942 },
    batteryPercent: 88,
    syncState: 'delivered',
    notes: 'Holding dispatch and convoy timing.',
  },
  {
    id: 'member-mara',
    displayName: 'Mara Chen',
    callSign: 'Scout',
    role: 'member',
    status: 'on_route',
    lastSeenAt: '2026-04-24T18:39:00Z',
    currentContext: MOCK_DISPATCH_CONTEXTS.routeSegment,
    coordinates: { latitude: 37.2241, longitude: -112.9309 },
    batteryPercent: 64,
    syncState: 'seen',
    notes: 'Scouting north spur before main vehicle movement.',
  },
  {
    id: 'member-ellis',
    displayName: 'Ellis Grant',
    callSign: 'Medic',
    role: 'member',
    status: 'at_waypoint',
    lastSeenAt: '2026-04-24T18:37:00Z',
    currentContext: MOCK_DISPATCH_CONTEXTS.waypointMesa,
    coordinates: { latitude: 37.2294, longitude: -112.9264 },
    batteryPercent: 72,
    syncState: 'acknowledged',
    notes: 'Standing by at Mesa Waypoint 03.',
  },
  {
    id: 'member-nia',
    displayName: 'Nia Alvarez',
    callSign: 'Quartermaster',
    role: 'member',
    status: 'needs_check_in',
    lastSeenAt: '2026-04-24T18:18:00Z',
    currentContext: MOCK_DISPATCH_CONTEXTS.resourceWater,
    batteryPercent: 41,
    syncState: 'sent',
    notes: 'Fuel and water count due before camp push.',
  },
  {
    id: 'member-owen',
    displayName: 'Owen Brooks',
    callSign: 'Tail',
    role: 'member',
    status: 'offline',
    lastSeenAt: '2026-04-24T17:56:00Z',
    currentContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    batteryPercent: 29,
    syncState: 'queued',
    notes: 'Last reported at Rally Point Alpha before signal drop.',
  },
];

export const MOCK_DISPATCH_ASSIGNMENTS: DispatchAssignment[] = [
  {
    id: 'assignment-hazard-scout',
    queueItemId: 'queue-hazard-confirmation',
    assigneeMemberId: 'member-mara',
    status: 'in_progress',
    assignedAt: '2026-04-24T18:22:00Z',
    acceptedAt: '2026-04-24T18:23:00Z',
    notes: 'Confirm passability and mark bypass if needed.',
  },
  {
    id: 'assignment-resource-check',
    queueItemId: 'queue-fuel-water-check',
    assigneeMemberId: 'member-nia',
    status: 'offered',
    assignedAt: '2026-04-24T18:28:00Z',
    notes: 'Awaiting check-in from resource lead.',
  },
  {
    id: 'assignment-power-status',
    queueItemId: 'queue-power-status',
    assigneeMemberId: 'member-logan',
    status: 'accepted',
    assignedAt: '2026-04-24T18:33:00Z',
    acceptedAt: '2026-04-24T18:34:00Z',
  },
];

export const MOCK_DISPATCH_QUEUE_ITEMS: DispatchQueueItem[] = [
  {
    id: 'queue-hazard-confirmation',
    title: 'Confirm shelf road washout',
    detail: 'Scout the marked hazard pin and report whether the convoy can pass or needs the bypass.',
    status: 'in_progress',
    priority: 'critical',
    createdAt: '2026-04-24T18:20:00Z',
    updatedAt: '2026-04-24T18:31:00Z',
    createdByMemberId: 'member-logan',
    assignedMemberIds: ['member-mara'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.hazardShelf,
    escalationState: 'escalated',
    deliveryState: 'accepted',
    dueAt: '2026-04-24T18:45:00Z',
    tags: ['hazard', 'route'],
  },
  {
    id: 'queue-rally-alpha',
    title: 'Rally Point Alpha check-in',
    detail: 'Confirm all team members can reach Rally Point Alpha before committing to the north spur.',
    status: 'pending_response',
    priority: 'high',
    createdAt: '2026-04-24T18:24:00Z',
    updatedAt: '2026-04-24T18:36:00Z',
    createdByMemberId: 'member-logan',
    assignedMemberIds: ['member-owen', 'member-ellis'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    escalationState: 'recommended',
    deliveryState: 'sent',
    dueAt: '2026-04-24T18:50:00Z',
    tags: ['rally', 'check-in'],
  },
  {
    id: 'queue-fuel-water-check',
    title: 'Fuel and water reserve check',
    detail: 'Update remaining fuel, potable water, and emergency reserve before camp push.',
    status: 'assigned',
    priority: 'high',
    createdAt: '2026-04-24T18:27:00Z',
    updatedAt: '2026-04-24T18:28:00Z',
    createdByMemberId: 'member-logan',
    assignedMemberIds: ['member-nia'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.resourceWater,
    escalationState: 'monitor',
    deliveryState: 'delivered',
    dueAt: '2026-04-24T19:00:00Z',
    tags: ['resource', 'fuel', 'water'],
  },
  {
    id: 'queue-route-scout',
    title: 'Scout North Spur Connector',
    detail: 'Verify grade, turn radius, and turnaround options for the lead and tail vehicles.',
    status: 'in_progress',
    priority: 'normal',
    createdAt: '2026-04-24T18:15:00Z',
    updatedAt: '2026-04-24T18:39:00Z',
    createdByMemberId: 'member-logan',
    assignedMemberIds: ['member-mara'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.routeSegment,
    escalationState: 'none',
    deliveryState: 'seen',
    tags: ['route', 'scout'],
  },
  {
    id: 'queue-assist-tail',
    title: 'Assist tail vehicle comms gap',
    detail: 'Attempt short-range relay and confirm whether Tail is stopped, moving, or out of coverage.',
    status: 'blocked',
    priority: 'critical',
    createdAt: '2026-04-24T18:32:00Z',
    updatedAt: '2026-04-24T18:40:00Z',
    createdByMemberId: 'member-logan',
    assignedMemberIds: ['member-ellis'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    escalationState: 'recommended',
    deliveryState: 'no_response',
    dueAt: '2026-04-24T18:48:00Z',
    tags: ['assist', 'offline'],
  },
  {
    id: 'queue-power-status',
    title: 'Glacier and Delta Mini power status',
    detail: 'Confirm fridge draw, auxiliary battery state, and whether power reserve supports overnight camp.',
    status: 'new',
    priority: 'normal',
    createdAt: '2026-04-24T18:34:00Z',
    updatedAt: '2026-04-24T18:34:00Z',
    createdByMemberId: 'member-logan',
    assignedMemberIds: ['member-logan'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.powerGlacier,
    escalationState: 'none',
    deliveryState: 'draft',
    tags: ['power', 'resource'],
  },
];

export const MOCK_DISPATCH_PINGS: DispatchPing[] = [
  {
    id: 'ping-rally-alpha',
    type: 'rally',
    priority: 'high',
    status: 'sent',
    message: 'Rally at Alpha and confirm arrival window.',
    createdAt: '2026-04-24T18:24:00Z',
    createdByMemberId: 'member-logan',
    targetMemberIds: ['member-owen', 'member-ellis', 'member-nia'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    escalationState: 'recommended',
    responseDueAt: '2026-04-24T18:50:00Z',
    acknowledgedByMemberIds: ['member-ellis'],
  },
  {
    id: 'ping-hazard-confirm',
    type: 'hazard',
    priority: 'critical',
    status: 'accepted',
    message: 'Confirm shelf road hazard and send pass/no-pass.',
    createdAt: '2026-04-24T18:21:00Z',
    createdByMemberId: 'member-logan',
    targetMemberIds: ['member-mara'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.hazardShelf,
    escalationState: 'escalated',
    responseDueAt: '2026-04-24T18:45:00Z',
    acknowledgedByMemberIds: ['member-mara'],
  },
  {
    id: 'ping-resource-check',
    type: 'resource',
    priority: 'high',
    status: 'delivered',
    message: 'Send fuel and water reserve counts before camp push.',
    createdAt: '2026-04-24T18:28:00Z',
    createdByMemberId: 'member-logan',
    targetMemberIds: ['member-nia'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.resourceWater,
    escalationState: 'monitor',
    responseDueAt: '2026-04-24T19:00:00Z',
  },
  {
    id: 'ping-route-scout',
    type: 'route',
    priority: 'normal',
    status: 'seen',
    message: 'Scout North Spur Connector and mark turnaround options.',
    createdAt: '2026-04-24T18:16:00Z',
    createdByMemberId: 'member-logan',
    targetMemberIds: ['member-mara'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.routeSegment,
    escalationState: 'none',
    acknowledgedByMemberIds: ['member-mara'],
  },
  {
    id: 'ping-tail-assist',
    type: 'assist',
    priority: 'critical',
    status: 'no_response',
    message: 'Tail vehicle comms gap. Relay status if you have line of sight.',
    createdAt: '2026-04-24T18:33:00Z',
    createdByMemberId: 'member-logan',
    targetMemberIds: ['member-owen', 'member-ellis'],
    linkedContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    escalationState: 'recommended',
    responseDueAt: '2026-04-24T18:48:00Z',
  },
];

export const MOCK_DISPATCH_TIMELINE_EVENTS: DispatchTimelineEvent[] = [
  {
    id: 'timeline-route-scout-start',
    type: 'assignment_created',
    title: 'Route scout assigned',
    detail: 'Scout accepted North Spur Connector verification.',
    occurredAt: '2026-04-24T18:16:00Z',
    priority: 'normal',
    memberIds: ['member-mara'],
    actor: 'Dispatch',
    target: 'Scout',
    linkedContext: MOCK_DISPATCH_CONTEXTS.routeSegment,
    queueItemId: 'queue-route-scout',
    deliveryState: 'seen',
    escalationState: 'none',
  },
  {
    id: 'timeline-hazard-escalated',
    type: 'queue_escalated',
    title: 'Hazard confirmation escalated',
    detail: 'Shelf road washout is now critical until passability is confirmed.',
    occurredAt: '2026-04-24T18:22:00Z',
    priority: 'critical',
    memberIds: ['member-logan', 'member-mara'],
    actor: 'Command',
    target: 'Scout',
    linkedContext: MOCK_DISPATCH_CONTEXTS.hazardShelf,
    queueItemId: 'queue-hazard-confirmation',
    deliveryState: 'accepted',
    escalationState: 'escalated',
  },
  {
    id: 'timeline-rally-ping',
    type: 'ping_created',
    title: 'Rally ping sent',
    detail: 'Team ping sent for Rally Point Alpha arrival confirmation.',
    occurredAt: '2026-04-24T18:24:00Z',
    priority: 'high',
    memberIds: ['member-owen', 'member-ellis', 'member-nia'],
    actor: 'Command',
    target: '3 members',
    linkedContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    pingId: 'ping-rally-alpha',
    deliveryState: 'sent',
    escalationState: 'recommended',
  },
  {
    id: 'timeline-resource-check',
    type: 'resource_check_requested',
    title: 'Resource check opened',
    detail: 'Fuel and water reserve check assigned before camp push.',
    occurredAt: '2026-04-24T18:28:00Z',
    priority: 'high',
    memberIds: ['member-nia'],
    actor: 'Command',
    target: 'Quartermaster',
    linkedContext: MOCK_DISPATCH_CONTEXTS.resourceWater,
    queueItemId: 'queue-fuel-water-check',
    deliveryState: 'delivered',
    escalationState: 'monitor',
  },
  {
    id: 'timeline-tail-offline',
    type: 'member_stale',
    title: 'Tail member offline',
    detail: 'Tail has not checked in since Rally Point Alpha.',
    occurredAt: '2026-04-24T18:32:00Z',
    priority: 'critical',
    memberIds: ['member-owen'],
    actor: 'Dispatch',
    target: 'Tail',
    linkedContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    deliveryState: 'no_response',
    escalationState: 'recommended',
  },
  {
    id: 'timeline-assist-request',
    type: 'assist_request_created',
    title: 'Assist request sent',
    detail: 'Relay requested for tail vehicle comms gap.',
    occurredAt: '2026-04-24T18:33:00Z',
    priority: 'critical',
    memberIds: ['member-owen', 'member-ellis'],
    actor: 'Command',
    target: 'Tail, Medic',
    linkedContext: MOCK_DISPATCH_CONTEXTS.rallyPoint,
    pingId: 'ping-tail-assist',
    deliveryState: 'no_response',
    escalationState: 'recommended',
  },
  {
    id: 'timeline-power-status',
    type: 'resource_check_requested',
    title: 'Power status queued',
    detail: 'Glacier fridge and Delta Mini reserve check added to dispatch.',
    occurredAt: '2026-04-24T18:34:00Z',
    priority: 'normal',
    memberIds: ['member-logan'],
    actor: 'Dispatch',
    target: 'Command',
    linkedContext: MOCK_DISPATCH_CONTEXTS.powerGlacier,
    queueItemId: 'queue-power-status',
    deliveryState: 'draft',
    escalationState: 'none',
  },
  {
    id: 'timeline-sync-hold',
    type: 'sync',
    title: 'Offline delivery watch',
    detail: 'Dispatch is tracking queued updates until all members recover connectivity.',
    occurredAt: '2026-04-24T18:40:00Z',
    priority: 'high',
    memberIds: ['member-logan', 'member-owen'],
    actor: 'Dispatch',
    target: 'Command, Tail',
    linkedContext: MOCK_DISPATCH_CONTEXTS.expedition,
    deliveryState: 'queued',
    escalationState: 'monitor',
  },
];

export const MOCK_DISPATCH_CAD_CONTEXTS: Record<string, DispatchCadLinkedContext> = {
  expedition: {
    id: 'expedition-ruby-ridge',
    type: 'expedition',
    title: 'Ruby Ridge Field Loop',
    subtitle: 'Primary expedition channel',
  },
  currentLocation: {
    id: 'current-location-command',
    type: 'current_location',
    title: 'Current Location',
    subtitle: 'Command vehicle GPS fix',
    coordinates: { latitude: 37.2139, longitude: -112.942 },
  },
  rallyPoint: {
    id: 'pin-rally-alpha',
    type: 'pin',
    title: 'Rally Point Alpha',
    subtitle: 'North wash turnout',
    coordinates: { latitude: 37.2142, longitude: -112.9418 },
  },
  hazardShelf: {
    id: 'pin-hazard-shelf-road',
    type: 'pin',
    title: 'Shelf Road Washout',
    subtitle: 'Passability confirmation requested',
    coordinates: { latitude: 37.2215, longitude: -112.9341 },
  },
  routeSegment: {
    id: 'route-segment-north-spur',
    type: 'route_segment',
    title: 'North Spur Connector',
    subtitle: 'Scout before convoy commit',
    routeSegmentId: 'north-spur-connector',
  },
  weatherCell: {
    id: 'weather-cell-west-ridge',
    type: 'weather',
    title: 'West Ridge Weather Cell',
    subtitle: 'Gust front approaching route corridor',
  },
  terrainShelf: {
    id: 'terrain-shelf-road',
    type: 'terrain',
    title: 'Shelf Road Terrain',
    subtitle: 'Loose edge and washout exposure',
  },
  streamRefill: {
    id: 'map-stream-cottonwood',
    type: 'manual',
    title: 'Cottonwood Stream',
    subtitle: 'Possible water refill opportunity near the route',
  },
  vehicleLead: {
    id: 'vehicle-lead-rig',
    type: 'vehicle',
    title: 'Lead Vehicle',
    subtitle: 'Recovery gear and fuel status',
  },
  resourceWater: {
    id: 'resource-water-fuel',
    type: 'resource',
    title: 'Fuel / Water Reserve',
    subtitle: 'Resource check before camp push',
  },
};

const MOCK_BASE_DISPATCH_CAD_EVENTS: DispatchCadEvent[] = sortCadEvents([
  createCadEventFromAiAdvisory({
    id: 'cad-ai-north-spur-risk',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:41:00Z',
    title: 'Hold north spur commit',
    summary: 'AI recommends holding convoy movement until shelf road passability is confirmed.',
    details: 'Critical hazard and assist events are active. Keep the expedition channel staged at Rally Point Alpha until passability is confirmed.',
    priority: 'high',
    status: 'active',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.routeSegment,
    metadata: {
      confidence: 0.84,
      contributingEventIds: ['cad-hazard-confirmation', 'cad-assist-comms-gap'],
    },
  }),
  {
    id: 'cad-hazard-confirmation',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:21:00Z',
    type: 'hazard',
    priority: 'critical',
    title: 'Hazard confirmation requested',
    summary: 'Confirm shelf road hazard and send pass/no-pass.',
    details: 'Expedition channel hazard ping is active for the marked shelf road washout.',
    status: 'active',
    source: 'team_ping',
    createdBy: 'Dispatch',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.hazardShelf,
    metadata: {
      cadSeed: 'hazard-confirmation',
      channelScope: 'expedition',
      requireAcknowledgment: true,
    },
  },
  {
    id: 'cad-assist-comms-gap',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:33:00Z',
    type: 'assist',
    priority: 'critical',
    title: 'Comms assist active',
    summary: 'Short-range relay requested for a route communication gap.',
    details: 'Attempt short-range relay and confirm movement state through the expedition channel.',
    status: 'active',
    source: 'assist_request',
    createdBy: 'Dispatch',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.rallyPoint,
    metadata: {
      cadSeed: 'comms-assist',
      assistType: 'comms',
      channelScope: 'expedition',
      requireAcknowledgment: true,
    },
  },
  {
    id: 'cad-check-in-waypoint',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:37:00Z',
    type: 'check_in',
    priority: 'normal',
    title: 'Waypoint check-in',
    summary: 'Logan checked in at Mesa Waypoint 03.',
    details: 'Check-in response received for the expedition channel at Mesa Waypoint 03.',
    status: 'acknowledged',
    source: 'check_in',
    createdBy: 'Logan',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.routeSegment,
    metadata: {
      cadSeed: 'waypoint-check-in',
      checkInStatus: 'at_waypoint',
      channelScope: 'expedition',
    },
  },
  {
    id: 'cad-resource-update-requested',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:28:00Z',
    type: 'resource',
    priority: 'high',
    title: 'Resource update requested',
    summary: 'Expedition channel fuel and water reserve update requested before camp push.',
    details: 'Send fuel and water reserve counts before committing to the remote segment.',
    status: 'active',
    source: 'team_ping',
    createdBy: 'Dispatch',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.resourceWater,
    metadata: {
      cadSeed: 'resource-check',
      channelScope: 'expedition',
      requireAcknowledgment: true,
    },
  },
  {
    id: 'cad-weather-west-ridge',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:29:00Z',
    type: 'weather',
    priority: 'high',
    title: 'Gust front approaching',
    summary: 'Weather strip reports gusts increasing along the west ridge corridor.',
    details: 'Monitor the ridge exposure before committing taller vehicles to the shelf road segment.',
    status: 'new',
    source: 'system',
    createdBy: 'ECS Weather',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.weatherCell,
    metadata: {
      windGustMph: 34,
      observedAt: '2026-04-24T18:28:00Z',
    },
  },
  {
    id: 'cad-route-scout-in-progress',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:39:00Z',
    type: 'route',
    priority: 'normal',
    title: 'Route scout in progress',
    summary: 'North Spur Connector route check is active in the expedition channel.',
    details: 'Verify grade, turn radius, and turnaround options before committing vehicles.',
    status: 'acknowledged',
    source: 'manual',
    createdBy: 'Dispatch',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.routeSegment,
    metadata: {
      cadSeed: 'route-scout',
      channelScope: 'expedition',
    },
  },
  {
    id: 'cad-system-offline-delivery-watch',
    expeditionId: 'expedition-ruby-ridge',
    timestamp: '2026-04-24T18:40:00Z',
    type: 'system',
    priority: 'normal',
    title: 'Offline delivery watch',
    summary: 'Dispatch is holding queued updates until channel connectivity recovers.',
    details: 'Queued delivery state remains visible in the CAD feed; active operations can continue locally.',
    status: 'queued',
    source: 'offline_sync',
    createdBy: 'ECS Sync',
    linkedContext: MOCK_DISPATCH_CAD_CONTEXTS.expedition,
    metadata: {
      queuedCount: 2,
      channelScope: 'expedition',
    },
  },
]);

export const MOCK_DISPATCH_ADVISORY_CONTEXT: DispatchAdvisoryContext = {
  expeditionId: 'expedition-ruby-ridge',
  now: '2026-04-24T18:42:00Z',
  weatherAlerts: [
    {
      id: 'weather-severe-west-ridge',
      title: 'Severe storm warning',
      severity: 'critical',
      summary: 'Severe thunderstorm warning near the west ridge route corridor.',
    },
  ],
  windMph: 52,
  stormRisk: 'severe',
  precipitationChance: 80,
  terrain: {
    difficulty: 'high',
    surface: 'loose shelf road',
  },
  route: {
    activeSegmentName: 'North Spur Connector',
    remoteSegmentAhead: true,
    exposure: 'high',
  },
  resources: {
    waterPercent: 24,
    fuelPercent: 32,
    foodStatus: 'ok',
    medicalStatus: 'ok',
    recoveryGearStatus: 'caution',
  },
  vehicleTelemetry: {
    engineTempF: 232,
    tirePressureLow: true,
    batteryChargingIssue: false,
    engineAlert: false,
    genericAlert: 'Vehicle temperature elevated before exposed climb.',
  },
  recentCadEvents: MOCK_BASE_DISPATCH_CAD_EVENTS,
  mapContexts: Object.values(MOCK_DISPATCH_CAD_CONTEXTS),
};

export const MOCK_DISPATCH_ADVISORIES = generateDispatchAdvisories(MOCK_DISPATCH_ADVISORY_CONTEXT);

export const MOCK_TOP_DISPATCH_ADVISORY = getTopDispatchAdvisory(MOCK_DISPATCH_ADVISORIES);

export const MOCK_DISPATCH_CAD_EVENTS: DispatchCadEvent[] = sortCadEvents([
  ...MOCK_BASE_DISPATCH_CAD_EVENTS,
  ...MOCK_DISPATCH_ADVISORIES
    .filter((advisory) => advisory.priority === 'critical')
    .map((advisory) => createCadEventFromAdvisory(advisory, MOCK_DISPATCH_ADVISORY_CONTEXT.now)),
]);
