import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { SafeIcon as Ionicons } from '../SafeIcon';

import { TACTICAL } from '../../lib/theme';
import type { DispatchEvent } from '../../lib/dispatchTypes';
import { EVENT_TYPE_META } from '../../lib/dispatchTypes';

interface Props {
  event: DispatchEvent;
}

function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  const now = new Date();
  const diffMs = now.getTime() - d.getTime();
  const diffMin = Math.floor(diffMs / 60000);
  const diffHr = Math.floor(diffMs / 3600000);

  if (diffMin < 1) return 'Just now';
  if (diffMin < 60) return `${diffMin}m ago`;
  if (diffHr < 24) return `${diffHr}h ago`;

  return d.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function getCreatorLabel(event: DispatchEvent): string | null {
  if (event.created_by_display_name) return event.created_by_display_name;
  if (event.created_by_email) {
    const local = event.created_by_email.split('@')[0];
    return local.charAt(0).toUpperCase() + local.slice(1);
  }
  return null;
}

export default function DispatchEventCard({ event }: Props) {
  const meta = EVENT_TYPE_META[event.event_type] || EVENT_TYPE_META.status_update;
  const isCritical = event.priority === 'critical';
  const isAutoGenerated = event.metadata?.auto_generated === true;
  const creatorLabel = getCreatorLabel(event);

  return (
    <View style={[styles.card, isCritical && styles.cardCritical]}>
      {/* Left accent bar */}
      <View style={[styles.accentBar, { backgroundColor: meta.color }]} />

      <View style={styles.body}>
        {/* Top row: icon + type label + timestamp + critical chip */}
        <View style={styles.topRow}>
          <View style={[styles.typeIcon, { borderColor: `${meta.color}40` }]}>
            <Ionicons name={meta.icon as any} size={14} color={meta.color} />
          </View>
          <Text style={[styles.typeLabel, { color: meta.color }]}>{meta.label.toUpperCase()}</Text>

          {isCritical && (
            <View style={styles.criticalChip}>
              <Text style={styles.criticalChipText}>CRITICAL</Text>
            </View>
          )}

          {isAutoGenerated && (
            <View style={styles.autoChip}>
              <Ionicons name="flash-outline" size={8} color={TACTICAL.textMuted} />
              <Text style={styles.autoChipText}>AUTO</Text>
            </View>
          )}

          <View style={{ flex: 1 }} />
          <Text style={styles.timestamp}>{formatTimestamp(event.created_at)}</Text>
        </View>

        {/* Headline */}
        <Text style={styles.headline}>{event.headline}</Text>

        {/* Detail */}
        {event.detail ? (
          <Text style={styles.detail}>{event.detail}</Text>
        ) : null}

        {/* Bottom row: creator + location */}
        <View style={styles.bottomRow}>
          {/* Creator */}
          {creatorLabel && (
            <View style={styles.creatorRow}>
              <Ionicons name="person-outline" size={10} color={TACTICAL.textMuted} />
              <Text style={styles.creatorText}>{creatorLabel}</Text>
            </View>
          )}

          {/* Location */}
          {event.location_enabled && (event.location_label || (event.latitude != null && event.longitude != null)) && (
            <View style={styles.locationRow}>
              <Ionicons name="navigate-outline" size={10} color={TACTICAL.textMuted} />
              <Text style={styles.locationText}>
                {event.location_label || `${event.latitude?.toFixed(5)}, ${event.longitude?.toFixed(5)}`}
              </Text>
              {event.location_label && event.latitude != null && (
                <Text style={styles.locationCoords}>
                  {event.latitude.toFixed(4)}, {event.longitude?.toFixed(4)}
                </Text>
              )}
            </View>
          )}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.18)',
    borderWidth: 1,
    borderColor: TACTICAL.border,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 8,
  },
  cardCritical: {
    borderColor: 'rgba(196, 138, 44, 0.4)',
    backgroundColor: 'rgba(196, 138, 44, 0.04)',
  },
  accentBar: {
    width: 3,
  },
  body: {
    flex: 1,
    padding: 12,
    paddingLeft: 10,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  typeIcon: {
    width: 24,
    height: 24,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderWidth: 1,
  },
  typeLabel: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  criticalChip: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: TACTICAL.amber,
    backgroundColor: 'rgba(196, 138, 44, 0.08)',
  },
  criticalChipText: {
    fontSize: 8,
    fontWeight: '900',
    color: TACTICAL.amber,
    letterSpacing: 1.5,
  },
  autoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(138, 138, 133, 0.15)',
  },
  autoChipText: {
    fontSize: 7,
    fontWeight: '800',
    color: TACTICAL.textMuted,
    letterSpacing: 1,
  },
  timestamp: {
    fontSize: 10,
    fontWeight: '600',
    color: TACTICAL.textMuted,
    fontFamily: 'Courier',
  },
  headline: {
    fontSize: 13,
    fontWeight: '800',
    color: TACTICAL.text,
    letterSpacing: 0.3,
    lineHeight: 18,
  },
  detail: {
    fontSize: 12,
    fontWeight: '400',
    color: TACTICAL.textMuted,
    marginTop: 4,
    lineHeight: 17,
  },
  bottomRow: {
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: 'rgba(62, 79, 60, 0.12)',
    gap: 4,
  },
  creatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  creatorText: {
    fontSize: 10,
    fontWeight: '600',
    color: TACTICAL.textMuted,
    letterSpacing: 0.3,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  locationText: {
    fontSize: 10,
    fontWeight: '700',
    color: TACTICAL.textMuted,
    letterSpacing: 0.5,
  },
  locationCoords: {
    fontSize: 9,
    fontWeight: '500',
    color: TACTICAL.textMuted,
    fontFamily: 'Courier',
    marginLeft: 4,
    opacity: 0.7,
  },
});



