import type { ExpeditionReadinessInput } from './expeditionReadinessTypes';

const now = '2026-05-13T18:00:00.000Z';

export const completeReadyReadinessFixture: ExpeditionReadinessInput = {
  readinessProfile: 'unknown',
  capturedAt: now,
  plannedDepartureAt: '2026-05-13T19:00:00.000Z',
  route: {
    routeId: 'route-white-rim-loop',
    name: 'White Rim Loop Segment Plan',
    distanceMiles: 72,
    difficulty: 'moderate',
    riskLevel: 'low',
    routeConfidence: 'high',
    knownHazards: [],
    source: 'live',
    updatedAt: now,
  },
  activeVehicle: {
    vehicleId: 'fleet-4runner',
    label: '4Runner Trail Build',
    profileComplete: true,
    gvwrUsagePct: 82,
    payloadRemainingLbs: 720,
    vehicleFitConfidence: 'high',
    source: 'manual',
    updatedAt: now,
  },
  weather: {
    riskLevel: 'low',
    severeAlertActive: false,
    windMph: 12,
    confidence: 'high',
    source: 'live',
    updatedAt: now,
  },
  daylight: {
    minutesRemainingAtArrival: 150,
    arrivalAfterDark: false,
    confidence: 'high',
    source: 'inferred',
    updatedAt: now,
    isInferred: true,
  },
  offline: {
    packageStatus: 'ready',
    routeDownloaded: true,
    routeGeometryCached: true,
    mapsDownloaded: true,
    mapTilesCachedForRoute: true,
    campIntelDownloaded: true,
    campCandidatesCached: true,
    bailoutPointsCached: true,
    weatherSnapshotAvailable: true,
    fuelTownRoadReferencesCached: true,
    emergencyDocsAvailable: true,
    emergencyPacketAvailable: true,
    currentRoutePackageFresh: true,
    cachedTileCount: 620,
    cachedRegionCount: 2,
    isRemoteRoute: false,
    isOnline: true,
    source: 'cached',
    updatedAt: now,
  },
  campCandidates: [{
    id: 'camp-1',
    name: 'Mineral Bottom zone candidate',
    legalAccessConfidence: 'high',
    officialConfirmation: true,
    accessStatus: 'open',
    suitabilityScore: 88,
    source: 'cached',
    updatedAt: now,
  }],
  fuel: {
    rangeRemainingMiles: 240,
    routeDistanceRemainingMiles: 72,
    fuelPercent: 78,
    source: 'live',
    updatedAt: now,
  },
  power: {
    runtimeHoursRemaining: 28,
    requiredRuntimeHours: 12,
    batteryPercent: 86,
    inputWatts: 210,
    outputWatts: 84,
    solarInputWatts: 160,
    connectedSourceAvailable: true,
    connectionState: 'connected',
    providerLabel: 'EcoFlow',
    deviceLabel: 'House power',
    dataFreshness: 'live',
    runtimeSource: 'provider',
    powerRelevantForTrip: true,
    powerNeedReason: 'Overnight trip context makes fridge/comms/navigation/device power relevant.',
    powerRecommendation: 'Power runtime is ready from connected telemetry.',
    hasManualFallback: true,
    source: 'live',
    updatedAt: now,
  },
  recovery: {
    bailoutRoutesAvailable: true,
    nearestExitMiles: 18,
    nearestPavedRoadMiles: 18,
    nearestKnownRoadMiles: 18,
    nearestKnownRoadLabel: 'Mineral Bottom Road',
    nearestFuelMiles: 42,
    nearestTownMiles: 38,
    officialContactPointAvailable: true,
    officialContactPointSummary: 'Indexed ranger/contact point available from cached trip inputs; verify official status before relying on it.',
    routeBailoutOptionCount: 3,
    recoveryDifficulty: 'moderate',
    currentCoordinatesAvailable: true,
    currentLatitude: 38.57,
    currentLongitude: -109.55,
    currentAccuracyMeters: 8,
    routeRemoteness: 'moderate',
    emergencyCoordinatePacketReady: true,
    emergencyCoordinatePacketSummary: 'Coordinate packet can include current GPS +/- 8m.',
    nearestBailoutSummary: 'Mineral Bottom Road is 18 mi from current coordinates.',
    recommendedPrep: ['Keep bailout, communications, and recovery inputs refreshed before departure.'],
    recoveryGearReady: true,
    recoveryAccessConfidence: 'high',
    source: 'cached',
    updatedAt: now,
  },
  communications: {
    signalConfidence: 'high',
    satelliteCommsReady: true,
    teamCheckInPlanReady: true,
    cellularExpected: false,
    source: 'manual',
    updatedAt: now,
  },
  telemetry: {
    vehicleTelemetryLive: true,
    lastKnownUsable: true,
    source: 'live',
    updatedAt: now,
  },
  currentLocation: {
    latitude: 38.57,
    longitude: -109.55,
    accuracyMeters: 8,
    source: 'live',
    updatedAt: now,
  },
};

export const partialReadinessFixture: ExpeditionReadinessInput = {
  capturedAt: now,
  route: null,
  activeVehicle: null,
  weather: {
    riskLevel: 'unknown',
    confidence: 'low',
    source: 'cached',
    updatedAt: '2026-05-12T05:00:00.000Z',
    isStale: true,
  },
  offline: {
    packageStatus: 'partial',
    routeDownloaded: false,
    mapsDownloaded: true,
    emergencyDocsAvailable: null,
    source: 'manual',
    updatedAt: now,
  },
  campCandidates: [{
    id: 'demo-camp',
    name: 'ECS demo camp candidate',
    legalAccessConfidence: 'low',
    officialConfirmation: false,
    accessStatus: 'unknown',
    suitabilityScore: 58,
    source: 'demo',
    isDemo: true,
    updatedAt: now,
  }],
  recovery: {
    bailoutRoutesAvailable: null,
    recoveryGearReady: false,
    recoveryAccessConfidence: 'low',
    source: 'manual',
    updatedAt: now,
  },
};

export const holdReadinessFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  route: {
    ...(completeReadyReadinessFixture.route ?? {}),
    closureKnown: true,
    riskLevel: 'critical',
  },
  offline: {
    ...(completeReadyReadinessFixture.offline ?? {}),
    packageStatus: 'missing',
    mapsDownloaded: false,
  },
};

export const localDayTripNoCampFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  tripIntent: 'dayTrip',
  tripIntentSource: 'selected',
  readinessProfile: 'dayTrip',
  route: {
    routeId: 'route-local-day-scout',
    name: 'Local Ridge Scout Loop',
    distanceMiles: 18,
    difficulty: 'easy',
    riskLevel: 'low',
    routeConfidence: 'high',
    knownHazards: [],
    source: 'live',
    updatedAt: now,
  },
  campCandidates: null,
  power: null,
  offline: {
    packageStatus: 'partial',
    routeDownloaded: true,
    routeGeometryCached: true,
    mapsDownloaded: true,
    mapTilesCachedForRoute: true,
    bailoutPointsCached: true,
    weatherSnapshotAvailable: true,
    emergencyPacketAvailable: true,
    currentRoutePackageFresh: true,
    isRemoteRoute: false,
    isOnline: true,
    source: 'cached',
    updatedAt: now,
  },
  fuel: {
    rangeRemainingMiles: 180,
    routeDistanceRemainingMiles: 18,
    reserveMiles: 162,
    fuelPercent: 70,
    source: 'manual',
    updatedAt: now,
  },
  recovery: {
    ...(completeReadyReadinessFixture.recovery ?? {}),
    nearestExitMiles: 4,
    nearestPavedRoadMiles: 4,
    nearestKnownRoadMiles: 4,
    nearestFuelMiles: 12,
    nearestTownMiles: 10,
    routeRemoteness: 'low',
    recoveryDifficulty: 'low',
    nearestBailoutSummary: 'County road bailout is 4 mi from the loop.',
    updatedAt: now,
  },
  communications: {
    signalConfidence: 'medium',
    satelliteCommsReady: false,
    teamCheckInPlanReady: true,
    cellularExpected: true,
    source: 'manual',
    updatedAt: now,
  },
};

export const overnightDispersedCampingFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  tripIntent: 'overnightCamp',
  tripIntentSource: 'selected',
  readinessProfile: 'overnight',
  route: {
    ...(completeReadyReadinessFixture.route ?? {}),
    routeId: 'route-overnight-dispersed',
    name: 'Canyon Rim Overnight Route',
    distanceMiles: 54,
    difficulty: 'moderate',
    riskLevel: 'moderate',
  },
  campCandidates: [{
    id: 'camp-overnight-a',
    label: 'A',
    name: 'Canyon Rim candidate A',
    overallCampScore: 82,
    legalAccessConfidence: 'medium',
    officialConfirmation: false,
    accessStatus: 'unknown',
    suitabilityScore: 84,
    terrainSuitabilityScore: 78,
    vehicleAccessConfidence: 'medium',
    weatherExposureSummary: 'Moderate wind exposure on the rim.',
    accessSummary: 'Access appears plausible from available layers; verify official agency rules.',
    whyECSPickedThis: 'Best balance of access, terrain, and bailout proximity among available candidates.',
    cautionNotes: ['Legal access confidence is medium; official confirmation is not attached.'],
    sourceConfidence: 'medium',
    isECSInferred: true,
    source: 'inferred',
    isInferred: true,
    updatedAt: now,
  }],
};

export const remoteMultiDayRouteFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  tripIntent: 'remoteExpedition',
  tripIntentSource: 'selected',
  readinessProfile: 'remoteExpedition',
  route: {
    ...(completeReadyReadinessFixture.route ?? {}),
    routeId: 'route-remote-multiday',
    name: 'Remote Basin Multi-Day Traverse',
    distanceMiles: 168,
    difficulty: 'hard',
    riskLevel: 'high',
    knownHazards: ['Long fuel gap', 'Shelf road exposure'],
  },
  offline: {
    ...(completeReadyReadinessFixture.offline ?? {}),
    isRemoteRoute: true,
  },
  fuel: {
    rangeRemainingMiles: 235,
    routeDistanceRemainingMiles: 168,
    reserveMiles: 67,
    fuelPercent: 82,
    source: 'manual',
    updatedAt: now,
  },
  recovery: {
    ...(completeReadyReadinessFixture.recovery ?? {}),
    nearestExitMiles: 44,
    nearestPavedRoadMiles: 66,
    nearestKnownRoadMiles: 44,
    nearestFuelMiles: 92,
    nearestTownMiles: 104,
    nearestSignalAreaMiles: 31,
    recoveryDifficulty: 'high',
    routeRemoteness: 'high',
    nearestBailoutSummary: 'Nearest indexed bailout is 44 mi from the current corridor.',
  },
  communications: {
    signalConfidence: 'low',
    satelliteCommsReady: true,
    teamCheckInPlanReady: true,
    cellularExpected: false,
    source: 'manual',
    updatedAt: now,
  },
};

export const noActiveVehicleReadinessFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  activeVehicle: null,
};

export const staleWeatherReadinessFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  weather: {
    ...(completeReadyReadinessFixture.weather ?? {}),
    updatedAt: '2026-05-12T05:00:00.000Z',
    isStale: true,
  },
};

export const missingOfflinePackageReadinessFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  offline: {
    ...(completeReadyReadinessFixture.offline ?? {}),
    packageStatus: 'missing',
    routeDownloaded: false,
    routeGeometryCached: false,
    mapsDownloaded: false,
    mapTilesCachedForRoute: false,
    campCandidatesCached: false,
    bailoutPointsCached: false,
    weatherSnapshotAvailable: false,
    currentRoutePackageFresh: false,
  },
};

export const lowCampLegalAccessConfidenceFixture: ExpeditionReadinessInput = {
  ...completeReadyReadinessFixture,
  campCandidates: [{
    id: 'camp-low-confidence',
    label: 'A',
    name: 'Low-confidence dispersed candidate',
    overallCampScore: 64,
    legalAccessConfidence: 'low',
    officialConfirmation: false,
    accessStatus: 'unknown',
    suitabilityScore: 68,
    terrainSuitabilityScore: 70,
    vehicleAccessConfidence: 'medium',
    accessSummary: 'Legal confidence is limited; check official agency rules.',
    cautionNotes: ['No official confirmation is attached to this camp candidate.'],
    sourceConfidence: 'low',
    isECSInferred: true,
    source: 'inferred',
    isInferred: true,
    updatedAt: now,
  }],
};
