import type { ImageSourcePropType } from 'react-native';

/**
 * Metro-safe map from the stable badge definition ID to achieved artwork.
 * Keep this file beside the tier folders so every require path stays valid.
 */
export const EXPEDITION_BADGE_ARTWORK = {
  'first-expedition': require('./common/first-expedition.png') as ImageSourcePropType,
  'first-10-miles': require('./common/first-10-miles.png') as ImageSourcePropType,
  'first-50-miles': require('./uncommon/first-50-miles.png') as ImageSourcePropType,
  'first-100-miles': require('./rare/first-100-miles.png') as ImageSourcePropType,
  'first-mountain-route': require('./uncommon/first-mountain-route.png') as ImageSourcePropType,
  'first-desert-route': require('./uncommon/first-desert-route.png') as ImageSourcePropType,
  'first-forest-route': require('./uncommon/first-forest-route.png') as ImageSourcePropType,
  'first-night-finish': require('./uncommon/first-night-finish.png') as ImageSourcePropType,
  'first-weather-event': require('./uncommon/first-weather-event.png') as ImageSourcePropType,
  'first-route-deviation': require('./common/first-route-deviation.png') as ImageSourcePropType,
  'profile-ready': require('./common/profile-ready.png') as ImageSourcePropType,
  'confidence-checked': require('./common/confidence-checked.png') as ImageSourcePropType,
  'trip-activated': require('./common/trip-activated.png') as ImageSourcePropType,
  'resume-ready': require('./common/resume-ready.png') as ImageSourcePropType,
  'local-packet-ready': require('./common/local-packet-ready.png') as ImageSourcePropType,
  'packet-reviewed': require('./common/packet-reviewed.png') as ImageSourcePropType,
  'terrain-aware': require('./common/terrain-aware.png') as ImageSourcePropType,
  'basecamp-reviewed': require('./common/basecamp-reviewed.png') as ImageSourcePropType,
  'clean-stop': require('./common/clean-stop.png') as ImageSourcePropType,
  'route-authority-recognized': require('./common/route-authority-recognized.png') as ImageSourcePropType,
  'honest-unknown': require('./common/honest-unknown.png') as ImageSourcePropType,
  'miles-50': require('./common/miles-50.png') as ImageSourcePropType,
  'miles-100': require('./uncommon/miles-100.png') as ImageSourcePropType,
  'miles-250': require('./rare/miles-250.png') as ImageSourcePropType,
  'miles-500': require('./epic/miles-500.png') as ImageSourcePropType,
  'miles-1000': require('./legendary/miles-1000.png') as ImageSourcePropType,
  'miles-2500': require('./legendary/miles-2500.png') as ImageSourcePropType,
  'miles-5000': require('./legendary/miles-5000.png') as ImageSourcePropType,
  'ten-mile-day': require('./common/ten-mile-day.png') as ImageSourcePropType,
  'fifty-mile-day': require('./uncommon/fifty-mile-day.png') as ImageSourcePropType,
  'hundred-mile-day': require('./rare/hundred-mile-day.png') as ImageSourcePropType,
  'long-haul': require('./uncommon/long-haul.png') as ImageSourcePropType,
  'endurance-run': require('./epic/endurance-run.png') as ImageSourcePropType,
  'elevation-1000': require('./common/elevation-1000.png') as ImageSourcePropType,
  'elevation-2500': require('./common/elevation-2500.png') as ImageSourcePropType,
  'elevation-5000': require('./uncommon/elevation-5000.png') as ImageSourcePropType,
  'elevation-7500': require('./rare/elevation-7500.png') as ImageSourcePropType,
  'elevation-10000': require('./epic/elevation-10000.png') as ImageSourcePropType,
  'highest-point-yet': require('./uncommon/highest-point-yet.png') as ImageSourcePropType,
  'mountain-pass': require('./rare/mountain-pass.png') as ImageSourcePropType,
  'ridge-runner': require('./uncommon/ridge-runner.png') as ImageSourcePropType,
  'elevation-hunter': require('./rare/elevation-hunter.png') as ImageSourcePropType,
  'big-climb': require('./uncommon/big-climb.png') as ImageSourcePropType,
  'above-the-clouds': require('./epic/above-the-clouds.png') as ImageSourcePropType,
  'summit-line': require('./legendary/summit-line.png') as ImageSourcePropType,
  'duration-1-hour': require('./common/duration-1-hour.png') as ImageSourcePropType,
  'duration-5-hours': require('./common/duration-5-hours.png') as ImageSourcePropType,
  'duration-10-hours': require('./uncommon/duration-10-hours.png') as ImageSourcePropType,
  'duration-25-hours': require('./rare/duration-25-hours.png') as ImageSourcePropType,
  'duration-50-hours': require('./epic/duration-50-hours.png') as ImageSourcePropType,
  'duration-100-hours': require('./legendary/duration-100-hours.png') as ImageSourcePropType,
  'early-start': require('./common/early-start.png') as ImageSourcePropType,
  'dawn-patrol': require('./common/dawn-patrol.png') as ImageSourcePropType,
  'sunset-finish': require('./common/sunset-finish.png') as ImageSourcePropType,
  'night-return': require('./uncommon/night-return.png') as ImageSourcePropType,
  'full-day-expedition': require('./rare/full-day-expedition.png') as ImageSourcePropType,
  'weathered-it': require('./uncommon/weathered-it.png') as ImageSourcePropType,
  'storm-runner': require('./rare/storm-runner.png') as ImageSourcePropType,
  'rain-route': require('./common/rain-route.png') as ImageSourcePropType,
  'snow-trace': require('./rare/snow-trace.png') as ImageSourcePropType,
  'heat-line': require('./uncommon/heat-line.png') as ImageSourcePropType,
  'cold-start': require('./uncommon/cold-start.png') as ImageSourcePropType,
  'wind-tested': require('./common/wind-tested.png') as ImageSourcePropType,
  'temperature-swing': require('./rare/temperature-swing.png') as ImageSourcePropType,
  'changing-skies': require('./common/changing-skies.png') as ImageSourcePropType,
  'weather-shift': require('./uncommon/weather-shift.png') as ImageSourcePropType,
  'gravel-proven': require('./common/gravel-proven.png') as ImageSourcePropType,
  'sand-track': require('./uncommon/sand-track.png') as ImageSourcePropType,
  'mud-season': require('./uncommon/mud-season.png') as ImageSourcePropType,
  'rocky-passage': require('./uncommon/rocky-passage.png') as ImageSourcePropType,
  'steep-grade': require('./rare/steep-grade.png') as ImageSourcePropType,
  'technical-terrain': require('./rare/technical-terrain.png') as ImageSourcePropType,
  'desert-crossing': require('./rare/desert-crossing.png') as ImageSourcePropType,
  'forest-corridor': require('./common/forest-corridor.png') as ImageSourcePropType,
  'canyon-line': require('./uncommon/canyon-line.png') as ImageSourcePropType,
  'backcountry-grade': require('./rare/backcountry-grade.png') as ImageSourcePropType,
  'washboard-veteran': require('./uncommon/washboard-veteran.png') as ImageSourcePropType,
  'trail-tested': require('./common/trail-tested.png') as ImageSourcePropType,
  'terrain-watch': require('./uncommon/terrain-watch.png') as ImageSourcePropType,
  'recovery-ready': require('./uncommon/recovery-ready.png') as ImageSourcePropType,
  'recovery-panel-opened': require('./common/recovery-panel-opened.png') as ImageSourcePropType,
  'recovery-plan-generated': require('./rare/recovery-plan-generated.png') as ImageSourcePropType,
  'assisted-recovery': require('./rare/assisted-recovery.png') as ImageSourcePropType,
  'self-recovery': require('./rare/self-recovery.png') as ImageSourcePropType,
  'stuck-but-sorted': require('./epic/stuck-but-sorted.png') as ImageSourcePropType,
  'field-problem-solver': require('./rare/field-problem-solver.png') as ImageSourcePropType,
  'recovery-veteran': require('./epic/recovery-veteran.png') as ImageSourcePropType,
  'route-adjusted': require('./common/route-adjusted.png') as ImageSourcePropType,
  'detour-logged': require('./common/detour-logged.png') as ImageSourcePropType,
  'reroute-accepted': require('./uncommon/reroute-accepted.png') as ImageSourcePropType,
  'stayed-the-course': require('./common/stayed-the-course.png') as ImageSourcePropType,
  'clean-run': require('./common/clean-run.png') as ImageSourcePropType,
  'clean-completion': require('./common/clean-completion.png') as ImageSourcePropType,
  'alternate-line': require('./uncommon/alternate-line.png') as ImageSourcePropType,
  'bailout-point-used': require('./rare/bailout-point-used.png') as ImageSourcePropType,
  'backtrack-logged': require('./uncommon/backtrack-logged.png') as ImageSourcePropType,
  'trail-pivot': require('./rare/trail-pivot.png') as ImageSourcePropType,
  'remote-redirect': require('./epic/remote-redirect.png') as ImageSourcePropType,
  'weekend-explorer': require('./common/weekend-explorer.png') as ImageSourcePropType,
  'three-trips-logged': require('./uncommon/three-trips-logged.png') as ImageSourcePropType,
  'five-trips-logged': require('./rare/five-trips-logged.png') as ImageSourcePropType,
  'ten-trips-logged': require('./epic/ten-trips-logged.png') as ImageSourcePropType,
  'monthly-explorer': require('./rare/monthly-explorer.png') as ImageSourcePropType,
  'expedition-habit': require('./rare/expedition-habit.png') as ImageSourcePropType,
  'trail-veteran': require('./rare/trail-veteran.png') as ImageSourcePropType,
  'seasoned-operator': require('./epic/seasoned-operator.png') as ImageSourcePropType,
  'repeat-explorer': require('./common/repeat-explorer.png') as ImageSourcePropType,
  'back-again': require('./common/back-again.png') as ImageSourcePropType,
  'new-region': require('./uncommon/new-region.png') as ImageSourcePropType,
  'new-trailhead': require('./common/new-trailhead.png') as ImageSourcePropType,
  'new-state': require('./rare/new-state.png') as ImageSourcePropType,
  'new-terrain-type': require('./uncommon/new-terrain-type.png') as ImageSourcePropType,
  'camp-scout': require('./common/camp-scout.png') as ImageSourcePropType,
  'resupply-scout': require('./common/resupply-scout.png') as ImageSourcePropType,
  'trailhead-ready': require('./common/trailhead-ready.png') as ImageSourcePropType,
  'remote-start': require('./rare/remote-start.png') as ImageSourcePropType,
  'borderline-wild': require('./rare/borderline-wild.png') as ImageSourcePropType,
  'uncharted-habit': require('./hidden/uncharted-habit.png') as ImageSourcePropType,
  'remote-route': require('./rare/remote-route.png') as ImageSourcePropType,
  'hybrid-run': require('./uncommon/hybrid-run.png') as ImageSourcePropType,
  'moment-captured': require('./common/moment-captured.png') as ImageSourcePropType,
  'five-moments-captured': require('./uncommon/five-moments-captured.png') as ImageSourcePropType,
  'ten-moments-captured': require('./rare/ten-moments-captured.png') as ImageSourcePropType,
  'weather-moment': require('./common/weather-moment.png') as ImageSourcePropType,
  'elevation-moment': require('./common/elevation-moment.png') as ImageSourcePropType,
  'recovery-moment': require('./uncommon/recovery-moment.png') as ImageSourcePropType,
  'deviation-moment': require('./common/deviation-moment.png') as ImageSourcePropType,
  'terrain-risk-moment': require('./uncommon/terrain-risk-moment.png') as ImageSourcePropType,
  'memorable-route': require('./rare/memorable-route.png') as ImageSourcePropType,
  'story-worth-saving': require('./epic/story-worth-saving.png') as ImageSourcePropType,
  'longest-expedition-yet': require('./uncommon/longest-expedition-yet.png') as ImageSourcePropType,
  'highest-expedition-yet': require('./uncommon/highest-expedition-yet.png') as ImageSourcePropType,
  'longest-duration-yet': require('./uncommon/longest-duration-yet.png') as ImageSourcePropType,
  'most-elevation-gain-yet': require('./rare/most-elevation-gain-yet.png') as ImageSourcePropType,
  'most-notable-moments-yet': require('./rare/most-notable-moments-yet.png') as ImageSourcePropType,
  'most-remote-route-yet': require('./rare/most-remote-route-yet.png') as ImageSourcePropType,
  'toughest-terrain-yet': require('./rare/toughest-terrain-yet.png') as ImageSourcePropType,
  'fastest-completion-yet': require('./rare/fastest-completion-yet.png') as ImageSourcePropType,
  'personal-best': require('./rare/personal-best.png') as ImageSourcePropType,
  'record-breaker': require('./epic/record-breaker.png') as ImageSourcePropType,
  'ghost-trail': require('./hidden/ghost-trail.png') as ImageSourcePropType,
  'golden-hour': require('./hidden/golden-hour.png') as ImageSourcePropType,
  'midnight-oil': require('./hidden/midnight-oil.png') as ImageSourcePropType,
  'silent-operator': require('./hidden/silent-operator.png') as ImageSourcePropType,
  'back-before-dark': require('./hidden/back-before-dark.png') as ImageSourcePropType,
  'the-long-way': require('./hidden/the-long-way.png') as ImageSourcePropType,
  'no-signal-no-problem': require('./hidden/no-signal-no-problem.png') as ImageSourcePropType,
  'needle-threader': require('./hidden/needle-threader.png') as ImageSourcePropType,
  'weather-gambler': require('./hidden/weather-gambler.png') as ImageSourcePropType,
  'ridge-whisperer': require('./hidden/ridge-whisperer.png') as ImageSourcePropType,
  'desert-ghost': require('./hidden/desert-ghost.png') as ImageSourcePropType,
  'mud-baptism': require('./hidden/mud-baptism.png') as ImageSourcePropType,
  'the-scenic-mistake': require('./hidden/the-scenic-mistake.png') as ImageSourcePropType,
  'perfect-window': require('./hidden/perfect-window.png') as ImageSourcePropType,
  'old-reliable': require('./hidden/old-reliable.png') as ImageSourcePropType,
  'spring-route': require('./common/spring-route.png') as ImageSourcePropType,
  'summer-route': require('./common/summer-route.png') as ImageSourcePropType,
  'fall-route': require('./common/fall-route.png') as ImageSourcePropType,
  'winter-route': require('./common/winter-route.png') as ImageSourcePropType,
  'new-year-expedition': require('./uncommon/new-year-expedition.png') as ImageSourcePropType,
  'holiday-trail': require('./uncommon/holiday-trail.png') as ImageSourcePropType,
  'first-trip-of-the-season': require('./uncommon/first-trip-of-the-season.png') as ImageSourcePropType,
  'last-trip-of-the-season': require('./uncommon/last-trip-of-the-season.png') as ImageSourcePropType,
} as const;

export type ExpeditionBadgeArtworkId = keyof typeof EXPEDITION_BADGE_ARTWORK;

export function hasExpeditionBadgeArtwork(
  badgeId: string,
): badgeId is ExpeditionBadgeArtworkId {
  return Object.prototype.hasOwnProperty.call(EXPEDITION_BADGE_ARTWORK, badgeId);
}

export function getExpeditionBadgeArtwork(
  badgeId: string,
): ImageSourcePropType | null {
  return hasExpeditionBadgeArtwork(badgeId)
    ? EXPEDITION_BADGE_ARTWORK[badgeId]
    : null;
}
