export const AUTH_COPY = {
  brand: 'ECS',
  title: 'Expedition Command System',
  login: {
    supporting: 'Secure access to your vehicle, route, and expedition systems.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter password',
    primary: 'Sign In',
    primaryLoading: 'Signing In...',
    forgotPassword: 'Forgot password?',
    createAccount: 'Create account',
    requestAccess: 'Request access',
    redeemInvite: 'Redeem invite',
    invalidEmail: 'Enter a valid email address.',
    missingPassword: 'Enter your password.',
    invalidCredentials: 'Email or password not recognized.',
    offline: 'No network connection. Reconnect to sign in.',
    genericFailure: 'Unable to sign in right now. Please try again.',
    rateLimited: 'Too many attempts. Please wait and try again.',
  },
  session: {
    checking: 'Checking secure session...',
    verifyingAccess: 'Verifying ECS access...',
    preparing: 'Preparing command system...',
    loadingSystems: 'Loading expedition systems...',
    expired: 'Your session has expired. Please sign in again.',
    reauth: 'Please sign in again to continue.',
    reconnect: 'Please reconnect and sign in again to continue.',
    verifyFailure: 'Unable to verify your session right now. Please try again.',
  },
  forgotPassword: {
    title: 'Reset password',
    supporting: "Enter your account email and we'll send reset instructions.",
    primary: 'Send reset link',
    primaryLoading: 'Sending...',
    success: 'Reset instructions sent if the account exists.',
    failure: 'Unable to send reset instructions right now. Please try again.',
    back: 'Back to sign in',
  },
  resetPassword: {
    verifying: 'Verifying reset link...',
    invalidLink: 'This reset link is no longer valid. Request a new password reset link to continue.',
    verifyFailure: 'Unable to verify this reset link right now. Please try again.',
    title: 'Create new password',
    supporting: 'Choose a new password for your ECS account.',
    passwordLabel: 'New password',
    passwordPlaceholder: 'Enter new password',
    confirmLabel: 'Confirm password',
    confirmPlaceholder: 'Confirm new password',
    missingPassword: 'Enter a new password.',
    missingConfirmation: 'Confirm your new password.',
    mismatch: 'Passwords do not match.',
    primary: 'Update password',
    primaryLoading: 'Updating...',
    failure: 'Unable to update your password right now. Please try again.',
    successTitle: 'Password updated',
    successLine: 'Your password has been updated successfully.',
    successCta: 'Continue to sign in',
    requestNewLink: 'Request new link',
  },
  signup: {
    title: 'Create account',
    supporting: 'Set up secure access to ECS.',
    primary: 'Create account',
    primaryLoading: 'Creating account...',
    successTitle: 'Account created',
    successLine: 'Check your email to complete verification, then continue to sign in.',
    failure: 'Unable to create account right now. Please try again.',
  },
  activation: {
    title: 'Activate access',
    supporting: 'Activate your authorized ECS access to continue.',
    primary: 'Continue',
    verifying: 'Verifying access...',
    invalid: 'This invitation is no longer valid.',
    verifyFailure: 'Unable to verify this invitation right now. Please try again.',
    setupTitle: 'Set password',
    setupSupporting: 'Create a password for your ECS account.',
    setupPrimary: 'Finish setup',
    setupLoading: 'Finishing setup...',
    setupFailure: 'Unable to finish setup right now. Please try again.',
    successTitle: 'Access ready',
    successLine: 'Your ECS access is ready. Continue to sign in.',
  },
  requestAccess: {
    title: 'Request access',
    supporting: 'Request authorized access to Expedition Command System.',
    primary: 'Submit request',
    successTitle: 'Request submitted',
    successLine: "We'll contact you if access is approved.",
    pendingTitle: 'Access pending',
    pendingLine: 'Your ECS access request is awaiting approval.',
    pendingSupport: "We'll contact you when access is available.",
  },
  accessGate: {
    title: 'Access required',
    supporting: 'Your account does not currently have active ECS access.',
    detail: 'Active ECS access is required to enter expedition systems.',
    primary: 'Manage access',
    secondary: 'Sign out',
    verificationFailureTitle: 'Unable to verify access',
    verificationFailureLine: 'Unable to verify ECS access right now. Please try again.',
    verificationFailureOfflineLine: 'Unable to verify ECS access right now. Please try again when connected.',
    retry: 'Try again',
  },
  logout: {
    title: 'Sign out',
    supporting: "You'll need to sign in again to access ECS.",
    primary: 'Sign out',
    primaryLoading: 'Signing out...',
    secondary: 'Cancel',
  },
  account: {
    header: 'Account',
    active: 'Active ECS access',
    pending: 'Pending access approval',
    blocked: 'Access required',
    unknown: 'Verifying ECS access',
    manageAccess: 'Manage access',
    resetPassword: 'Reset password',
    restorePurchases: 'Restore Purchases',
    refreshAccess: 'Refresh Access',
    support: 'Support',
    privacy: 'Privacy',
    terms: 'Terms',
    signOut: 'Sign out',
    signIn: 'Sign In',
  },
  utility: {
    supportPrompt: 'Need help accessing your account?',
    controlledAccessLine: 'Access is provided through an authorized ECS account.',
    publicAccessLine: 'Sign in with your ECS account to access expedition systems.',
    terms: 'Terms',
    privacy: 'Privacy',
    support: 'Support',
    sheets: {
      terms: {
        title: 'Terms',
        body:
          'Use of Expedition Command System is governed by the active ECS account terms and operational policies assigned to your deployment.\n\n' +
          'Use only authorized accounts, protect expedition data, and verify route, safety, and vehicle decisions independently during field operations.\n\n' +
          'If you need the current account terms for your organization, contact ECS support through your normal access channel.',
      },
      privacy: {
        title: 'Privacy',
        body:
          'ECS stores expedition planning, route, and vehicle configuration data locally by default. When cloud sync is enabled, data is sent through secured ECS account services for session restore and cross-device continuity.\n\n' +
          'Location, route, and expedition records remain tied to the signed-in ECS account. ECS does not use this login surface for advertising or unrelated data collection.\n\n' +
          'For privacy questions tied to your deployment, contact ECS support or your system administrator.',
      },
      support: {
        title: 'Support',
        body:
          'Need help accessing your account?\n\n' +
          'Use Forgot password to request a reset link or Create account to set up a new ECS account when self-service setup is enabled.\n\n' +
          'Account sign-in and ECS access are verified separately, so access may still require active ECS access after you sign in.\n\n' +
          'If access is still blocked, contact your ECS administrator or your established support channel for account assistance.',
      },
    },
  },
  degraded: {
    limitedConnectivity: 'Limited connectivity detected. Some cloud-backed live services may be unavailable.',
    liveServicesUnavailable: 'Cloud-backed live services unavailable. Offline-capable features remain available.',
  },
} as const;

export type AuthCopy = typeof AUTH_COPY;
