import { MOTION, PRESS } from '../motion';

export const AUTH_VISUAL_SPEC = {
  breakpoints: {
    tabletMinWidth: 768,
    compactHeightMax: 759,
    narrowLandscapeHeightMax: 539,
    tallPhoneHeightMin: 880,
  },
  widths: {
    minUsableColumn: 320,
    phoneColumnMax: 430,
    narrowLandscapeFactor: 0.52,
    narrowLandscapeMin: 420,
    narrowLandscapeMax: 500,
    tabletFactor: 0.54,
    tabletMin: 480,
    tabletMax: 560,
    footerPhoneMax: 360,
    footerTabletMax: 400,
    heroSupportingPhoneMax: 336,
    heroSupportingTabletMax: 420,
    stateSupportingPhoneMax: 318,
    stateSupportingTabletMax: 380,
    loadingPhoneMax: 380,
    loadingLandscapeMax: 470,
    loadingTabletMax: 520,
    accessGatePhoneMax: 440,
    accessGateLandscapeMax: 500,
    accessGateTabletMax: 560,
  },
  spacing: {
    topPadding: {
      compactLandscape: 12,
      compactPortrait: 14,
      standardPhone: 18,
      tablet: 26,
    },
    bottomPadding: {
      compactLandscape: 14,
      compactPortrait: 16,
      standardPhone: 18,
      tablet: 26,
    },
    brandGap: {
      compactLandscape: 12,
      compactPortrait: 14,
      standardPhone: 18,
      tablet: 24,
    },
    footerGap: {
      compactLandscape: 12,
      standardPhone: 16,
      tablet: 20,
    },
    headerBrandLabelGap: {
      hero: 6,
      state: 5,
    },
    headerTitleGap: {
      heroCompact: 9,
      heroStandard: 10,
      state: 8,
    },
    headerSupportingGap: {
      hero: 10,
      state: 8,
    },
    panelPaddingX: 20,
    panelPaddingTop: 18,
    panelPaddingBottom: 18,
    topRuleInset: 18,
    cornerAccentTop: 18,
    cornerAccentInset: 16,
    cornerAccentWidth: 20,
    fieldGap: 16,
    fieldLabelGap: 8,
    feedbackGap: 7,
    feedbackSlotMinHeight: 22,
    inputTextPaddingY: 14,
    primaryButtonMarginTop: 4,
    secondaryRowMarginTop: 16,
    secondaryRowPaddingTop: 14,
    secondaryRowRowGap: 8,
    secondaryRowColumnGap: 8,
    messageRowMarginTop: 14,
    recoveryHeaderGap: 6,
    holdGap: 10,
    holdPaddingX: 18,
    footerDividerPaddingTop: 14,
    footerInternalGap: 8,
    footerPaddingX: 8,
    footerVersionGap: 2,
    footerUtilityRowGap: 8,
    footerUtilityColumnGap: 10,
    footerUtilityMinHeight: 36,
    footerUtilityMinWidth: 36,
    footerUtilityPaddingX: 12,
    footerUtilityPaddingY: 7,
    footerUtilityRadius: 12,
    footerSupportGap: 0,
    stateBlockGap: 10,
    stateBlockPaddingY: 10,
    rulesCardPaddingY: 12,
    rulesCardGap: 9,
    emailBadgeMarginTop: 10,
    accessContextMarginTop: 8,
    accessStateCardMarginTop: 18,
    accessStateCardPaddingX: 16,
    accessStateCardPaddingY: 15,
    accessStatusLineGap: 5,
    accessMessageMarginTop: 12,
    accessStatusMarginTop: 10,
    accessStatusRowGap: 8,
    accessPrimaryMarginTop: 16,
    accessPrimaryPaddingX: 16,
    accessUtilityMarginTop: 12,
    accessUtilityGap: 10,
    accessUtilityPaddingX: 14,
    accessFootnoteMarginTop: 14,
    accessScreenPaddingX: 22,
    accessScreenPaddingY: 18,
  },
  crest: {
    hero: {
      phoneFactor: 0.35,
      compactFactor: 0.33,
      tabletFactor: 0.2,
      min: 144,
      phoneMax: 176,
      tabletMax: 182,
    },
    state: {
      phoneFactor: 0.3,
      compactFactor: 0.28,
      tabletFactor: 0.18,
      min: 118,
      phoneMax: 144,
      tabletMax: 154,
    },
  },
  form: {
    panelRadius: 22,
    inputRadius: 16,
    inputMinHeight: 56,
    inputPaddingX: 16,
    helperRadius: 14,
    helperPaddingX: 12,
    helperPaddingY: 11,
    subSurfaceRadius: 16,
    primaryHeight: 56,
    primaryRadius: 16,
    utilityHitRadius: 14,
    utilityHitMinHeight: 38,
    utilityHitMinWidth: 36,
    utilityHitPaddingX: 10,
    utilityHitPaddingY: 8,
  },
  hold: {
    minHeight: 228,
    detailMaxWidth: 250,
  },
  state: {
    supportingMaxWidth: 320,
    accessContextMaxWidth: 340,
    accessFootnoteMaxWidth: 340,
    accessGateCardRadius: 22,
    accessStatusRadius: 16,
    accessUtilityRadius: 12,
    accessUtilityMinHeight: 44,
    accessUtilityMinWidth: 132,
    accessPrimaryMinHeight: 54,
  },
  typography: {
    brandLabel: {
      fontSize: 11,
      fontWeight: '800' as const,
      letterSpacing: 4,
    },
    heroTitle: {
      compactSize: 26,
      compactLineHeight: 32,
      standardSize: 28,
      standardLineHeight: 34,
    },
    stateTitle: {
      compactSize: 24,
      compactLineHeight: 30,
      standardSize: 26,
      standardLineHeight: 32,
    },
    heroSupporting: {
      fontSize: 14,
      lineHeight: 20,
    },
    stateSupporting: {
      fontSize: 13,
      lineHeight: 18,
    },
    fieldLabel: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700' as const,
      letterSpacing: 0.2,
    },
    inputText: {
      fontSize: 15,
      lineHeight: 20,
      minHeight: 24,
    },
    inlineError: {
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '600' as const,
    },
    statusBanner: {
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600' as const,
      iconSize: 14,
      rowGap: 8,
    },
    primaryButton: {
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '800' as const,
      letterSpacing: 0.35,
    },
    secondaryAction: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700' as const,
    },
    ruleText: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '600' as const,
    },
    recoveryTitle: {
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '800' as const,
      letterSpacing: 0.2,
    },
    recoverySupporting: {
      fontSize: 13,
      lineHeight: 18,
    },
    stateLead: {
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '800' as const,
      letterSpacing: 0.2,
    },
    stateSupporting: {
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600' as const,
    },
    holdTitle: {
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '800' as const,
      letterSpacing: 0.2,
    },
    holdDetail: {
      fontSize: 13,
      lineHeight: 18,
    },
    loadingText: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '700' as const,
      letterSpacing: 0.2,
    },
    loadingDetail: {
      fontSize: 12,
      lineHeight: 18,
    },
    footerHelper: {
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600' as const,
    },
    footerLink: {
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '700' as const,
      letterSpacing: 0.2,
    },
    footerVersion: {
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '700' as const,
      letterSpacing: 1.2,
    },
    accessEyebrow: {
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '800' as const,
      letterSpacing: 2.2,
    },
    accessTitle: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '800' as const,
    },
    accessLine: {
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600' as const,
    },
    accessDetail: {
      fontSize: 13,
      lineHeight: 19,
    },
    accessMessage: {
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '700' as const,
    },
    accessPrimaryButton: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '800' as const,
      letterSpacing: 0.5,
    },
    accessUtilityButton: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700' as const,
    },
    accessFootnote: {
      fontSize: 11,
      lineHeight: 16,
    },
    emailBadge: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700' as const,
    },
  },
  motion: {
    screenRevealDuration: MOTION.screenFadeIn,
    stateTransitionDuration: MOTION.stateTransition,
    buttonPressScale: PRESS.scaleDown,
    buttonPressReleaseScale: PRESS.scaleUp,
  },
} as const;
