import { ECS, TACTICAL } from '../theme';
import { AUTH_VISUAL_SPEC } from './authVisualSpec';

export const AUTH_SURFACE = {
  panelBackground: 'rgba(10, 14, 18, 0.88)',
  panelBorder: 'rgba(212,160,23,0.18)',
  panelRadius: AUTH_VISUAL_SPEC.form.panelRadius,
  panelInsetWash: 'rgba(255,255,255,0.03)',
  panelTopRule: 'rgba(255,255,255,0.055)',
  panelCornerAccent: 'rgba(212,160,23,0.34)',
  panelPaddingX: AUTH_VISUAL_SPEC.spacing.panelPaddingX,
  panelPaddingTop: AUTH_VISUAL_SPEC.spacing.panelPaddingTop,
  panelPaddingBottom: AUTH_VISUAL_SPEC.spacing.panelPaddingBottom,
  panelTopRuleInset: AUTH_VISUAL_SPEC.spacing.topRuleInset,
  panelCornerAccentTop: AUTH_VISUAL_SPEC.spacing.cornerAccentTop,
  panelCornerAccentInset: AUTH_VISUAL_SPEC.spacing.cornerAccentInset,
  panelCornerAccentWidth: AUTH_VISUAL_SPEC.spacing.cornerAccentWidth,
  panelShadowColor: '#000',
  panelShadowOffset: { width: 0, height: 12 } as const,
  panelShadowOpacity: 0.34,
  panelShadowRadius: 28,
  panelElevation: 9,
  inputBackground: 'rgba(255,255,255,0.028)',
  inputBorder: 'rgba(255,255,255,0.085)',
  inputFocusedBackground: 'rgba(255,255,255,0.045)',
  inputFocusedBorder: 'rgba(212,160,23,0.56)',
  inputFocusFill: 'rgba(212,160,23,0.04)',
  inputErrorBorder: 'rgba(217,123,114,0.7)',
  inputRadius: AUTH_VISUAL_SPEC.form.inputRadius,
  inputMinHeight: AUTH_VISUAL_SPEC.form.inputMinHeight,
  inputPaddingX: AUTH_VISUAL_SPEC.form.inputPaddingX,
  fieldGap: AUTH_VISUAL_SPEC.spacing.fieldGap,
  fieldLabelGap: AUTH_VISUAL_SPEC.spacing.fieldLabelGap,
  helperRadius: AUTH_VISUAL_SPEC.form.helperRadius,
  helperBorder: 'rgba(255,255,255,0.08)',
  helperBackground: 'rgba(255,255,255,0.035)',
  helperPaddingX: AUTH_VISUAL_SPEC.form.helperPaddingX,
  helperPaddingY: AUTH_VISUAL_SPEC.form.helperPaddingY,
  subSurfaceRadius: AUTH_VISUAL_SPEC.form.subSurfaceRadius,
  subSurfaceBorder: 'rgba(255,255,255,0.08)',
  subSurfaceBackground: 'rgba(255,255,255,0.03)',
  primaryHeight: AUTH_VISUAL_SPEC.form.primaryHeight,
  primaryRadius: AUTH_VISUAL_SPEC.form.primaryRadius,
  primaryBorder: 'rgba(255,247,222,0.14)',
  primaryShadowColor: TACTICAL.amber,
  primaryShadowOffset: { width: 0, height: 5 } as const,
  primaryShadowOpacity: 0.24,
  primaryShadowRadius: 12,
  primaryElevation: 5,
  divider: 'rgba(255,255,255,0.06)',
  utilityHitBackground: 'rgba(255,255,255,0.02)',
  utilityHitBorder: 'rgba(255,255,255,0.05)',
  utilityHitRadius: AUTH_VISUAL_SPEC.form.utilityHitRadius,
  utilityHitMinHeight: AUTH_VISUAL_SPEC.form.utilityHitMinHeight,
  utilityHitMinWidth: AUTH_VISUAL_SPEC.form.utilityHitMinWidth,
  utilityHitPaddingX: AUTH_VISUAL_SPEC.form.utilityHitPaddingX,
  utilityHitPaddingY: AUTH_VISUAL_SPEC.form.utilityHitPaddingY,
  primaryText: ECS.bgPrimary,
} as const;
