import type { EstablishedCampsite } from './establishedCampsiteTypes';

export type EstablishedCampsiteSourceCategory =
  | 'recreation_gov'
  | 'nps'
  | 'openstreetmap'
  | 'state_county_private';

export const ESTABLISHED_CAMPSITE_SOURCE_STRATEGY: Record<EstablishedCampsiteSourceCategory, string[]> = {
  recreation_gov: [
    'Federal reservable campground feeds approved for ECS use.',
    'Reservable, fee, operator, amenity, and season fields should be normalized without scraping private sites.',
  ],
  nps: [
    'NPS campground records and official park facility metadata.',
    'General National Park land must not imply dispersed camping eligibility.',
  ],
  openstreetmap: [
    'tourism=camp_site and tourism=caravan_site features from approved OSM ingestion.',
    'fee, reservation, access, and operator tags should stay source-labeled and verification-required.',
  ],
  state_county_private: [
    'Future licensed state, county, and private campground imports.',
    'Private campground sites require authorized source feeds, not scraping.',
  ],
};

export const SAMPLE_ESTABLISHED_CAMPSITES: EstablishedCampsite[] = [
  {
    id: 'ecs-demo-established-campsite-01',
    name: 'Juniper Flats Campground',
    latitude: 37.7749,
    longitude: -119.5925,
    campsiteType: 'campground',
    source: 'RECREATION_GOV',
    feeStatus: 'paid',
    reservationStatus: 'reservable',
    amenities: ['water', 'toilets', 'picnic_table', 'fire_ring', 'trash'],
    operatorName: 'Federal recreation facility',
    bookingUrl: 'https://www.recreation.gov/',
    seasonDescription: 'Season varies by agency notice',
    maxVehicleLengthFt: 28,
    tentAllowed: true,
    rvAllowed: true,
    trailersAllowed: true,
    sourceUpdatedAt: '2026-01-15',
    requiresVerification: true,
  },
  {
    id: 'ecs-demo-established-campsite-02',
    name: 'Pine Creek First-Come Camp',
    latitude: 37.8122,
    longitude: -119.6814,
    campsiteType: 'primitive_developed',
    source: 'OSM',
    feeStatus: 'free',
    reservationStatus: 'first_come',
    amenities: ['toilets', 'picnic_table', 'fire_ring'],
    operatorName: 'Forest Service district',
    seasonDescription: 'Open season depends on snow and road access',
    tentAllowed: true,
    rvAllowed: false,
    trailersAllowed: false,
    sourceUpdatedAt: '2026-01-11',
    requiresVerification: true,
  },
  {
    id: 'ecs-demo-established-campsite-03',
    name: 'Sierra Gate RV Park',
    latitude: 37.7331,
    longitude: -119.7832,
    campsiteType: 'rv_park',
    source: 'PRIVATE',
    feeStatus: 'paid',
    reservationStatus: 'mixed',
    amenities: ['water', 'toilets', 'showers', 'hookups', 'dump_station', 'trash', 'store', 'cell_service'],
    operatorName: 'Private operator',
    phone: '555-0103',
    seasonDescription: 'Call operator for current availability',
    maxVehicleLengthFt: 40,
    tentAllowed: false,
    rvAllowed: true,
    trailersAllowed: true,
    sourceUpdatedAt: '2026-01-10',
    requiresVerification: true,
  },
  {
    id: 'ecs-demo-established-campsite-04',
    name: 'Granite Group Site',
    latitude: 37.8616,
    longitude: -119.5387,
    campsiteType: 'group_site',
    source: 'STATE',
    feeStatus: 'paid',
    reservationStatus: 'required',
    amenities: ['water', 'toilets', 'picnic_table', 'fire_ring', 'trash'],
    operatorName: 'State park campground office',
    bookingUrl: 'https://example.invalid/state-camping',
    seasonDescription: 'Group reservations may close seasonally',
    tentAllowed: true,
    rvAllowed: true,
    trailersAllowed: true,
    sourceUpdatedAt: '2026-01-09',
    requiresVerification: true,
  },
  {
    id: 'ecs-demo-established-campsite-05',
    name: 'High Meadow Campground',
    latitude: 37.6923,
    longitude: -119.6412,
    campsiteType: 'campground',
    source: 'OSM',
    feeStatus: 'unknown',
    reservationStatus: 'unknown',
    amenities: ['unknown'],
    operatorName: 'Operator not confirmed',
    seasonDescription: 'Season not confirmed',
    tentAllowed: true,
    rvAllowed: false,
    trailersAllowed: false,
    sourceUpdatedAt: '2026-01-08',
    requiresVerification: true,
  },
  {
    id: 'ecs-demo-established-campsite-06',
    name: 'Ridge Cabin Camp',
    latitude: 37.9058,
    longitude: -119.7201,
    campsiteType: 'cabin',
    source: 'COUNTY',
    feeStatus: 'paid',
    reservationStatus: 'reservable',
    amenities: ['water', 'toilets', 'picnic_table', 'fire_ring'],
    operatorName: 'County recreation office',
    seasonDescription: 'Booking window changes seasonally',
    tentAllowed: false,
    rvAllowed: false,
    trailersAllowed: false,
    sourceUpdatedAt: '2026-01-06',
    requiresVerification: true,
  },
];
